#!/usr/bin/env python3
"""Generate USD validation fixtures from a schema description.

Reads the canonical JSON schema (src/usd-preview-surface-schema.json -- the same
file that drives the validator's input-type table) describing shader prim types
and their input name -> value type, then emits synthetic `.usda` fixtures into an
output directory:

  <type>-valid.usda          every input authored with the correct type   (EXPECT-OK)
  <type>-badtype.usda        a couple of inputs given the wrong type       (shade.preview.inputType)
  <type>-unknown-input.usda  an input name not in the schema               (shade.preview.unknownInput)

Each fixture embeds machine-readable `# EXPECT:` / `# EXPECT-OK` markers that
run-validation-suite.py checks against `tusdcat --validate-all` output.

This keeps the fixtures in lock-step with the schema: regenerate after the
schema (or the validator's table) changes.

Usage:
  python3 gen_validation_fixtures.py [--schema src/usd-preview-surface-schema.json]
                                     [--outdir generated]
"""

import argparse
import json
import os

# A representative authored value for each value type.
SAMPLE_VALUE = {
    "color3f": "(0.1, 0.2, 0.3)",
    "color4f": "(0.1, 0.2, 0.3, 1)",
    "normal3f": "(0, 0, 1)",
    "point3f": "(0, 0, 0)",
    "vector3f": "(0, 0, 1)",
    "float": "0.5",
    "float2": "(0, 0)",
    "int": "0",
    "token": '"opacity"',
    "asset": "@./tex.png@",
}

# A "wrong but valid" type to author for a given expected type, guaranteed to be
# a real type mismatch the validator catches (different underlying base type).
WRONG_TYPE = {
    "color3f": "float",
    "color4f": "float",
    "normal3f": "float",
    "point3f": "float",
    "vector3f": "float",
    "float": "color3f",
    "float2": "color3f",
    "int": "color3f",
    "token": "float",
    "asset": "float",
}


def sample_value(typ):
    return SAMPLE_VALUE.get(typ, "0")


def header(lines):
    """Build the standard fixture preamble with EXPECT markers."""
    out = ["#usda 1.0"]
    out.extend(lines)
    out.append("(")
    out.append('    doc = "GENERATED by gen_validation_fixtures.py -- do not edit by hand."')
    out.append('    defaultPrim = "World"')
    out.append("    metersPerUnit = 0.01")
    out.append('    upAxis = "Y"')
    out.append(")")
    out.append("")
    return out


def shader_block(type_name, input_lines):
    """A Material containing one Shader of `type_name` (proper encapsulation)."""
    out = []
    out.append('def Xform "World"')
    out.append("{")
    out.append('    def Material "mat"')
    out.append("    {")
    out.append("        token outputs:surface.connect = </World/mat/surface.outputs:surface>")
    out.append("")
    out.append('        def Shader "surface"')
    out.append("        {")
    out.append('            uniform token info:id = "%s"' % type_name)
    for line in input_lines:
        out.append("            " + line)
    out.append("            token outputs:surface")
    out.append("        }")
    out.append("    }")
    out.append("}")
    out.append("")
    return out


def attr_line(typ, name, value):
    return "%s inputs:%s = %s" % (typ, name, value)


def gen_valid(type_name, inputs):
    lines = header(["# EXPECT-OK"])
    input_lines = [attr_line(typ, name, sample_value(typ))
                   for name, typ in sorted(inputs.items())]
    lines += shader_block(type_name, input_lines)
    return "\n".join(lines)


def gen_badtype(type_name, inputs):
    # Flip the first color/normal input and the first scalar input to a wrong
    # (but valid) type so two `shade.preview.inputType` warnings are produced.
    sorted_inputs = sorted(inputs.items())
    flipped = 0
    targets = set()
    # one vector-ish input, one scalar input
    for name, typ in sorted_inputs:
        base_vec = typ in ("color3f", "color4f", "normal3f", "point3f", "vector3f")
        if base_vec and "vec" not in targets:
            targets.add("vec")
            targets.add(name)
        elif typ in ("float", "int") and "scalar" not in targets:
            targets.add("scalar")
            targets.add(name)

    input_lines = []
    for name, typ in sorted_inputs:
        if name in targets:
            input_lines.append(attr_line(WRONG_TYPE[typ], name, sample_value(WRONG_TYPE[typ])))
            flipped += 1
        else:
            input_lines.append(attr_line(typ, name, sample_value(typ)))

    lines = header(["# EXPECT: shade.preview.inputType"])
    lines += shader_block(type_name, input_lines)
    return "\n".join(lines), flipped


def gen_unknown(type_name, inputs):
    input_lines = [attr_line(typ, name, sample_value(typ))
                   for name, typ in sorted(inputs.items())]
    # A misspelled / non-schema input name.
    input_lines.append(attr_line("float", "bogusInput", "0.5"))
    lines = header(["# EXPECT: shade.preview.unknownInput"])
    lines += shader_block(type_name, input_lines)
    return "\n".join(lines)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(os.path.dirname(os.path.dirname(here)))
    default_schema = os.path.join(repo_root, "src", "usd-preview-surface-schema.json")
    ap = argparse.ArgumentParser()
    ap.add_argument("--schema", default=default_schema)
    ap.add_argument("--outdir", default=os.path.join(here, "generated"))
    args = ap.parse_args()

    with open(args.schema) as f:
        schema = json.load(f)

    os.makedirs(args.outdir, exist_ok=True)
    written = []

    for type_name, desc in sorted(schema.get("shaders", {}).items()):
        inputs = desc.get("inputs", {})
        if not inputs:
            continue

        def write(suffix, text):
            path = os.path.join(args.outdir, "%s-%s.usda" % (type_name.lower(), suffix))
            with open(path, "w") as fp:
                fp.write(text if text.endswith("\n") else text + "\n")
            written.append(path)

        write("valid", gen_valid(type_name, inputs))
        bad, n = gen_badtype(type_name, inputs)
        write("badtype", bad)
        write("unknown-input", gen_unknown(type_name, inputs))

    print("Generated %d fixture(s) in %s:" % (len(written), args.outdir))
    for p in written:
        print("  " + os.path.relpath(p, here))


if __name__ == "__main__":
    main()
