// SPDX-License-Identifier: Apache 2.0
// Copyright 2025, Light Transport Entertainment Inc.
//
// USDC Validation Tool
//
// Reads back USDC files generated by crate-writer using TinyUSDZ
// and validates that the content matches expectations.
//

#include "tinyusdz.hh"
#include "stage.hh"
#include "usdGeom.hh"
#include <iostream>
#include <string>

using namespace tinyusdz;

void PrintPrimInfo(const Prim& prim, int depth = 0) {
  std::string indent(depth * 2, ' ');

  std::cout << indent << "Prim: " << prim.absolute_path().full_path_name()
            << " (type: " << prim.type_name() << ")\n";

  // Print specifier
  std::cout << indent << "  Specifier: ";
  switch(prim.specifier()) {
    case Specifier::Def: std::cout << "def\n"; break;
    case Specifier::Over: std::cout << "over\n"; break;
    case Specifier::Class: std::cout << "class\n"; break;
    default: std::cout << "unknown\n"; break;
  }

  // For GeomMesh, print points info
  if (prim.type_name() == "Mesh") {
    if (const auto* mesh = prim.data().as<GeomMesh>()) {
      if (mesh->points.has_value()) {
        auto points_attr = mesh->points.get_value();
        if (points_attr && points_attr->has_default()) {
          std::vector<value::point3f> points;
          if (points_attr->get_default(&points)) {
            std::cout << indent << "  Points: " << points.size() << " vertices\n";
            if (points.size() > 0 && points.size() <= 4) {
              for (size_t i = 0; i < points.size(); ++i) {
                std::cout << indent << "    [" << i << "]: ("
                          << points[i][0] << ", "
                          << points[i][1] << ", "
                          << points[i][2] << ")\n";
              }
            }
          }
        }
      }

      if (mesh->normals.has_value()) {
        auto normals_attr = mesh->normals.get_value();
        if (normals_attr && normals_attr->has_default()) {
          std::vector<value::normal3f> normals;
          if (normals_attr->get_default(&normals)) {
            std::cout << indent << "  Normals: " << normals.size() << " normals\n";
          }
        }
      }
    }
  }

  // For GeomCube, print xformOps
  if (prim.type_name() == "Cube" || prim.type_name() == "Xform") {
    const Xformable* xformable = nullptr;

    if (auto* cube = prim.data().as<GeomCube>()) {
      xformable = static_cast<const Xformable*>(cube);
    } else if (auto* xform = prim.data().as<Xform>()) {
      xformable = xform;
    }

    if (xformable && !xformable->xformOps.empty()) {
      std::cout << indent << "  XformOps: " << xformable->xformOps.size() << " ops\n";
      for (const auto& xformOp : xformable->xformOps) {
        std::cout << indent << "    - ";
        switch(xformOp.op_type) {
          case XformOp::OpType::Translate: std::cout << "translate"; break;
          case XformOp::OpType::RotateX: std::cout << "rotateX"; break;
          case XformOp::OpType::RotateY: std::cout << "rotateY"; break;
          case XformOp::OpType::RotateZ: std::cout << "rotateZ"; break;
          case XformOp::OpType::RotateXYZ: std::cout << "rotateXYZ"; break;
          case XformOp::OpType::Scale: std::cout << "scale"; break;
          case XformOp::OpType::Transform: std::cout << "transform"; break;
          case XformOp::OpType::Orient: std::cout << "orient"; break;
          default: std::cout << "other"; break;
        }
        if (!xformOp.suffix.empty()) {
          std::cout << ":" << xformOp.suffix;
        }
        std::cout << "\n";
      }
    }

    // Print size for Cube
    if (auto* cube = prim.data().as<GeomCube>()) {
      if (cube->size.authored()) {
        const Animatable<double>& size_animatable = cube->size.get_value();
        if (size_animatable.has_default()) {
          double size;
          if (size_animatable.get_default(&size)) {
            std::cout << indent << "  Size: " << size << "\n";
          }
        }
      }
    }
  }

  // Recurse into children
  for (const auto& child : prim.children()) {
    PrintPrimInfo(child, depth + 1);
  }
}

int main(int argc, char** argv) {
  if (argc < 2) {
    std::cerr << "Usage: " << argv[0] << " <file.usdc>\n";
    return 1;
  }

  std::string filepath = argv[1];

  std::cout << "Validating USDC file: " << filepath << "\n";
  std::cout << "==========================================\n\n";

  // Load the USDC file
  tinyusdz::Stage stage;
  std::string warn, err;

  bool ret = tinyusdz::LoadUSDFromFile(filepath, &stage, &warn, &err);

  if (!ret) {
    std::cerr << "ERROR: Failed to load USDC file\n";
    std::cerr << "Error: " << err << "\n";
    return 1;
  }

  if (!warn.empty()) {
    std::cout << "Warning: " << warn << "\n\n";
  }

  std::cout << "✓ File loaded successfully\n\n";

  // Print stage metadata
  std::cout << "Stage metadata:\n";
  if (stage.metas().metersPerUnit.authored()) {
    const Animatable<double>& mpu_animatable = stage.metas().metersPerUnit.get_value();
    if (mpu_animatable.has_default()) {
      double mpu;
      if (mpu_animatable.get_default(&mpu)) {
        std::cout << "  metersPerUnit: " << mpu << "\n";
      }
    }
  }
  if (stage.metas().upAxis.authored()) {
    const Animatable<Axis>& upAxis_animatable = stage.metas().upAxis.get_value();
    if (upAxis_animatable.has_default()) {
      Axis upAxis;
      if (upAxis_animatable.get_default(&upAxis)) {
        std::string axis_str = (upAxis == Axis::X) ? "X" : (upAxis == Axis::Y) ? "Y" : "Z";
        std::cout << "  upAxis: " << axis_str << "\n";
      }
    }
  }
  std::cout << "\n";

  // Print prim hierarchy
  std::cout << "Prim hierarchy:\n";
  std::cout << "Root prims: " << stage.root_prims().size() << "\n\n";

  for (const auto& prim : stage.root_prims()) {
    PrintPrimInfo(prim);
  }

  std::cout << "\n✓ Validation complete\n";

  return 0;
}
