// SPDX-License-Identifier: Apache-2.0
#include "vk/vk_renderer.hh"

#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>

#include <cmath>
#include <cstdio>
#include <cstring>

#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_vulkan.h"
#include "light3d/math.h"
#include "log.hh"

// Generated by glslangValidator (see vk/vulkan.cmake): unsigned int *_spv[].
#include "line_frag.spv.h"
#include "line_vert.spv.h"
#include "mesh_frag.spv.h"
#include "mesh_vert.spv.h"
#if defined(TUSDVIEW_HAVE_RT_SHADER) && TUSDVIEW_HAVE_RT_SHADER
#include "raytrace_comp.spv.h"  // ray-query compute shader (when glslang supports it)
#endif

namespace tusdview {

namespace {

#define VK_CHECK(expr, msg)                                  \
  do {                                                       \
    VkResult _r = (expr);                                    \
    if (_r != VK_SUCCESS) {                                  \
      if (err) *err = std::string(msg) + " (VkResult " +     \
                      std::to_string(static_cast<int>(_r)) + ")"; \
      return false;                                          \
    }                                                        \
  } while (0)

light3d::Mat4 ToMat4(const float* m) {
  light3d::Mat4 r;
  std::memcpy(r.m, m, sizeof(r.m));
  return r;
}

void NormalMatrix3(const float m[16], float out9[9]) {
  const float a00 = m[0], a01 = m[4], a02 = m[8];
  const float a10 = m[1], a11 = m[5], a12 = m[9];
  const float a20 = m[2], a21 = m[6], a22 = m[10];
  const float det = a00 * (a11 * a22 - a12 * a21) -
                    a01 * (a10 * a22 - a12 * a20) +
                    a02 * (a10 * a21 - a11 * a20);
  if (std::fabs(det) < 1e-12f) {
    out9[0] = 1; out9[1] = 0; out9[2] = 0;
    out9[3] = 0; out9[4] = 1; out9[5] = 0;
    out9[6] = 0; out9[7] = 0; out9[8] = 1;
    return;
  }
  const float inv = 1.0f / det;
  out9[0] = (a11 * a22 - a12 * a21) * inv;
  out9[1] = -(a01 * a22 - a02 * a21) * inv;
  out9[2] = (a01 * a12 - a02 * a11) * inv;
  out9[3] = -(a10 * a22 - a12 * a20) * inv;
  out9[4] = (a00 * a22 - a02 * a20) * inv;
  out9[5] = -(a00 * a12 - a02 * a10) * inv;
  out9[6] = (a10 * a21 - a11 * a20) * inv;
  out9[7] = -(a00 * a21 - a01 * a20) * inv;
  out9[8] = (a00 * a11 - a01 * a10) * inv;
}

struct PushC {
  float mvp[16];
  float nmat[12];  // 3 columns padded to vec4
  float baseColor[4];
};

// Ray-tracing compute push constants (must match raytrace.comp).
struct RtPushC {
  float invViewProj[16];
  float camPos[4];
  float lightDir[4];
  float clearColor[4];
};

// Per-mesh descriptor for the RT shader (scalar layout, must match raytrace.comp).
struct MeshDescGPU {
  uint64_t vtxAddr;
  uint64_t idxAddr;
  uint32_t matId;
  uint32_t pad;
  float nrm0[4];  // normal matrix columns (xyz used)
  float nrm1[4];
  float nrm2[4];
};
static_assert(sizeof(MeshDescGPU) == 72, "MeshDescGPU must be tightly packed (scalar)");

// General column-major 4x4 inverse (for the camera's inverse view-projection).
bool Mat4Inverse(const float m[16], float out[16]) {
  float inv[16];
  inv[0] = m[5]*m[10]*m[15] - m[5]*m[11]*m[14] - m[9]*m[6]*m[15] +
           m[9]*m[7]*m[14] + m[13]*m[6]*m[11] - m[13]*m[7]*m[10];
  inv[4] = -m[4]*m[10]*m[15] + m[4]*m[11]*m[14] + m[8]*m[6]*m[15] -
           m[8]*m[7]*m[14] - m[12]*m[6]*m[11] + m[12]*m[7]*m[10];
  inv[8] = m[4]*m[9]*m[15] - m[4]*m[11]*m[13] - m[8]*m[5]*m[15] +
           m[8]*m[7]*m[13] + m[12]*m[5]*m[11] - m[12]*m[7]*m[9];
  inv[12] = -m[4]*m[9]*m[14] + m[4]*m[10]*m[13] + m[8]*m[5]*m[14] -
            m[8]*m[6]*m[13] - m[12]*m[5]*m[10] + m[12]*m[6]*m[9];
  inv[1] = -m[1]*m[10]*m[15] + m[1]*m[11]*m[14] + m[9]*m[2]*m[15] -
           m[9]*m[3]*m[14] - m[13]*m[2]*m[11] + m[13]*m[3]*m[10];
  inv[5] = m[0]*m[10]*m[15] - m[0]*m[11]*m[14] - m[8]*m[2]*m[15] +
           m[8]*m[3]*m[14] + m[12]*m[2]*m[11] - m[12]*m[3]*m[10];
  inv[9] = -m[0]*m[9]*m[15] + m[0]*m[11]*m[13] + m[8]*m[1]*m[15] -
           m[8]*m[3]*m[13] - m[12]*m[1]*m[11] + m[12]*m[3]*m[9];
  inv[13] = m[0]*m[9]*m[14] - m[0]*m[10]*m[13] - m[8]*m[1]*m[14] +
            m[8]*m[2]*m[13] + m[12]*m[1]*m[10] - m[12]*m[2]*m[9];
  inv[2] = m[1]*m[6]*m[15] - m[1]*m[7]*m[14] - m[5]*m[2]*m[15] +
           m[5]*m[3]*m[14] + m[13]*m[2]*m[7] - m[13]*m[3]*m[6];
  inv[6] = -m[0]*m[6]*m[15] + m[0]*m[7]*m[14] + m[4]*m[2]*m[15] -
           m[4]*m[3]*m[14] - m[12]*m[2]*m[7] + m[12]*m[3]*m[6];
  inv[10] = m[0]*m[5]*m[15] - m[0]*m[7]*m[13] - m[4]*m[1]*m[15] +
            m[4]*m[3]*m[13] + m[12]*m[1]*m[7] - m[12]*m[3]*m[5];
  inv[14] = -m[0]*m[5]*m[14] + m[0]*m[6]*m[13] + m[4]*m[1]*m[14] -
            m[4]*m[2]*m[13] - m[12]*m[1]*m[6] + m[12]*m[2]*m[5];
  inv[3] = -m[1]*m[6]*m[11] + m[1]*m[7]*m[10] + m[5]*m[2]*m[11] -
           m[5]*m[3]*m[10] - m[9]*m[2]*m[7] + m[9]*m[3]*m[6];
  inv[7] = m[0]*m[6]*m[11] - m[0]*m[7]*m[10] - m[4]*m[2]*m[11] +
           m[4]*m[3]*m[10] + m[8]*m[2]*m[7] - m[8]*m[3]*m[6];
  inv[11] = -m[0]*m[5]*m[11] + m[0]*m[7]*m[9] + m[4]*m[1]*m[11] -
            m[4]*m[3]*m[9] - m[8]*m[1]*m[7] + m[8]*m[3]*m[5];
  inv[15] = m[0]*m[5]*m[10] - m[0]*m[6]*m[9] - m[4]*m[1]*m[10] +
            m[4]*m[2]*m[9] + m[8]*m[1]*m[6] - m[8]*m[2]*m[5];
  float det = m[0]*inv[0] + m[1]*inv[4] + m[2]*inv[8] + m[3]*inv[12];
  if (std::fabs(det) < 1e-20f) return false;
  det = 1.0f / det;
  for (int i = 0; i < 16; ++i) out[i] = inv[i] * det;
  return true;
}

}  // namespace

VulkanRenderer::~VulkanRenderer() { shutdown(); }

uint32_t VulkanRenderer::findMemoryType(uint32_t typeBits,
                                        VkMemoryPropertyFlags props) const {
  VkPhysicalDeviceMemoryProperties mp;
  vkGetPhysicalDeviceMemoryProperties(phys_, &mp);
  for (uint32_t i = 0; i < mp.memoryTypeCount; ++i) {
    if ((typeBits & (1u << i)) &&
        (mp.memoryTypes[i].propertyFlags & props) == props) {
      return i;
    }
  }
  return 0;
}

bool VulkanRenderer::createInstance(std::string* err) {
  VkApplicationInfo app{};
  app.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
  app.pApplicationName = "tusdview";
  // 1.2 for bufferDeviceAddress (core) + ray query against acceleration structures.
  app.apiVersion = VK_API_VERSION_1_2;

  // Windowed: GLFW tells us which surface extensions it needs. Headless: none
  // (no surface), so we also don't depend on GLFW being initialized.
  std::vector<const char*> exts;
  if (!headless_) {
    uint32_t extCount = 0;
    const char** glfwExt = glfwGetRequiredInstanceExtensions(&extCount);
    exts.assign(glfwExt, glfwExt + extCount);
  }

  VkInstanceCreateInfo ci{};
  ci.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
  ci.pApplicationInfo = &app;
  ci.enabledExtensionCount = static_cast<uint32_t>(exts.size());
  ci.ppEnabledExtensionNames = exts.data();
  VK_CHECK(vkCreateInstance(&ci, nullptr, &instance_), "vkCreateInstance");
  return true;
}

bool VulkanRenderer::createSurface(std::string* err) {
  VK_CHECK(glfwCreateWindowSurface(instance_, window_, nullptr, &surface_),
           "glfwCreateWindowSurface");
  return true;
}

bool VulkanRenderer::pickPhysicalDevice(std::string* err) {
  uint32_t n = 0;
  vkEnumeratePhysicalDevices(instance_, &n, nullptr);
  if (n == 0) {
    if (err) *err = "no Vulkan physical devices";
    return false;
  }
  std::vector<VkPhysicalDevice> devs(n);
  vkEnumeratePhysicalDevices(instance_, &n, devs.data());

  VkPhysicalDevice fallback = VK_NULL_HANDLE;
  uint32_t fallbackFam = 0;
  for (VkPhysicalDevice d : devs) {
    uint32_t qn = 0;
    vkGetPhysicalDeviceQueueFamilyProperties(d, &qn, nullptr);
    std::vector<VkQueueFamilyProperties> qfp(qn);
    vkGetPhysicalDeviceQueueFamilyProperties(d, &qn, qfp.data());
    for (uint32_t i = 0; i < qn; ++i) {
      VkBool32 present = VK_TRUE;  // headless: presentation not required
      if (!headless_) vkGetPhysicalDeviceSurfaceSupportKHR(d, i, surface_, &present);
      if ((qfp[i].queueFlags & VK_QUEUE_GRAPHICS_BIT) && present) {
        VkPhysicalDeviceProperties props;
        vkGetPhysicalDeviceProperties(d, &props);
        if (props.deviceType == VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU) {
          phys_ = d;
          queueFamily_ = i;
          return true;
        }
        if (fallback == VK_NULL_HANDLE) {
          fallback = d;
          fallbackFam = i;
        }
      }
    }
  }
  if (fallback != VK_NULL_HANDLE) {
    phys_ = fallback;
    queueFamily_ = fallbackFam;
    return true;
  }
  if (err) *err = "no graphics+present queue family";
  return false;
}

void VulkanRenderer::detectRtSupport() {
  rtSupported_ = false;
#if defined(TUSDVIEW_HAVE_RT_SHADER) && TUSDVIEW_HAVE_RT_SHADER
  if (!phys_) return;

  // Required device extensions for the ray-query path. (descriptor_indexing,
  // buffer_device_address and spirv_1_4 are Vulkan 1.2 core, so not listed here.)
  const char* needed[] = {VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME,
                          VK_KHR_RAY_QUERY_EXTENSION_NAME,
                          VK_KHR_DEFERRED_HOST_OPERATIONS_EXTENSION_NAME};
  uint32_t n = 0;
  vkEnumerateDeviceExtensionProperties(phys_, nullptr, &n, nullptr);
  std::vector<VkExtensionProperties> have(n);
  vkEnumerateDeviceExtensionProperties(phys_, nullptr, &n, have.data());
  for (const char* req : needed) {
    bool found = false;
    for (const auto& e : have) {
      if (std::strcmp(e.extensionName, req) == 0) { found = true; break; }
    }
    if (!found) {
      LOGD("ray tracing: missing device extension: %s", req);
      return;  // missing extension -> stay on rasterization
    }
  }

  // Confirm the feature bits are actually enabled-able.
  VkPhysicalDeviceRayQueryFeaturesKHR rqf{};
  rqf.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_QUERY_FEATURES_KHR;
  VkPhysicalDeviceAccelerationStructureFeaturesKHR asf{};
  asf.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ACCELERATION_STRUCTURE_FEATURES_KHR;
  asf.pNext = &rqf;
  VkPhysicalDeviceBufferDeviceAddressFeatures bda{};
  bda.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES;
  bda.pNext = &asf;
  VkPhysicalDeviceFeatures2 f2{};
  f2.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2;
  f2.pNext = &bda;
  vkGetPhysicalDeviceFeatures2(phys_, &f2);
  if (!rqf.rayQuery || !asf.accelerationStructure || !bda.bufferDeviceAddress) {
    LOGD("ray tracing: feature veto: rayQuery=%d as=%d bda=%d",
         int(rqf.rayQuery), int(asf.accelerationStructure), int(bda.bufferDeviceAddress));
    return;
  }

  // Cache the scratch-buffer alignment requirement.
  VkPhysicalDeviceAccelerationStructurePropertiesKHR asp{};
  asp.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ACCELERATION_STRUCTURE_PROPERTIES_KHR;
  VkPhysicalDeviceProperties2 p2{};
  p2.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2;
  p2.pNext = &asp;
  vkGetPhysicalDeviceProperties2(phys_, &p2);
  if (asp.minAccelerationStructureScratchOffsetAlignment > 0) {
    scratchAlign_ = asp.minAccelerationStructureScratchOffsetAlignment;
  }

  rtSupported_ = true;  // device-side OK; PFN load in createDevice may still veto
#endif
}

bool VulkanRenderer::createDevice(std::string* err) {
  detectRtSupport();

  float prio = 1.0f;
  VkDeviceQueueCreateInfo qci{};
  qci.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
  qci.queueFamilyIndex = queueFamily_;
  qci.queueCount = 1;
  qci.pQueuePriorities = &prio;

  // Swapchain extension only when presenting (its instance-surface dependency is
  // not enabled in the headless path).
  std::vector<const char*> devExts;
  if (!headless_) devExts.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
  VkDeviceCreateInfo ci{};
  ci.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
  ci.queueCreateInfoCount = 1;
  ci.pQueueCreateInfos = &qci;

  // Ray-tracing feature chain (only when supported; otherwise device is created
  // exactly as before so the rasterization path is unaffected).
  VkPhysicalDeviceRayQueryFeaturesKHR rqf{};
  rqf.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_QUERY_FEATURES_KHR;
  rqf.rayQuery = VK_TRUE;
  VkPhysicalDeviceAccelerationStructureFeaturesKHR asf{};
  asf.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ACCELERATION_STRUCTURE_FEATURES_KHR;
  asf.accelerationStructure = VK_TRUE;
  asf.pNext = &rqf;
  VkPhysicalDeviceBufferDeviceAddressFeatures bda{};
  bda.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES;
  bda.bufferDeviceAddress = VK_TRUE;
  bda.pNext = &asf;
  if (rtSupported_) {
    devExts.push_back(VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME);
    devExts.push_back(VK_KHR_RAY_QUERY_EXTENSION_NAME);
    devExts.push_back(VK_KHR_DEFERRED_HOST_OPERATIONS_EXTENSION_NAME);
    ci.pNext = &bda;
  }
  ci.enabledExtensionCount = static_cast<uint32_t>(devExts.size());
  ci.ppEnabledExtensionNames = devExts.data();
  VK_CHECK(vkCreateDevice(phys_, &ci, nullptr, &device_), "vkCreateDevice");
  vkGetDeviceQueue(device_, queueFamily_, 0, &queue_);

  // Load the RT entrypoints (extension functions aren't statically exported).
  if (rtSupported_) {
    // bufferDeviceAddress is Vulkan 1.2 core here (not the KHR extension), so the
    // core entrypoint is what's exported; fall back to the KHR alias.
    pfnGetBufferDeviceAddress_ =
        reinterpret_cast<PFN_vkGetBufferDeviceAddressKHR>(
            vkGetDeviceProcAddr(device_, "vkGetBufferDeviceAddress"));
    if (!pfnGetBufferDeviceAddress_) {
      pfnGetBufferDeviceAddress_ = reinterpret_cast<PFN_vkGetBufferDeviceAddressKHR>(
          vkGetDeviceProcAddr(device_, "vkGetBufferDeviceAddressKHR"));
    }
    pfnGetASBuildSizes_ = reinterpret_cast<PFN_vkGetAccelerationStructureBuildSizesKHR>(
        vkGetDeviceProcAddr(device_, "vkGetAccelerationStructureBuildSizesKHR"));
    pfnCreateAS_ = reinterpret_cast<PFN_vkCreateAccelerationStructureKHR>(
        vkGetDeviceProcAddr(device_, "vkCreateAccelerationStructureKHR"));
    pfnDestroyAS_ = reinterpret_cast<PFN_vkDestroyAccelerationStructureKHR>(
        vkGetDeviceProcAddr(device_, "vkDestroyAccelerationStructureKHR"));
    pfnCmdBuildAS_ = reinterpret_cast<PFN_vkCmdBuildAccelerationStructuresKHR>(
        vkGetDeviceProcAddr(device_, "vkCmdBuildAccelerationStructuresKHR"));
    pfnGetASDeviceAddress_ =
        reinterpret_cast<PFN_vkGetAccelerationStructureDeviceAddressKHR>(
            vkGetDeviceProcAddr(device_, "vkGetAccelerationStructureDeviceAddressKHR"));
    if (!pfnGetBufferDeviceAddress_ || !pfnGetASBuildSizes_ || !pfnCreateAS_ ||
        !pfnDestroyAS_ || !pfnCmdBuildAS_ || !pfnGetASDeviceAddress_) {
      rtSupported_ = false;  // any missing entrypoint -> rasterization only
      LOGD("ray tracing: PFN load failed: bda=%p sizes=%p create=%p destroy=%p "
           "build=%p addr=%p",
           (void*)pfnGetBufferDeviceAddress_, (void*)pfnGetASBuildSizes_,
           (void*)pfnCreateAS_, (void*)pfnDestroyAS_, (void*)pfnCmdBuildAS_,
           (void*)pfnGetASDeviceAddress_);
    }
  }
  LOGD("ray tracing: rtSupported_=%d after device creation", rtSupported_ ? 1 : 0);
  return true;
}

bool VulkanRenderer::createSwapchain(std::string* err) {
  VkSurfaceCapabilitiesKHR caps;
  vkGetPhysicalDeviceSurfaceCapabilitiesKHR(phys_, surface_, &caps);

  uint32_t fn = 0;
  vkGetPhysicalDeviceSurfaceFormatsKHR(phys_, surface_, &fn, nullptr);
  std::vector<VkSurfaceFormatKHR> formats(fn);
  vkGetPhysicalDeviceSurfaceFormatsKHR(phys_, surface_, &fn, formats.data());
  VkSurfaceFormatKHR fmt = formats[0];
  for (const auto& f : formats) {
    if (f.format == VK_FORMAT_B8G8R8A8_UNORM &&
        f.colorSpace == VK_COLOR_SPACE_SRGB_NONLINEAR_KHR) {
      fmt = f;
      break;
    }
  }
  swapFormat_ = fmt.format;

  VkExtent2D extent = caps.currentExtent;
  if (extent.width == 0xFFFFFFFFu) {
    int w = 0, h = 0;
    glfwGetFramebufferSize(window_, &w, &h);
    extent.width = static_cast<uint32_t>(w);
    extent.height = static_cast<uint32_t>(h);
  }
  if (extent.width == 0) extent.width = 1;
  if (extent.height == 0) extent.height = 1;
  swapExtent_ = extent;

  uint32_t imageCount = caps.minImageCount + 1;
  if (caps.maxImageCount > 0 && imageCount > caps.maxImageCount) {
    imageCount = caps.maxImageCount;
  }

  VkSwapchainCreateInfoKHR ci{};
  ci.sType = VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR;
  ci.surface = surface_;
  ci.minImageCount = imageCount;
  ci.imageFormat = fmt.format;
  ci.imageColorSpace = fmt.colorSpace;
  ci.imageExtent = extent;
  ci.imageArrayLayers = 1;
  ci.imageUsage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
  ci.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
  ci.preTransform = caps.currentTransform;
  ci.compositeAlpha = VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;
  ci.presentMode = VK_PRESENT_MODE_FIFO_KHR;
  ci.clipped = VK_TRUE;
  VK_CHECK(vkCreateSwapchainKHR(device_, &ci, nullptr, &swapchain_),
           "vkCreateSwapchainKHR");

  uint32_t sc = 0;
  vkGetSwapchainImagesKHR(device_, swapchain_, &sc, nullptr);
  swapImages_.resize(sc);
  vkGetSwapchainImagesKHR(device_, swapchain_, &sc, swapImages_.data());
  return true;
}

bool VulkanRenderer::createSwapchainViews(std::string* err) {
  swapViews_.resize(swapImages_.size());
  for (size_t i = 0; i < swapImages_.size(); ++i) {
    VkImageViewCreateInfo ci{};
    ci.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    ci.image = swapImages_[i];
    ci.viewType = VK_IMAGE_VIEW_TYPE_2D;
    ci.format = swapFormat_;
    ci.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    ci.subresourceRange.levelCount = 1;
    ci.subresourceRange.layerCount = 1;
    VK_CHECK(vkCreateImageView(device_, &ci, nullptr, &swapViews_[i]),
             "swapchain image view");
  }
  return true;
}

bool VulkanRenderer::createHeadlessSwapchain(std::string* err) {
  // Own a small ring of color images to stand in for swapchain images. RGBA8 so
  // the composite reads back without a channel swizzle; TRANSFER_SRC so the
  // render pass can leave it copy-ready for captureWindow().
  swapFormat_ = VK_FORMAT_R8G8B8A8_UNORM;
  swapExtent_ = {static_cast<uint32_t>(headlessW_ > 0 ? headlessW_ : 1),
                 static_cast<uint32_t>(headlessH_ > 0 ? headlessH_ : 1)};
  const size_t count = kFramesInFlight;
  swapImages_.resize(count);
  swapMem_.resize(count, VK_NULL_HANDLE);
  swapViews_.resize(count);
  for (size_t i = 0; i < count; ++i) {
    VkImageCreateInfo ici{};
    ici.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    ici.imageType = VK_IMAGE_TYPE_2D;
    ici.format = swapFormat_;
    ici.extent = {swapExtent_.width, swapExtent_.height, 1};
    ici.mipLevels = 1;
    ici.arrayLayers = 1;
    ici.samples = VK_SAMPLE_COUNT_1_BIT;
    ici.tiling = VK_IMAGE_TILING_OPTIMAL;
    ici.usage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT;
    ici.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    VK_CHECK(vkCreateImage(device_, &ici, nullptr, &swapImages_[i]),
             "headless composite image");
    VkMemoryRequirements req;
    vkGetImageMemoryRequirements(device_, swapImages_[i], &req);
    VkMemoryAllocateInfo ai{};
    ai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    ai.allocationSize = req.size;
    ai.memoryTypeIndex =
        findMemoryType(req.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    VK_CHECK(vkAllocateMemory(device_, &ai, nullptr, &swapMem_[i]),
             "headless composite memory");
    vkBindImageMemory(device_, swapImages_[i], swapMem_[i], 0);

    VkImageViewCreateInfo vci{};
    vci.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    vci.image = swapImages_[i];
    vci.viewType = VK_IMAGE_VIEW_TYPE_2D;
    vci.format = swapFormat_;
    vci.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    vci.subresourceRange.levelCount = 1;
    vci.subresourceRange.layerCount = 1;
    VK_CHECK(vkCreateImageView(device_, &vci, nullptr, &swapViews_[i]),
             "headless composite view");
  }
  return true;
}

bool VulkanRenderer::createSwapchainRenderPass(std::string* err) {
  VkAttachmentDescription color{};
  color.format = swapFormat_;
  color.samples = VK_SAMPLE_COUNT_1_BIT;
  color.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
  color.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
  color.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
  color.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
  color.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
  // Headless: leave the composite copy-ready for captureWindow(); windowed:
  // hand it to the presentation engine.
  color.finalLayout = headless_ ? VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL
                                 : VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;

  VkAttachmentReference ref{};
  ref.attachment = 0;
  ref.layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;

  VkSubpassDescription sub{};
  sub.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
  sub.colorAttachmentCount = 1;
  sub.pColorAttachments = &ref;

  VkSubpassDependency dep{};
  dep.srcSubpass = VK_SUBPASS_EXTERNAL;
  dep.dstSubpass = 0;
  dep.srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  dep.dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  dep.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;

  VkRenderPassCreateInfo ci{};
  ci.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
  ci.attachmentCount = 1;
  ci.pAttachments = &color;
  ci.subpassCount = 1;
  ci.pSubpasses = &sub;
  ci.dependencyCount = 1;
  ci.pDependencies = &dep;
  VK_CHECK(vkCreateRenderPass(device_, &ci, nullptr, &swapRenderPass_),
           "swapchain render pass");
  return true;
}

bool VulkanRenderer::createSwapchainFramebuffers(std::string* err) {
  swapFramebuffers_.resize(swapViews_.size());
  for (size_t i = 0; i < swapViews_.size(); ++i) {
    VkFramebufferCreateInfo ci{};
    ci.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
    ci.renderPass = swapRenderPass_;
    ci.attachmentCount = 1;
    ci.pAttachments = &swapViews_[i];
    ci.width = swapExtent_.width;
    ci.height = swapExtent_.height;
    ci.layers = 1;
    VK_CHECK(vkCreateFramebuffer(device_, &ci, nullptr, &swapFramebuffers_[i]),
             "swapchain framebuffer");
  }
  return true;
}

bool VulkanRenderer::createOffscreenRenderPass(std::string* err) {
  VkAttachmentDescription atts[2]{};
  atts[0].format = colorFormat_;
  atts[0].samples = VK_SAMPLE_COUNT_1_BIT;
  atts[0].loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
  atts[0].storeOp = VK_ATTACHMENT_STORE_OP_STORE;
  atts[0].stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
  atts[0].stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
  atts[0].initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
  atts[0].finalLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
  atts[1].format = depthFormat_;
  atts[1].samples = VK_SAMPLE_COUNT_1_BIT;
  atts[1].loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
  atts[1].storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
  atts[1].stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
  atts[1].stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
  atts[1].initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
  atts[1].finalLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;

  VkAttachmentReference colorRef{0, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};
  VkAttachmentReference depthRef{1, VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL};

  VkSubpassDescription sub{};
  sub.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
  sub.colorAttachmentCount = 1;
  sub.pColorAttachments = &colorRef;
  sub.pDepthStencilAttachment = &depthRef;

  // Sync the offscreen color write with later fragment sampling by ImGui.
  VkSubpassDependency deps[2]{};
  deps[0].srcSubpass = VK_SUBPASS_EXTERNAL;
  deps[0].dstSubpass = 0;
  deps[0].srcStageMask = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
  deps[0].dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  deps[0].srcAccessMask = VK_ACCESS_SHADER_READ_BIT;
  deps[0].dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
  deps[1].srcSubpass = 0;
  deps[1].dstSubpass = VK_SUBPASS_EXTERNAL;
  deps[1].srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  deps[1].dstStageMask = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
  deps[1].srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
  deps[1].dstAccessMask = VK_ACCESS_SHADER_READ_BIT;

  VkRenderPassCreateInfo ci{};
  ci.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
  ci.attachmentCount = 2;
  ci.pAttachments = atts;
  ci.subpassCount = 1;
  ci.pSubpasses = &sub;
  ci.dependencyCount = 2;
  ci.pDependencies = deps;
  VK_CHECK(vkCreateRenderPass(device_, &ci, nullptr, &offscreenPass_),
           "offscreen render pass");
  return true;
}

VkShaderModule VulkanRenderer::createShader(const uint32_t* code, size_t bytes) {
  VkShaderModuleCreateInfo ci{};
  ci.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
  ci.codeSize = bytes;
  ci.pCode = code;
  VkShaderModule m = VK_NULL_HANDLE;
  vkCreateShaderModule(device_, &ci, nullptr, &m);
  return m;
}

bool VulkanRenderer::createPipeline(std::string* err) {
  VkPushConstantRange pcr{};
  pcr.stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT;
  pcr.offset = 0;
  pcr.size = sizeof(PushC);

  VkPipelineLayoutCreateInfo plci{};
  plci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
  plci.setLayoutCount = 1;
  plci.pSetLayouts = &texSetLayout_;
  plci.pushConstantRangeCount = 1;
  plci.pPushConstantRanges = &pcr;
  VK_CHECK(vkCreatePipelineLayout(device_, &plci, nullptr, &pipelineLayout_),
           "pipeline layout");

  VkShaderModule vs = createShader(mesh_vert_spv, sizeof(mesh_vert_spv));
  VkShaderModule fs = createShader(mesh_frag_spv, sizeof(mesh_frag_spv));
  if (!vs || !fs) {
    if (err) *err = "shader module creation failed";
    return false;
  }

  VkPipelineShaderStageCreateInfo stages[2]{};
  stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
  stages[0].module = vs;
  stages[0].pName = "main";
  stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
  stages[1].module = fs;
  stages[1].pName = "main";

  VkVertexInputBindingDescription bind{};
  bind.binding = 0;
  bind.stride = sizeof(DrawVertex);
  bind.inputRate = VK_VERTEX_INPUT_RATE_VERTEX;
  VkVertexInputAttributeDescription attrs[3]{};
  attrs[0] = {0, 0, VK_FORMAT_R32G32B32_SFLOAT, 0};
  attrs[1] = {1, 0, VK_FORMAT_R32G32B32_SFLOAT, 3 * sizeof(float)};
  attrs[2] = {2, 0, VK_FORMAT_R32G32_SFLOAT, 6 * sizeof(float)};

  VkPipelineVertexInputStateCreateInfo vin{};
  vin.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
  vin.vertexBindingDescriptionCount = 1;
  vin.pVertexBindingDescriptions = &bind;
  vin.vertexAttributeDescriptionCount = 3;
  vin.pVertexAttributeDescriptions = attrs;

  VkPipelineInputAssemblyStateCreateInfo ia{};
  ia.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
  ia.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

  VkPipelineViewportStateCreateInfo vp{};
  vp.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
  vp.viewportCount = 1;
  vp.scissorCount = 1;

  VkPipelineRasterizationStateCreateInfo rs{};
  rs.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
  rs.polygonMode = VK_POLYGON_MODE_FILL;
  rs.cullMode = VK_CULL_MODE_NONE;
  rs.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
  rs.lineWidth = 1.0f;

  VkPipelineMultisampleStateCreateInfo ms{};
  ms.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
  ms.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

  VkPipelineDepthStencilStateCreateInfo ds{};
  ds.sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
  ds.depthTestEnable = VK_TRUE;
  ds.depthWriteEnable = VK_TRUE;
  ds.depthCompareOp = VK_COMPARE_OP_LESS;

  VkPipelineColorBlendAttachmentState cba{};
  cba.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                       VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
  VkPipelineColorBlendStateCreateInfo cb{};
  cb.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
  cb.attachmentCount = 1;
  cb.pAttachments = &cba;

  VkDynamicState dyn[] = {VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR};
  VkPipelineDynamicStateCreateInfo dynState{};
  dynState.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
  dynState.dynamicStateCount = 2;
  dynState.pDynamicStates = dyn;

  VkGraphicsPipelineCreateInfo ci{};
  ci.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
  ci.stageCount = 2;
  ci.pStages = stages;
  ci.pVertexInputState = &vin;
  ci.pInputAssemblyState = &ia;
  ci.pViewportState = &vp;
  ci.pRasterizationState = &rs;
  ci.pMultisampleState = &ms;
  ci.pDepthStencilState = &ds;
  ci.pColorBlendState = &cb;
  ci.pDynamicState = &dynState;
  ci.layout = pipelineLayout_;
  ci.renderPass = offscreenPass_;
  ci.subpass = 0;
  VkResult r = vkCreateGraphicsPipelines(device_, VK_NULL_HANDLE, 1, &ci, nullptr,
                                         &pipeline_);
  vkDestroyShaderModule(device_, vs, nullptr);
  vkDestroyShaderModule(device_, fs, nullptr);
  if (r != VK_SUCCESS) {
    if (err) *err = "vkCreateGraphicsPipelines failed";
    return false;
  }
  return true;
}

bool VulkanRenderer::createLinePipeline(std::string* err) {
  VkPushConstantRange pcr{};
  pcr.stageFlags = VK_SHADER_STAGE_VERTEX_BIT;
  pcr.offset = 0;
  pcr.size = sizeof(float) * 16;  // mat4 vp
  VkPipelineLayoutCreateInfo plci{};
  plci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
  plci.pushConstantRangeCount = 1;
  plci.pPushConstantRanges = &pcr;
  VK_CHECK(vkCreatePipelineLayout(device_, &plci, nullptr, &lineLayout_),
           "line pipeline layout");

  VkShaderModule vs = createShader(line_vert_spv, sizeof(line_vert_spv));
  VkShaderModule fs = createShader(line_frag_spv, sizeof(line_frag_spv));
  if (!vs || !fs) {
    if (err) *err = "line shader module creation failed";
    return false;
  }

  VkPipelineShaderStageCreateInfo stages[2]{};
  stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
  stages[0].module = vs;
  stages[0].pName = "main";
  stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
  stages[1].module = fs;
  stages[1].pName = "main";

  VkVertexInputBindingDescription bind{};
  bind.binding = 0;
  bind.stride = sizeof(HelperVertex);
  bind.inputRate = VK_VERTEX_INPUT_RATE_VERTEX;
  VkVertexInputAttributeDescription attrs[2]{};
  attrs[0] = {0, 0, VK_FORMAT_R32G32B32_SFLOAT, 0};
  attrs[1] = {1, 0, VK_FORMAT_R32G32B32_SFLOAT, 3 * sizeof(float)};
  VkPipelineVertexInputStateCreateInfo vin{};
  vin.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
  vin.vertexBindingDescriptionCount = 1;
  vin.pVertexBindingDescriptions = &bind;
  vin.vertexAttributeDescriptionCount = 2;
  vin.pVertexAttributeDescriptions = attrs;

  VkPipelineInputAssemblyStateCreateInfo ia{};
  ia.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
  ia.topology = VK_PRIMITIVE_TOPOLOGY_LINE_LIST;

  VkPipelineViewportStateCreateInfo vp{};
  vp.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
  vp.viewportCount = 1;
  vp.scissorCount = 1;

  VkPipelineRasterizationStateCreateInfo rs{};
  rs.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
  rs.polygonMode = VK_POLYGON_MODE_FILL;
  rs.cullMode = VK_CULL_MODE_NONE;
  rs.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
  rs.lineWidth = 1.0f;

  VkPipelineMultisampleStateCreateInfo ms{};
  ms.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
  ms.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

  VkPipelineDepthStencilStateCreateInfo ds{};
  ds.sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
  ds.depthTestEnable = VK_TRUE;
  ds.depthWriteEnable = VK_TRUE;
  ds.depthCompareOp = VK_COMPARE_OP_LESS;

  VkPipelineColorBlendAttachmentState cba{};
  cba.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                       VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
  VkPipelineColorBlendStateCreateInfo cb{};
  cb.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
  cb.attachmentCount = 1;
  cb.pAttachments = &cba;

  VkDynamicState dyn[] = {VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR};
  VkPipelineDynamicStateCreateInfo dynState{};
  dynState.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
  dynState.dynamicStateCount = 2;
  dynState.pDynamicStates = dyn;

  VkGraphicsPipelineCreateInfo ci{};
  ci.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
  ci.stageCount = 2;
  ci.pStages = stages;
  ci.pVertexInputState = &vin;
  ci.pInputAssemblyState = &ia;
  ci.pViewportState = &vp;
  ci.pRasterizationState = &rs;
  ci.pMultisampleState = &ms;
  ci.pDepthStencilState = &ds;
  ci.pColorBlendState = &cb;
  ci.pDynamicState = &dynState;
  ci.layout = lineLayout_;
  ci.renderPass = offscreenPass_;
  ci.subpass = 0;
  VkResult r = vkCreateGraphicsPipelines(device_, VK_NULL_HANDLE, 1, &ci, nullptr,
                                         &linePipeline_);

  // Second variant with depth testing disabled, for the skeleton X-ray overlay.
  VkPipelineDepthStencilStateCreateInfo dsNo = ds;
  dsNo.depthTestEnable = VK_FALSE;
  dsNo.depthWriteEnable = VK_FALSE;
  ci.pDepthStencilState = &dsNo;
  VkResult r2 = vkCreateGraphicsPipelines(device_, VK_NULL_HANDLE, 1, &ci, nullptr,
                                          &linePipelineNoDepth_);

  vkDestroyShaderModule(device_, vs, nullptr);
  vkDestroyShaderModule(device_, fs, nullptr);
  if (r != VK_SUCCESS || r2 != VK_SUCCESS) {
    if (err) *err = "vkCreateGraphicsPipelines(line) failed";
    return false;
  }
  return true;
}

bool VulkanRenderer::createCommands(std::string* err) {
  VkCommandPoolCreateInfo pci{};
  pci.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
  pci.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
  pci.queueFamilyIndex = queueFamily_;
  VK_CHECK(vkCreateCommandPool(device_, &pci, nullptr, &commandPool_),
           "command pool");

  VkCommandBufferAllocateInfo ai{};
  ai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
  ai.commandPool = commandPool_;
  ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
  ai.commandBufferCount = kFramesInFlight;
  VK_CHECK(vkAllocateCommandBuffers(device_, &ai, cmd_), "command buffers");
  return true;
}

bool VulkanRenderer::createSync(std::string* err) {
  VkSemaphoreCreateInfo si{};
  si.sType = VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO;
  VkFenceCreateInfo fi{};
  fi.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
  fi.flags = VK_FENCE_CREATE_SIGNALED_BIT;
  for (int i = 0; i < kFramesInFlight; ++i) {
    VK_CHECK(vkCreateSemaphore(device_, &si, nullptr, &imageAvailable_[i]), "sem");
    VK_CHECK(vkCreateSemaphore(device_, &si, nullptr, &renderFinished_[i]), "sem");
    VK_CHECK(vkCreateFence(device_, &fi, nullptr, &inFlight_[i]), "fence");
  }
  return true;
}

bool VulkanRenderer::createSampler(std::string* err) {
  VkSamplerCreateInfo ci{};
  ci.sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
  ci.magFilter = VK_FILTER_LINEAR;
  ci.minFilter = VK_FILTER_LINEAR;
  // REPEAT suits tiled UV textures; the offscreen-image display samples exactly
  // [0,1] so its wrap mode is irrelevant.
  ci.addressModeU = VK_SAMPLER_ADDRESS_MODE_REPEAT;
  ci.addressModeV = VK_SAMPLER_ADDRESS_MODE_REPEAT;
  ci.addressModeW = VK_SAMPLER_ADDRESS_MODE_REPEAT;
  ci.maxLod = 1.0f;
  VK_CHECK(vkCreateSampler(device_, &ci, nullptr, &sampler_), "sampler");
  return true;
}

bool VulkanRenderer::createDescriptorInfra(std::string* err) {
  VkDescriptorSetLayoutBinding b{};
  b.binding = 0;
  b.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
  b.descriptorCount = 1;
  b.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;
  VkDescriptorSetLayoutCreateInfo lci{};
  lci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
  lci.bindingCount = 1;
  lci.pBindings = &b;
  VK_CHECK(vkCreateDescriptorSetLayout(device_, &lci, nullptr, &texSetLayout_),
           "tex descriptor set layout");

  // One combined-image-sampler set per texture (cap = pool size); reset+realloc
  // on each uploadScene.
  const uint32_t kMaxTexSets = 1024;
  VkDescriptorPoolSize ps{};
  ps.type = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
  ps.descriptorCount = kMaxTexSets;
  VkDescriptorPoolCreateInfo pci{};
  pci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
  pci.maxSets = kMaxTexSets;
  pci.poolSizeCount = 1;
  pci.pPoolSizes = &ps;
  VK_CHECK(vkCreateDescriptorPool(device_, &pci, nullptr, &texPool_),
           "tex descriptor pool");
  return true;
}

VkCommandBuffer VulkanRenderer::beginOneShot() {
  VkCommandBufferAllocateInfo ai{};
  ai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
  ai.commandPool = commandPool_;
  ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
  ai.commandBufferCount = 1;
  VkCommandBuffer cb = VK_NULL_HANDLE;
  vkAllocateCommandBuffers(device_, &ai, &cb);
  VkCommandBufferBeginInfo bi{};
  bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
  bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
  vkBeginCommandBuffer(cb, &bi);
  return cb;
}

void VulkanRenderer::endOneShot(VkCommandBuffer cb) {
  vkEndCommandBuffer(cb);
  VkSubmitInfo si{};
  si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
  si.commandBufferCount = 1;
  si.pCommandBuffers = &cb;
  vkQueueSubmit(queue_, 1, &si, VK_NULL_HANDLE);
  vkQueueWaitIdle(queue_);
  vkFreeCommandBuffers(device_, commandPool_, 1, &cb);
}

VkDescriptorSet VulkanRenderer::allocTexDescriptor(VkImageView view) {
  VkDescriptorSetAllocateInfo ai{};
  ai.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
  ai.descriptorPool = texPool_;
  ai.descriptorSetCount = 1;
  ai.pSetLayouts = &texSetLayout_;
  VkDescriptorSet ds = VK_NULL_HANDLE;
  if (vkAllocateDescriptorSets(device_, &ai, &ds) != VK_SUCCESS) return VK_NULL_HANDLE;
  VkDescriptorImageInfo info{};
  info.sampler = sampler_;
  info.imageView = view;
  info.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
  VkWriteDescriptorSet w{};
  w.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
  w.dstSet = ds;
  w.dstBinding = 0;
  w.descriptorCount = 1;
  w.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
  w.pImageInfo = &info;
  vkUpdateDescriptorSets(device_, 1, &w, 0, nullptr);
  return ds;
}

bool VulkanRenderer::createTextureImage(const light3d::Image& img, VkImage* outImg,
                                        VkDeviceMemory* outMem, VkImageView* outView) {
  if (img.width <= 0 || img.height <= 0 || img.data.empty()) return false;
  const VkDeviceSize size = img.data.size();  // RGBA8

  VkBuffer staging = VK_NULL_HANDLE;
  VkDeviceMemory stagingMem = VK_NULL_HANDLE;
  if (!createHostBuffer(size, VK_BUFFER_USAGE_TRANSFER_SRC_BIT, img.data.data(),
                        &staging, &stagingMem)) {
    return false;
  }

  VkImageCreateInfo ici{};
  ici.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
  ici.imageType = VK_IMAGE_TYPE_2D;
  ici.format = VK_FORMAT_R8G8B8A8_UNORM;
  ici.extent = {static_cast<uint32_t>(img.width), static_cast<uint32_t>(img.height), 1};
  ici.mipLevels = 1;
  ici.arrayLayers = 1;
  ici.samples = VK_SAMPLE_COUNT_1_BIT;
  ici.tiling = VK_IMAGE_TILING_OPTIMAL;
  ici.usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
  ici.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
  if (vkCreateImage(device_, &ici, nullptr, outImg) != VK_SUCCESS) {
    vkDestroyBuffer(device_, staging, nullptr);
    vkFreeMemory(device_, stagingMem, nullptr);
    return false;
  }
  VkMemoryRequirements req;
  vkGetImageMemoryRequirements(device_, *outImg, &req);
  VkMemoryAllocateInfo mai{};
  mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  mai.allocationSize = req.size;
  mai.memoryTypeIndex = findMemoryType(req.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
  vkAllocateMemory(device_, &mai, nullptr, outMem);
  vkBindImageMemory(device_, *outImg, *outMem, 0);

  VkCommandBuffer cb = beginOneShot();
  VkImageMemoryBarrier toDst{};
  toDst.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
  toDst.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
  toDst.newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
  toDst.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
  toDst.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
  toDst.image = *outImg;
  toDst.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
  toDst.subresourceRange.levelCount = 1;
  toDst.subresourceRange.layerCount = 1;
  toDst.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
  vkCmdPipelineBarrier(cb, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
                       VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 0, nullptr, 0, nullptr, 1,
                       &toDst);
  VkBufferImageCopy region{};
  region.imageSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
  region.imageSubresource.layerCount = 1;
  region.imageExtent = {static_cast<uint32_t>(img.width), static_cast<uint32_t>(img.height), 1};
  vkCmdCopyBufferToImage(cb, staging, *outImg, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1,
                         &region);
  VkImageMemoryBarrier toRead = toDst;
  toRead.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
  toRead.newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
  toRead.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
  toRead.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
  vkCmdPipelineBarrier(cb, VK_PIPELINE_STAGE_TRANSFER_BIT,
                       VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT, 0, 0, nullptr, 0, nullptr,
                       1, &toRead);
  endOneShot(cb);

  vkDestroyBuffer(device_, staging, nullptr);
  vkFreeMemory(device_, stagingMem, nullptr);

  VkImageViewCreateInfo vci{};
  vci.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
  vci.image = *outImg;
  vci.viewType = VK_IMAGE_VIEW_TYPE_2D;
  vci.format = VK_FORMAT_R8G8B8A8_UNORM;
  vci.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
  vci.subresourceRange.levelCount = 1;
  vci.subresourceRange.layerCount = 1;
  return vkCreateImageView(device_, &vci, nullptr, outView) == VK_SUCCESS;
}

bool VulkanRenderer::createWhiteTexture(std::string* err) {
  light3d::Image w;
  w.width = 1;
  w.height = 1;
  w.channels = 4;
  w.data = {255, 255, 255, 255};
  if (!createTextureImage(w, &whiteImg_, &whiteMem_, &whiteView_)) {
    if (err) *err = "failed to create white texture";
    return false;
  }
  return true;
}

bool VulkanRenderer::init(GLFWwindow* window, std::string* err) {
  window_ = window;
  headless_ = (window == nullptr);  // windowless: no surface/swapchain
  caps_.backend_name = "Vulkan";
  caps_.usesZeroToOneDepth = true;
  caps_.flipViewportV = false;  // we Y-flip via a negative-height viewport

  // Resolve the Vulkan loader at runtime (dlopen libvulkan / vulkan-1.dll). No
  // link-time dependency on the Vulkan SDK. Fails cleanly when no ICD/loader is
  // installed, letting the app fall back to the GL backend.
  if (volkInitialize() != VK_SUCCESS) {
    if (err) *err = "Vulkan loader not found (volkInitialize failed)";
    return false;
  }

  if (!createInstance(err)) return false;
  // Load instance-level entrypoints now that we have a VkInstance.
  volkLoadInstance(instance_);
  if (!headless_ && !createSurface(err)) return false;
  if (!pickPhysicalDevice(err)) return false;
  if (!createDevice(err)) return false;
  // Re-resolve device-level entrypoints through the device for direct dispatch
  // (skips the loader trampoline).
  volkLoadDevice(device_);
  if (headless_) {
    if (!createHeadlessSwapchain(err)) return false;  // owns images + views
  } else {
    if (!createSwapchain(err)) return false;
    if (!createSwapchainViews(err)) return false;
  }
  if (!createSwapchainRenderPass(err)) return false;
  if (!createSwapchainFramebuffers(err)) return false;
  if (!createOffscreenRenderPass(err)) return false;
  if (!createCommands(err)) return false;
  if (!createSync(err)) return false;
  if (!createSampler(err)) return false;
  if (!createDescriptorInfra(err)) return false;
  if (!createPipeline(err)) return false;       // needs texSetLayout_
  if (!createLinePipeline(err)) return false;   // needs offscreenPass_
  if (!createWhiteTexture(err)) return false;   // needs commandPool_ + texPool_

  // Ray tracing (ray query) resources, when the device + shader support it.
  if (rtSupported_) {
    std::string rterr;
    if (!createRtResources(&rterr)) {
      LOGD("ray tracing: createRtResources failed: %s", rterr.c_str());
      destroyRt();
      rtSupported_ = false;  // fall back to rasterization
    }
  }
  techniqueLabel_ = rtSupported_ ? "Vulkan (raster)" : "Vulkan";
  caps_.backend_name = techniqueLabel_.c_str();
  caps_.supportsRayTracing = rtSupported_;
  return true;
}

bool VulkanRenderer::initImGui(std::string* err) {
  // Headless: no GLFW platform backend (the app drives io.DisplaySize/DeltaTime
  // itself); only the Vulkan render backend is needed.
  if (!headless_ && !ImGui_ImplGlfw_InitForVulkan(window_, true)) {
    if (err) *err = "ImGui_ImplGlfw_InitForVulkan failed";
    return false;
  }
  ImGui_ImplVulkan_InitInfo info{};
  info.ApiVersion = VK_API_VERSION_1_2;
  info.Instance = instance_;
  info.PhysicalDevice = phys_;
  info.Device = device_;
  info.QueueFamily = queueFamily_;
  info.Queue = queue_;
  info.DescriptorPool = VK_NULL_HANDLE;
  info.DescriptorPoolSize = 16;  // backend creates its own pool (fonts + AddTexture)
  info.MinImageCount = static_cast<uint32_t>(swapImages_.size());
  info.ImageCount = static_cast<uint32_t>(swapImages_.size());
  info.PipelineInfoMain.RenderPass = swapRenderPass_;
  info.UseDynamicRendering = false;
  if (!ImGui_ImplVulkan_Init(&info)) {
    if (err) *err = "ImGui_ImplVulkan_Init failed";
    return false;
  }
  imguiInited_ = true;
  return true;
}

bool VulkanRenderer::createHostBuffer(VkDeviceSize size, VkBufferUsageFlags usage,
                                      const void* data, VkBuffer* buf,
                                      VkDeviceMemory* mem, bool deviceAddress) {
  VkBufferCreateInfo bi{};
  bi.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
  bi.size = size;
  bi.usage = usage | (deviceAddress ? VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT : 0);
  bi.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
  if (vkCreateBuffer(device_, &bi, nullptr, buf) != VK_SUCCESS) return false;

  VkMemoryRequirements req;
  vkGetBufferMemoryRequirements(device_, *buf, &req);
  VkMemoryAllocateInfo ai{};
  ai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  ai.allocationSize = req.size;
  ai.memoryTypeIndex = findMemoryType(
      req.memoryTypeBits,
      VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
  VkMemoryAllocateFlagsInfo fi{};
  fi.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO;
  fi.flags = VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT;
  if (deviceAddress) ai.pNext = &fi;
  if (vkAllocateMemory(device_, &ai, nullptr, mem) != VK_SUCCESS) return false;
  vkBindBufferMemory(device_, *buf, *mem, 0);

  void* mapped = nullptr;
  vkMapMemory(device_, *mem, 0, size, 0, &mapped);
  std::memcpy(mapped, data, static_cast<size_t>(size));
  vkUnmapMemory(device_, *mem);
  return true;
}

// Device-local buffer (no initial data) with a device address — for AS storage
// and scratch buffers.
bool VulkanRenderer::createDeviceBuffer(VkDeviceSize size, VkBufferUsageFlags usage,
                                        VkBuffer* buf, VkDeviceMemory* mem) {
  VkBufferCreateInfo bi{};
  bi.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
  bi.size = size;
  bi.usage = usage | VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT;
  bi.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
  if (vkCreateBuffer(device_, &bi, nullptr, buf) != VK_SUCCESS) return false;
  VkMemoryRequirements req;
  vkGetBufferMemoryRequirements(device_, *buf, &req);
  VkMemoryAllocateFlagsInfo fi{};
  fi.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO;
  fi.flags = VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT;
  VkMemoryAllocateInfo ai{};
  ai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  ai.pNext = &fi;
  ai.allocationSize = req.size;
  ai.memoryTypeIndex = findMemoryType(req.memoryTypeBits,
                                      VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
  if (vkAllocateMemory(device_, &ai, nullptr, mem) != VK_SUCCESS) return false;
  vkBindBufferMemory(device_, *buf, *mem, 0);
  return true;
}

VkDeviceAddress VulkanRenderer::bufferDeviceAddress(VkBuffer buf) const {
  if (!pfnGetBufferDeviceAddress_ || !buf) return 0;
  VkBufferDeviceAddressInfo info{};
  info.sType = VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO;
  info.buffer = buf;
  return pfnGetBufferDeviceAddress_(device_, &info);
}

void VulkanRenderer::destroyScene() {
  for (auto& m : meshes_) {
    if (m.vbo) vkDestroyBuffer(device_, m.vbo, nullptr);
    if (m.vboMem) vkFreeMemory(device_, m.vboMem, nullptr);
    if (m.ebo) vkDestroyBuffer(device_, m.ebo, nullptr);
    if (m.eboMem) vkFreeMemory(device_, m.eboMem, nullptr);
    if (m.blas && pfnDestroyAS_) pfnDestroyAS_(device_, m.blas, nullptr);
    if (m.blasBuf) vkDestroyBuffer(device_, m.blasBuf, nullptr);
    if (m.blasMem) vkFreeMemory(device_, m.blasMem, nullptr);
  }
  meshes_.clear();
  matColor_.clear();
  matBaseTex_.clear();

  // Per-scene acceleration structure + RT scene buffers (rebuilt on next trace).
  if (tlas_) { if (pfnDestroyAS_) pfnDestroyAS_(device_, tlas_, nullptr); tlas_ = VK_NULL_HANDLE; }
  if (tlasBuf_) { vkDestroyBuffer(device_, tlasBuf_, nullptr); tlasBuf_ = VK_NULL_HANDLE; }
  if (tlasMem_) { vkFreeMemory(device_, tlasMem_, nullptr); tlasMem_ = VK_NULL_HANDLE; }
  if (instBuf_) { vkDestroyBuffer(device_, instBuf_, nullptr); instBuf_ = VK_NULL_HANDLE; }
  if (instMem_) { vkFreeMemory(device_, instMem_, nullptr); instMem_ = VK_NULL_HANDLE; }
  if (meshDescBuf_) { vkDestroyBuffer(device_, meshDescBuf_, nullptr); meshDescBuf_ = VK_NULL_HANDLE; }
  if (meshDescMem_) { vkFreeMemory(device_, meshDescMem_, nullptr); meshDescMem_ = VK_NULL_HANDLE; }
  if (rtMatBuf_) { vkDestroyBuffer(device_, rtMatBuf_, nullptr); rtMatBuf_ = VK_NULL_HANDLE; }
  if (rtMatMem_) { vkFreeMemory(device_, rtMatMem_, nullptr); rtMatMem_ = VK_NULL_HANDLE; }
  tlasDirty_ = true;

  for (auto v : texViews_) vkDestroyImageView(device_, v, nullptr);
  for (auto i : texImgs_) vkDestroyImage(device_, i, nullptr);
  for (auto m : texMems_) vkFreeMemory(device_, m, nullptr);
  texViews_.clear();
  texImgs_.clear();
  texMems_.clear();
  texDescs_.clear();
  // Free all per-texture descriptor sets (incl. whiteDesc_) in one shot.
  if (texPool_) vkResetDescriptorPool(device_, texPool_, 0);
  whiteDesc_ = VK_NULL_HANDLE;
}

void VulkanRenderer::beginScene(const std::vector<DrawMaterialCPU>& materials,
                                int textureCount) {
  if (device_) vkDeviceWaitIdle(device_);
  destroyScene();  // resets texPool_, clears texDescs_, sets whiteDesc_ = NULL

  // Default white texture descriptor + one white slot per texture (filled lazily).
  whiteDesc_ = allocTexDescriptor(whiteView_);
  texDescs_.assign(textureCount > 0 ? static_cast<size_t>(textureCount) : 0, whiteDesc_);

  matColor_.resize(materials.size() * 4);
  matBaseTex_.resize(materials.size());
  for (size_t i = 0; i < materials.size(); ++i) {
    matColor_[i * 4 + 0] = materials[i].baseColor[0];
    matColor_[i * 4 + 1] = materials[i].baseColor[1];
    matColor_[i * 4 + 2] = materials[i].baseColor[2];
    matColor_[i * 4 + 3] = materials[i].alpha;
    matBaseTex_[i] = materials[i].baseColorTex;
  }
}

void VulkanRenderer::uploadTexture(int slot, const DrawTextureCPU& t) {
  if (slot < 0 || static_cast<size_t>(slot) >= texDescs_.size()) return;
  VkImage img = VK_NULL_HANDLE;
  VkDeviceMemory mem = VK_NULL_HANDLE;
  VkImageView view = VK_NULL_HANDLE;
  if (createTextureImage(t.image, &img, &mem, &view)) {
    texImgs_.push_back(img);
    texMems_.push_back(mem);
    texViews_.push_back(view);
    texDescs_[static_cast<size_t>(slot)] = allocTexDescriptor(view);
  }
}

void VulkanRenderer::appendMesh(const DrawMeshCPU& sm) {
  if (sm.vertices.empty() || sm.indices.empty()) return;
  VkMeshGPU gm;
  gm.submeshes = sm.submeshes;
  std::memcpy(gm.world, sm.world, sizeof(gm.world));

  // When RT is supported the vertex/index buffers double as BLAS build input and
  // SSBOs read by the ray-query shader (device addresses).
  VkBufferUsageFlags vboUsage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
  VkBufferUsageFlags eboUsage = VK_BUFFER_USAGE_INDEX_BUFFER_BIT;
  if (rtSupported_) {
    const VkBufferUsageFlags rtExtra =
        VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR |
        VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
    vboUsage |= rtExtra;
    eboUsage |= rtExtra;
  }
  if (!createHostBuffer(sm.vertices.size() * sizeof(DrawVertex), vboUsage,
                        sm.vertices.data(), &gm.vbo, &gm.vboMem, rtSupported_)) {
    return;
  }
  if (!createHostBuffer(sm.indices.size() * sizeof(uint32_t), eboUsage,
                        sm.indices.data(), &gm.ebo, &gm.eboMem, rtSupported_)) {
    vkDestroyBuffer(device_, gm.vbo, nullptr);
    vkFreeMemory(device_, gm.vboMem, nullptr);
    return;
  }

  if (rtSupported_) {
    gm.vertexCount = static_cast<uint32_t>(sm.vertices.size());
    gm.indexCount = static_cast<uint32_t>(sm.indices.size());
    gm.vboAddr = bufferDeviceAddress(gm.vbo);
    gm.eboAddr = bufferDeviceAddress(gm.ebo);
    gm.matId = sm.submeshes.empty() ? -1 : sm.submeshes.front().materialId;
    NormalMatrix3(gm.world, gm.normalMat);
    tlasDirty_ = true;  // BLAS built lazily in rebuildTlas() before the next trace
  }
  meshes_.push_back(gm);
}

void VulkanRenderer::buildBlas(VkMeshGPU& m) {
  if (m.blas != VK_NULL_HANDLE || m.indexCount < 3 || !pfnCreateAS_) return;

  VkAccelerationStructureGeometryKHR geom{};
  geom.sType = VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_GEOMETRY_KHR;
  geom.geometryType = VK_GEOMETRY_TYPE_TRIANGLES_KHR;
  geom.flags = VK_GEOMETRY_OPAQUE_BIT_KHR;
  auto& tri = geom.geometry.triangles;
  tri.sType = VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_GEOMETRY_TRIANGLES_DATA_KHR;
  tri.vertexFormat = VK_FORMAT_R32G32B32_SFLOAT;
  tri.vertexData.deviceAddress = m.vboAddr;
  tri.vertexStride = sizeof(DrawVertex);
  tri.maxVertex = m.vertexCount - 1;
  tri.indexType = VK_INDEX_TYPE_UINT32;
  tri.indexData.deviceAddress = m.eboAddr;

  const uint32_t primCount = m.indexCount / 3;

  VkAccelerationStructureBuildGeometryInfoKHR bgi{};
  bgi.sType = VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_BUILD_GEOMETRY_INFO_KHR;
  bgi.type = VK_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_KHR;
  bgi.flags = VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT_KHR;
  bgi.mode = VK_BUILD_ACCELERATION_STRUCTURE_MODE_BUILD_KHR;
  bgi.geometryCount = 1;
  bgi.pGeometries = &geom;

  VkAccelerationStructureBuildSizesInfoKHR sizes{};
  sizes.sType = VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_BUILD_SIZES_INFO_KHR;
  pfnGetASBuildSizes_(device_, VK_ACCELERATION_STRUCTURE_BUILD_TYPE_DEVICE_KHR, &bgi,
                      &primCount, &sizes);

  if (!createDeviceBuffer(sizes.accelerationStructureSize,
                          VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR,
                          &m.blasBuf, &m.blasMem)) {
    return;
  }
  VkAccelerationStructureCreateInfoKHR aci{};
  aci.sType = VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_CREATE_INFO_KHR;
  aci.buffer = m.blasBuf;
  aci.size = sizes.accelerationStructureSize;
  aci.type = VK_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_KHR;
  if (pfnCreateAS_(device_, &aci, nullptr, &m.blas) != VK_SUCCESS) return;

  // Scratch (over-allocate by the alignment so we can align the start address).
  VkBuffer scratch = VK_NULL_HANDLE;
  VkDeviceMemory scratchMem = VK_NULL_HANDLE;
  if (!createDeviceBuffer(sizes.buildScratchSize + scratchAlign_,
                          VK_BUFFER_USAGE_STORAGE_BUFFER_BIT, &scratch, &scratchMem)) {
    return;
  }
  VkDeviceAddress sa = bufferDeviceAddress(scratch);
  sa = (sa + scratchAlign_ - 1) & ~(static_cast<VkDeviceAddress>(scratchAlign_) - 1);

  bgi.dstAccelerationStructure = m.blas;
  bgi.scratchData.deviceAddress = sa;
  VkAccelerationStructureBuildRangeInfoKHR range{};
  range.primitiveCount = primCount;
  const VkAccelerationStructureBuildRangeInfoKHR* pRange = &range;

  VkCommandBuffer cb = beginOneShot();
  pfnCmdBuildAS_(cb, 1, &bgi, &pRange);
  endOneShot(cb);

  vkDestroyBuffer(device_, scratch, nullptr);
  vkFreeMemory(device_, scratchMem, nullptr);

  VkAccelerationStructureDeviceAddressInfoKHR dai{};
  dai.sType = VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_DEVICE_ADDRESS_INFO_KHR;
  dai.accelerationStructure = m.blas;
  m.blasAddr = pfnGetASDeviceAddress_(device_, &dai);
}

void VulkanRenderer::rebuildTlas() {
  if (!rtSupported_ || meshes_.empty() || !rtSet_) return;
  vkDeviceWaitIdle(device_);

  // Drop the previous per-scene TLAS + scene buffers.
  if (tlas_) { pfnDestroyAS_(device_, tlas_, nullptr); tlas_ = VK_NULL_HANDLE; }
  if (tlasBuf_) { vkDestroyBuffer(device_, tlasBuf_, nullptr); tlasBuf_ = VK_NULL_HANDLE; }
  if (tlasMem_) { vkFreeMemory(device_, tlasMem_, nullptr); tlasMem_ = VK_NULL_HANDLE; }
  if (instBuf_) { vkDestroyBuffer(device_, instBuf_, nullptr); instBuf_ = VK_NULL_HANDLE; }
  if (instMem_) { vkFreeMemory(device_, instMem_, nullptr); instMem_ = VK_NULL_HANDLE; }
  if (meshDescBuf_) { vkDestroyBuffer(device_, meshDescBuf_, nullptr); meshDescBuf_ = VK_NULL_HANDLE; }
  if (meshDescMem_) { vkFreeMemory(device_, meshDescMem_, nullptr); meshDescMem_ = VK_NULL_HANDLE; }
  if (rtMatBuf_) { vkDestroyBuffer(device_, rtMatBuf_, nullptr); rtMatBuf_ = VK_NULL_HANDLE; }
  if (rtMatMem_) { vkFreeMemory(device_, rtMatMem_, nullptr); rtMatMem_ = VK_NULL_HANDLE; }

  // Ensure every mesh has a BLAS, and build the instance + descriptor arrays.
  std::vector<VkAccelerationStructureInstanceKHR> insts;
  std::vector<MeshDescGPU> descs(meshes_.size());
  for (uint32_t i = 0; i < meshes_.size(); ++i) {
    VkMeshGPU& m = meshes_[i];
    buildBlas(m);
    MeshDescGPU& d = descs[i];
    d.vtxAddr = m.vboAddr;
    d.idxAddr = m.eboAddr;
    d.matId = (m.matId < 0) ? 0xffffffffu : static_cast<uint32_t>(m.matId);
    for (int k = 0; k < 3; ++k) {
      d.nrm0[k] = m.normalMat[0 * 3 + k];
      d.nrm1[k] = m.normalMat[1 * 3 + k];
      d.nrm2[k] = m.normalMat[2 * 3 + k];
    }
    if (m.blas == VK_NULL_HANDLE) continue;
    VkAccelerationStructureInstanceKHR inst{};
    for (int r = 0; r < 3; ++r)
      for (int c = 0; c < 4; ++c)
        inst.transform.matrix[r][c] = m.world[c * 4 + r];  // col-major -> row 3x4
    inst.instanceCustomIndex = i;
    inst.mask = 0xFF;
    inst.flags = VK_GEOMETRY_INSTANCE_TRIANGLE_FACING_CULL_DISABLE_BIT_KHR;
    inst.accelerationStructureReference = m.blasAddr;
    insts.push_back(inst);
  }
  if (insts.empty()) return;

  // Instances buffer (AS build input, device address).
  createHostBuffer(insts.size() * sizeof(VkAccelerationStructureInstanceKHR),
                   VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR,
                   insts.data(), &instBuf_, &instMem_, /*deviceAddress=*/true);

  VkAccelerationStructureGeometryKHR geom{};
  geom.sType = VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_GEOMETRY_KHR;
  geom.geometryType = VK_GEOMETRY_TYPE_INSTANCES_KHR;
  geom.flags = VK_GEOMETRY_OPAQUE_BIT_KHR;
  geom.geometry.instances.sType =
      VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_GEOMETRY_INSTANCES_DATA_KHR;
  geom.geometry.instances.data.deviceAddress = bufferDeviceAddress(instBuf_);

  const uint32_t instCount = static_cast<uint32_t>(insts.size());
  VkAccelerationStructureBuildGeometryInfoKHR bgi{};
  bgi.sType = VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_BUILD_GEOMETRY_INFO_KHR;
  bgi.type = VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR;
  bgi.flags = VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT_KHR;
  bgi.mode = VK_BUILD_ACCELERATION_STRUCTURE_MODE_BUILD_KHR;
  bgi.geometryCount = 1;
  bgi.pGeometries = &geom;

  VkAccelerationStructureBuildSizesInfoKHR sizes{};
  sizes.sType = VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_BUILD_SIZES_INFO_KHR;
  pfnGetASBuildSizes_(device_, VK_ACCELERATION_STRUCTURE_BUILD_TYPE_DEVICE_KHR, &bgi,
                      &instCount, &sizes);

  if (!createDeviceBuffer(sizes.accelerationStructureSize,
                          VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR,
                          &tlasBuf_, &tlasMem_)) {
    return;
  }
  VkAccelerationStructureCreateInfoKHR aci{};
  aci.sType = VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_CREATE_INFO_KHR;
  aci.buffer = tlasBuf_;
  aci.size = sizes.accelerationStructureSize;
  aci.type = VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR;
  if (pfnCreateAS_(device_, &aci, nullptr, &tlas_) != VK_SUCCESS) return;

  VkBuffer scratch = VK_NULL_HANDLE;
  VkDeviceMemory scratchMem = VK_NULL_HANDLE;
  if (!createDeviceBuffer(sizes.buildScratchSize + scratchAlign_,
                          VK_BUFFER_USAGE_STORAGE_BUFFER_BIT, &scratch, &scratchMem)) {
    return;
  }
  VkDeviceAddress sa = bufferDeviceAddress(scratch);
  sa = (sa + scratchAlign_ - 1) & ~(static_cast<VkDeviceAddress>(scratchAlign_) - 1);
  bgi.dstAccelerationStructure = tlas_;
  bgi.scratchData.deviceAddress = sa;

  VkAccelerationStructureBuildRangeInfoKHR range{};
  range.primitiveCount = instCount;
  const VkAccelerationStructureBuildRangeInfoKHR* pRange = &range;
  VkCommandBuffer cb = beginOneShot();
  pfnCmdBuildAS_(cb, 1, &bgi, &pRange);
  endOneShot(cb);
  vkDestroyBuffer(device_, scratch, nullptr);
  vkFreeMemory(device_, scratchMem, nullptr);

  // Per-mesh descriptor SSBO + materials SSBO.
  createHostBuffer(descs.size() * sizeof(MeshDescGPU), VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,
                   descs.data(), &meshDescBuf_, &meshDescMem_);
  std::vector<float> mats = matColor_;       // vec4 baseColor per material
  if (mats.empty()) mats.assign(4, 0.6f);    // dummy so the SSBO is non-empty
  createHostBuffer(mats.size() * sizeof(float), VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,
                   mats.data(), &rtMatBuf_, &rtMatMem_);

  // Update descriptors: TLAS(0), meshDesc(2), material(3). Image(1) set elsewhere.
  VkWriteDescriptorSetAccelerationStructureKHR asInfo{};
  asInfo.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET_ACCELERATION_STRUCTURE_KHR;
  asInfo.accelerationStructureCount = 1;
  asInfo.pAccelerationStructures = &tlas_;
  VkDescriptorBufferInfo descInfo{meshDescBuf_, 0, VK_WHOLE_SIZE};
  VkDescriptorBufferInfo matInfo{rtMatBuf_, 0, VK_WHOLE_SIZE};
  VkWriteDescriptorSet w[3]{};
  w[0].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
  w[0].pNext = &asInfo;
  w[0].dstSet = rtSet_;
  w[0].dstBinding = 0;
  w[0].descriptorCount = 1;
  w[0].descriptorType = VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR;
  w[1].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
  w[1].dstSet = rtSet_;
  w[1].dstBinding = 2;
  w[1].descriptorCount = 1;
  w[1].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
  w[1].pBufferInfo = &descInfo;
  w[2].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
  w[2].dstSet = rtSet_;
  w[2].dstBinding = 3;
  w[2].descriptorCount = 1;
  w[2].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
  w[2].pBufferInfo = &matInfo;
  vkUpdateDescriptorSets(device_, 3, w, 0, nullptr);

  tlasDirty_ = false;
}

bool VulkanRenderer::createRtResources(std::string* err) {
#if defined(TUSDVIEW_HAVE_RT_SHADER) && TUSDVIEW_HAVE_RT_SHADER
  VkDescriptorSetLayoutBinding b[4]{};
  b[0].binding = 0;
  b[0].descriptorType = VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR;
  b[0].descriptorCount = 1;
  b[0].stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  b[1].binding = 1;
  b[1].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE;
  b[1].descriptorCount = 1;
  b[1].stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  b[2].binding = 2;
  b[2].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
  b[2].descriptorCount = 1;
  b[2].stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  b[3] = b[2];
  b[3].binding = 3;
  VkDescriptorSetLayoutCreateInfo lci{};
  lci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
  lci.bindingCount = 4;
  lci.pBindings = b;
  VK_CHECK(vkCreateDescriptorSetLayout(device_, &lci, nullptr, &rtSetLayout_),
           "rt descriptor set layout");

  VkDescriptorPoolSize ps[3]{};
  ps[0] = {VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR, 1};
  ps[1] = {VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, 1};
  ps[2] = {VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 2};
  VkDescriptorPoolCreateInfo pci{};
  pci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
  pci.maxSets = 1;
  pci.poolSizeCount = 3;
  pci.pPoolSizes = ps;
  VK_CHECK(vkCreateDescriptorPool(device_, &pci, nullptr, &rtPool_), "rt descriptor pool");

  VkDescriptorSetAllocateInfo ai{};
  ai.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
  ai.descriptorPool = rtPool_;
  ai.descriptorSetCount = 1;
  ai.pSetLayouts = &rtSetLayout_;
  VK_CHECK(vkAllocateDescriptorSets(device_, &ai, &rtSet_), "rt descriptor set");

  VkPushConstantRange pcr{};
  pcr.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  pcr.size = sizeof(RtPushC);
  VkPipelineLayoutCreateInfo plci{};
  plci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
  plci.setLayoutCount = 1;
  plci.pSetLayouts = &rtSetLayout_;
  plci.pushConstantRangeCount = 1;
  plci.pPushConstantRanges = &pcr;
  VK_CHECK(vkCreatePipelineLayout(device_, &plci, nullptr, &rtPipelineLayout_),
           "rt pipeline layout");

  VkShaderModule cs = createShader(raytrace_comp_spv, sizeof(raytrace_comp_spv));
  if (!cs) {
    if (err) *err = "rt shader module";
    return false;
  }
  VkComputePipelineCreateInfo cpci{};
  cpci.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
  cpci.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  cpci.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
  cpci.stage.module = cs;
  cpci.stage.pName = "main";
  cpci.layout = rtPipelineLayout_;
  VkResult r = vkCreateComputePipelines(device_, VK_NULL_HANDLE, 1, &cpci, nullptr,
                                        &rtPipeline_);
  vkDestroyShaderModule(device_, cs, nullptr);
  if (r != VK_SUCCESS) {
    if (err) *err = "rt compute pipeline";
    return false;
  }
  return true;
#else
  (void)err;
  return false;
#endif
}

void VulkanRenderer::createRtImage() {
  if (!rtSupported_ || vpW_ < 1 || vpH_ < 1) return;
  if (rtImageView_) { vkDestroyImageView(device_, rtImageView_, nullptr); rtImageView_ = VK_NULL_HANDLE; }
  if (rtImage_) { vkDestroyImage(device_, rtImage_, nullptr); rtImage_ = VK_NULL_HANDLE; }
  if (rtImageMem_) { vkFreeMemory(device_, rtImageMem_, nullptr); rtImageMem_ = VK_NULL_HANDLE; }

  VkImageCreateInfo ici{};
  ici.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
  ici.imageType = VK_IMAGE_TYPE_2D;
  ici.format = colorFormat_;
  ici.extent = {static_cast<uint32_t>(vpW_), static_cast<uint32_t>(vpH_), 1};
  ici.mipLevels = 1;
  ici.arrayLayers = 1;
  ici.samples = VK_SAMPLE_COUNT_1_BIT;
  ici.tiling = VK_IMAGE_TILING_OPTIMAL;
  ici.usage = VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT;
  ici.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
  if (vkCreateImage(device_, &ici, nullptr, &rtImage_) != VK_SUCCESS) return;
  VkMemoryRequirements req;
  vkGetImageMemoryRequirements(device_, rtImage_, &req);
  VkMemoryAllocateInfo mai{};
  mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  mai.allocationSize = req.size;
  mai.memoryTypeIndex = findMemoryType(req.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
  if (vkAllocateMemory(device_, &mai, nullptr, &rtImageMem_) != VK_SUCCESS) return;
  vkBindImageMemory(device_, rtImage_, rtImageMem_, 0);
  VkImageViewCreateInfo vci{};
  vci.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
  vci.image = rtImage_;
  vci.viewType = VK_IMAGE_VIEW_TYPE_2D;
  vci.format = colorFormat_;
  vci.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
  vci.subresourceRange.levelCount = 1;
  vci.subresourceRange.layerCount = 1;
  if (vkCreateImageView(device_, &vci, nullptr, &rtImageView_) != VK_SUCCESS) return;

  // Transition UNDEFINED -> GENERAL (kept GENERAL between frames).
  VkCommandBuffer cb = beginOneShot();
  VkImageMemoryBarrier toGen{};
  toGen.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
  toGen.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
  toGen.newLayout = VK_IMAGE_LAYOUT_GENERAL;
  toGen.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
  toGen.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
  toGen.image = rtImage_;
  toGen.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
  toGen.subresourceRange.levelCount = 1;
  toGen.subresourceRange.layerCount = 1;
  vkCmdPipelineBarrier(cb, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
                       VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 0, nullptr, 0, nullptr, 1,
                       &toGen);
  endOneShot(cb);

  if (rtSet_) {
    VkDescriptorImageInfo ii{};
    ii.imageView = rtImageView_;
    ii.imageLayout = VK_IMAGE_LAYOUT_GENERAL;
    VkWriteDescriptorSet w{};
    w.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
    w.dstSet = rtSet_;
    w.dstBinding = 1;
    w.descriptorCount = 1;
    w.descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE;
    w.pImageInfo = &ii;
    vkUpdateDescriptorSets(device_, 1, &w, 0, nullptr);
  }
}

void VulkanRenderer::traceRt(VkCommandBuffer cb) {
  // rtImage_ is in GENERAL. Dispatch the ray-query trace, then copy into colorImg_.
  vkCmdBindPipeline(cb, VK_PIPELINE_BIND_POINT_COMPUTE, rtPipeline_);
  vkCmdBindDescriptorSets(cb, VK_PIPELINE_BIND_POINT_COMPUTE, rtPipelineLayout_, 0, 1,
                          &rtSet_, 0, nullptr);
  RtPushC pc{};
  light3d::Mat4 PV = ToMat4(proj_) * ToMat4(view_);
  if (!Mat4Inverse(PV.m, pc.invViewProj)) {
    for (int i = 0; i < 16; ++i) pc.invViewProj[i] = (i % 5 == 0) ? 1.0f : 0.0f;
  }
  pc.camPos[0] = cameraPos_[0]; pc.camPos[1] = cameraPos_[1]; pc.camPos[2] = cameraPos_[2];
  // Same fixed light direction as mesh.frag.
  float lx = 0.5f, ly = 0.8f, lz = 0.6f;
  float ll = std::sqrt(lx * lx + ly * ly + lz * lz);
  pc.lightDir[0] = lx / ll; pc.lightDir[1] = ly / ll; pc.lightDir[2] = lz / ll;
  for (int i = 0; i < 4; ++i) pc.clearColor[i] = clear_[i];
  vkCmdPushConstants(cb, rtPipelineLayout_, VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(RtPushC),
                     &pc);
  vkCmdDispatch(cb, (static_cast<uint32_t>(vpW_) + 7) / 8,
                (static_cast<uint32_t>(vpH_) + 7) / 8, 1);

  auto imgBarrier = [&](VkImage img, VkImageLayout oldL, VkImageLayout newL,
                        VkAccessFlags srcA, VkAccessFlags dstA, VkPipelineStageFlags srcS,
                        VkPipelineStageFlags dstS) {
    VkImageMemoryBarrier b{};
    b.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
    b.oldLayout = oldL;
    b.newLayout = newL;
    b.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    b.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    b.image = img;
    b.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    b.subresourceRange.levelCount = 1;
    b.subresourceRange.layerCount = 1;
    b.srcAccessMask = srcA;
    b.dstAccessMask = dstA;
    vkCmdPipelineBarrier(cb, srcS, dstS, 0, 0, nullptr, 0, nullptr, 1, &b);
  };
  imgBarrier(rtImage_, VK_IMAGE_LAYOUT_GENERAL, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
             VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT,
             VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT);
  imgBarrier(colorImg_, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 0,
             VK_ACCESS_TRANSFER_WRITE_BIT, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
             VK_PIPELINE_STAGE_TRANSFER_BIT);
  VkImageCopy copy{};
  copy.srcSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
  copy.srcSubresource.layerCount = 1;
  copy.dstSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
  copy.dstSubresource.layerCount = 1;
  copy.extent = {static_cast<uint32_t>(vpW_), static_cast<uint32_t>(vpH_), 1};
  vkCmdCopyImage(cb, rtImage_, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, colorImg_,
                 VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &copy);
  imgBarrier(colorImg_, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
             VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, VK_ACCESS_TRANSFER_WRITE_BIT,
             VK_ACCESS_SHADER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
             VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);
  imgBarrier(rtImage_, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, VK_IMAGE_LAYOUT_GENERAL,
             VK_ACCESS_TRANSFER_READ_BIT, VK_ACCESS_SHADER_WRITE_BIT,
             VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT);
}

void VulkanRenderer::setRayTracing(bool enable) {
  bool want = enable && rtSupported_;
  if (want == rtActive_) return;
  rtActive_ = want;
  techniqueLabel_ = rtActive_ ? "Vulkan (ray query)" : "Vulkan (raster)";
  caps_.backend_name = techniqueLabel_.c_str();
  if (rtActive_) tlasDirty_ = true;  // build AS lazily before the next trace
}

void VulkanRenderer::destroyRt() {
  if (tlas_) { if (pfnDestroyAS_) pfnDestroyAS_(device_, tlas_, nullptr); tlas_ = VK_NULL_HANDLE; }
  if (tlasBuf_) { vkDestroyBuffer(device_, tlasBuf_, nullptr); tlasBuf_ = VK_NULL_HANDLE; }
  if (tlasMem_) { vkFreeMemory(device_, tlasMem_, nullptr); tlasMem_ = VK_NULL_HANDLE; }
  if (instBuf_) { vkDestroyBuffer(device_, instBuf_, nullptr); instBuf_ = VK_NULL_HANDLE; }
  if (instMem_) { vkFreeMemory(device_, instMem_, nullptr); instMem_ = VK_NULL_HANDLE; }
  if (meshDescBuf_) { vkDestroyBuffer(device_, meshDescBuf_, nullptr); meshDescBuf_ = VK_NULL_HANDLE; }
  if (meshDescMem_) { vkFreeMemory(device_, meshDescMem_, nullptr); meshDescMem_ = VK_NULL_HANDLE; }
  if (rtMatBuf_) { vkDestroyBuffer(device_, rtMatBuf_, nullptr); rtMatBuf_ = VK_NULL_HANDLE; }
  if (rtMatMem_) { vkFreeMemory(device_, rtMatMem_, nullptr); rtMatMem_ = VK_NULL_HANDLE; }
  if (rtImageView_) { vkDestroyImageView(device_, rtImageView_, nullptr); rtImageView_ = VK_NULL_HANDLE; }
  if (rtImage_) { vkDestroyImage(device_, rtImage_, nullptr); rtImage_ = VK_NULL_HANDLE; }
  if (rtImageMem_) { vkFreeMemory(device_, rtImageMem_, nullptr); rtImageMem_ = VK_NULL_HANDLE; }
  if (rtPipeline_) { vkDestroyPipeline(device_, rtPipeline_, nullptr); rtPipeline_ = VK_NULL_HANDLE; }
  if (rtPipelineLayout_) { vkDestroyPipelineLayout(device_, rtPipelineLayout_, nullptr); rtPipelineLayout_ = VK_NULL_HANDLE; }
  if (rtPool_) { vkDestroyDescriptorPool(device_, rtPool_, nullptr); rtPool_ = VK_NULL_HANDLE; rtSet_ = VK_NULL_HANDLE; }
  if (rtSetLayout_) { vkDestroyDescriptorSetLayout(device_, rtSetLayout_, nullptr); rtSetLayout_ = VK_NULL_HANDLE; }
}

void VulkanRenderer::destroyOffscreen() {
  if (offscreenTexId_ && imguiInited_) {
    ImGui_ImplVulkan_RemoveTexture(offscreenTexId_);
    offscreenTexId_ = VK_NULL_HANDLE;
  }
  if (offscreenFb_) { vkDestroyFramebuffer(device_, offscreenFb_, nullptr); offscreenFb_ = VK_NULL_HANDLE; }
  if (colorView_) { vkDestroyImageView(device_, colorView_, nullptr); colorView_ = VK_NULL_HANDLE; }
  if (colorImg_) { vkDestroyImage(device_, colorImg_, nullptr); colorImg_ = VK_NULL_HANDLE; }
  if (colorMem_) { vkFreeMemory(device_, colorMem_, nullptr); colorMem_ = VK_NULL_HANDLE; }
  if (depthView_) { vkDestroyImageView(device_, depthView_, nullptr); depthView_ = VK_NULL_HANDLE; }
  if (depthImg_) { vkDestroyImage(device_, depthImg_, nullptr); depthImg_ = VK_NULL_HANDLE; }
  if (depthMem_) { vkFreeMemory(device_, depthMem_, nullptr); depthMem_ = VK_NULL_HANDLE; }
}

void VulkanRenderer::resizeViewport(int width, int height) {
  if (width < 1) width = 1;
  if (height < 1) height = 1;
  if (offscreenFb_ && width == vpW_ && height == vpH_) return;
  if (!device_) return;
  vkDeviceWaitIdle(device_);
  destroyOffscreen();
  vpW_ = width;
  vpH_ = height;

  auto makeImage = [&](VkFormat fmt, VkImageUsageFlags usage, VkImageAspectFlags aspect,
                       VkImage* img, VkDeviceMemory* mem, VkImageView* view) -> bool {
    VkImageCreateInfo ici{};
    ici.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    ici.imageType = VK_IMAGE_TYPE_2D;
    ici.format = fmt;
    ici.extent = {static_cast<uint32_t>(vpW_), static_cast<uint32_t>(vpH_), 1};
    ici.mipLevels = 1;
    ici.arrayLayers = 1;
    ici.samples = VK_SAMPLE_COUNT_1_BIT;
    ici.tiling = VK_IMAGE_TILING_OPTIMAL;
    ici.usage = usage;
    ici.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    if (vkCreateImage(device_, &ici, nullptr, img) != VK_SUCCESS) return false;
    VkMemoryRequirements req;
    vkGetImageMemoryRequirements(device_, *img, &req);
    VkMemoryAllocateInfo ai{};
    ai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    ai.allocationSize = req.size;
    ai.memoryTypeIndex = findMemoryType(req.memoryTypeBits,
                                        VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (vkAllocateMemory(device_, &ai, nullptr, mem) != VK_SUCCESS) return false;
    vkBindImageMemory(device_, *img, *mem, 0);
    VkImageViewCreateInfo vci{};
    vci.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    vci.image = *img;
    vci.viewType = VK_IMAGE_VIEW_TYPE_2D;
    vci.format = fmt;
    vci.subresourceRange.aspectMask = aspect;
    vci.subresourceRange.levelCount = 1;
    vci.subresourceRange.layerCount = 1;
    return vkCreateImageView(device_, &vci, nullptr, view) == VK_SUCCESS;
  };

  makeImage(colorFormat_,
            VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_SAMPLED_BIT,
            VK_IMAGE_ASPECT_COLOR_BIT, &colorImg_, &colorMem_, &colorView_);
  makeImage(depthFormat_, VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT,
            VK_IMAGE_ASPECT_DEPTH_BIT, &depthImg_, &depthMem_, &depthView_);

  VkImageView atts[2] = {colorView_, depthView_};
  VkFramebufferCreateInfo fci{};
  fci.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
  fci.renderPass = offscreenPass_;
  fci.attachmentCount = 2;
  fci.pAttachments = atts;
  fci.width = static_cast<uint32_t>(vpW_);
  fci.height = static_cast<uint32_t>(vpH_);
  fci.layers = 1;
  vkCreateFramebuffer(device_, &fci, nullptr, &offscreenFb_);

  if (imguiInited_) {
    offscreenTexId_ = ImGui_ImplVulkan_AddTexture(
        sampler_, colorView_, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
  }

  // Ray-trace storage image (same size); the compute shader writes it and we copy
  // it into colorImg_ for display.
  createRtImage();
  tlasDirty_ = true;
}

void VulkanRenderer::newFrame() { ImGui_ImplVulkan_NewFrame(); }

void VulkanRenderer::renderFrame(const RenderFrameParams& params) {
  if (params.view) std::memcpy(view_, params.view, sizeof(view_));
  if (params.proj) std::memcpy(proj_, params.proj, sizeof(proj_));
  for (int i = 0; i < 3; ++i) cameraPos_[i] = params.cameraPos[i];
  for (int i = 0; i < 4; ++i) clear_[i] = params.clearColor[i];
  hasParams_ = (params.view && params.proj);

  // Copy helper lines (the caller's pointer is only valid during this call).
  if (params.helperLines && params.helperLineVertexCount > 0) {
    helperCopy_.assign(params.helperLines,
                       params.helperLines + params.helperLineVertexCount);
  } else {
    helperCopy_.clear();
  }

  // Copy overlay (skeleton X-ray) lines.
  if (params.overlayLines && params.overlayLineVertexCount > 0) {
    overlayCopy_.assign(params.overlayLines,
                        params.overlayLines + params.overlayLineVertexCount);
  } else {
    overlayCopy_.clear();
  }

  // Copy the per-mesh visibility mask (same lifetime caveat; consumed in
  // present(), which records the draw commands after this call returns).
  if (params.meshVisible && params.meshVisibleCount > 0) {
    meshVisible_.assign(params.meshVisible,
                        params.meshVisible + params.meshVisibleCount);
  } else {
    meshVisible_.clear();
  }
}

ViewportTexHandle VulkanRenderer::viewportTexture() const {
  return reinterpret_cast<ViewportTexHandle>(offscreenTexId_);
}

bool VulkanRenderer::recreateSwapchain() {
  std::string* err = nullptr;
  int w = 0, h = 0;
  glfwGetFramebufferSize(window_, &w, &h);
  if (w == 0 || h == 0) return true;  // minimized; skip
  vkDeviceWaitIdle(device_);
  destroySwapchain();
  if (!createSwapchain(err)) return false;
  if (!createSwapchainViews(err)) return false;
  if (!createSwapchainFramebuffers(err)) return false;
  return true;
}

void VulkanRenderer::present() {
  if (!device_) return;

  // Build/refresh the acceleration structure before the frame (synchronous; uses
  // its own one-shot submissions) so the trace below sees a ready TLAS.
  const bool rtFrame = rtActive_ && rtSupported_ && hasParams_ && offscreenFb_ &&
                       rtImage_ && !meshes_.empty();
  if (rtFrame && tlasDirty_) rebuildTlas();

  vkWaitForFences(device_, 1, &inFlight_[frame_], VK_TRUE, UINT64_MAX);

  // Headless: no swapchain to acquire from — composite into our own image ring.
  uint32_t imageIndex = frame_;
  if (!headless_) {
    VkResult acq = vkAcquireNextImageKHR(device_, swapchain_, UINT64_MAX,
                                         imageAvailable_[frame_], VK_NULL_HANDLE,
                                         &imageIndex);
    if (acq == VK_ERROR_OUT_OF_DATE_KHR) {
      recreateSwapchain();
      return;
    }
  }
  vkResetFences(device_, 1, &inFlight_[frame_]);

  VkCommandBuffer cb = cmd_[frame_];
  vkResetCommandBuffer(cb, 0);
  VkCommandBufferBeginInfo bi{};
  bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
  vkBeginCommandBuffer(cb, &bi);

  // ---- Offscreen 3D pass: ray query (compute) or rasterization ----
  if (rtFrame && tlas_ != VK_NULL_HANDLE) {
    traceRt(cb);
  } else if (offscreenFb_ && hasParams_) {
    VkClearValue clears[2];
    clears[0].color = {{clear_[0], clear_[1], clear_[2], clear_[3]}};
    clears[1].depthStencil = {1.0f, 0};
    VkRenderPassBeginInfo rp{};
    rp.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
    rp.renderPass = offscreenPass_;
    rp.framebuffer = offscreenFb_;
    rp.renderArea.extent = {static_cast<uint32_t>(vpW_), static_cast<uint32_t>(vpH_)};
    rp.clearValueCount = 2;
    rp.pClearValues = clears;
    vkCmdBeginRenderPass(cb, &rp, VK_SUBPASS_CONTENTS_INLINE);

    // Y-flipped viewport so the offscreen image is upright (top-left origin).
    VkViewport vpRect{};
    vpRect.x = 0.0f;
    vpRect.y = static_cast<float>(vpH_);
    vpRect.width = static_cast<float>(vpW_);
    vpRect.height = -static_cast<float>(vpH_);
    vpRect.minDepth = 0.0f;
    vpRect.maxDepth = 1.0f;
    vkCmdSetViewport(cb, 0, 1, &vpRect);
    VkRect2D sc{{0, 0}, {static_cast<uint32_t>(vpW_), static_cast<uint32_t>(vpH_)}};
    vkCmdSetScissor(cb, 0, 1, &sc);
    vkCmdBindPipeline(cb, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline_);

    light3d::Mat4 P = ToMat4(proj_);
    light3d::Mat4 V = ToMat4(view_);
    for (size_t mi = 0; mi < meshes_.size(); ++mi) {
      if (mi < meshVisible_.size() && !meshVisible_[mi]) {
        continue;  // hidden by the viewer's per-mesh visibility mask
      }
      const auto& mesh = meshes_[mi];
      light3d::Mat4 W = ToMat4(mesh.world);
      light3d::Mat4 MVP = P * V * W;
      float nmat9[9];
      NormalMatrix3(mesh.world, nmat9);
      VkDeviceSize off = 0;
      vkCmdBindVertexBuffers(cb, 0, 1, &mesh.vbo, &off);
      vkCmdBindIndexBuffer(cb, mesh.ebo, 0, VK_INDEX_TYPE_UINT32);
      for (const auto& sub : mesh.submeshes) {
        // Bind the submesh's base-color texture (white if untextured).
        VkDescriptorSet ds = whiteDesc_;
        if (sub.materialId >= 0 &&
            static_cast<size_t>(sub.materialId) < matBaseTex_.size()) {
          const int bt = matBaseTex_[static_cast<size_t>(sub.materialId)];
          if (bt >= 0 && static_cast<size_t>(bt) < texDescs_.size()) {
            ds = texDescs_[static_cast<size_t>(bt)];
          }
        }
        if (ds != VK_NULL_HANDLE) {
          vkCmdBindDescriptorSets(cb, VK_PIPELINE_BIND_POINT_GRAPHICS, pipelineLayout_,
                                  0, 1, &ds, 0, nullptr);
        }
        PushC pc{};
        std::memcpy(pc.mvp, MVP.m, sizeof(pc.mvp));
        // mat3 columns padded to vec4
        for (int c = 0; c < 3; ++c) {
          pc.nmat[c * 4 + 0] = nmat9[c * 3 + 0];
          pc.nmat[c * 4 + 1] = nmat9[c * 3 + 1];
          pc.nmat[c * 4 + 2] = nmat9[c * 3 + 2];
          pc.nmat[c * 4 + 3] = 0.0f;
        }
        if (sub.materialId >= 0 &&
            static_cast<size_t>(sub.materialId) * 4 + 3 < matColor_.size()) {
          const float* mc = &matColor_[static_cast<size_t>(sub.materialId) * 4];
          pc.baseColor[0] = mc[0]; pc.baseColor[1] = mc[1];
          pc.baseColor[2] = mc[2]; pc.baseColor[3] = mc[3];
        } else {
          pc.baseColor[0] = pc.baseColor[1] = pc.baseColor[2] = 0.6f;
          pc.baseColor[3] = 1.0f;
        }
        vkCmdPushConstants(cb, pipelineLayout_,
                           VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
                           0, sizeof(PushC), &pc);
        vkCmdDrawIndexed(cb, sub.indexCount, 1, sub.indexOffset, 0, 0);
      }
    }
    // Helper lines (grid/axes/bbox) within the offscreen pass.
    if (!helperCopy_.empty() && linePipeline_) {
      const VkDeviceSize bytes = helperCopy_.size() * sizeof(HelperVertex);
      if (bytes > helperCap_[frame_]) {
        if (helperBuf_[frame_]) vkDestroyBuffer(device_, helperBuf_[frame_], nullptr);
        if (helperMem_[frame_]) vkFreeMemory(device_, helperMem_[frame_], nullptr);
        helperBuf_[frame_] = VK_NULL_HANDLE;
        helperMem_[frame_] = VK_NULL_HANDLE;
        if (createHostBuffer(bytes, VK_BUFFER_USAGE_VERTEX_BUFFER_BIT,
                             helperCopy_.data(), &helperBuf_[frame_],
                             &helperMem_[frame_])) {
          helperCap_[frame_] = bytes;
        }
      } else {
        void* p = nullptr;
        vkMapMemory(device_, helperMem_[frame_], 0, bytes, 0, &p);
        std::memcpy(p, helperCopy_.data(), static_cast<size_t>(bytes));
        vkUnmapMemory(device_, helperMem_[frame_]);
      }
      if (helperBuf_[frame_]) {
        vkCmdBindPipeline(cb, VK_PIPELINE_BIND_POINT_GRAPHICS, linePipeline_);
        const light3d::Mat4 VP = P * V;
        vkCmdPushConstants(cb, lineLayout_, VK_SHADER_STAGE_VERTEX_BIT, 0,
                           sizeof(float) * 16, VP.m);
        VkDeviceSize off = 0;
        vkCmdBindVertexBuffers(cb, 0, 1, &helperBuf_[frame_], &off);
        vkCmdDraw(cb, static_cast<uint32_t>(helperCopy_.size()), 1, 0, 0);
      }
    }
    // Overlay (skeleton X-ray) lines: depth-test-disabled pipeline, on top.
    if (!overlayCopy_.empty() && linePipelineNoDepth_) {
      const VkDeviceSize bytes = overlayCopy_.size() * sizeof(HelperVertex);
      if (bytes > overlayCap_[frame_]) {
        if (overlayBuf_[frame_]) vkDestroyBuffer(device_, overlayBuf_[frame_], nullptr);
        if (overlayMem_[frame_]) vkFreeMemory(device_, overlayMem_[frame_], nullptr);
        overlayBuf_[frame_] = VK_NULL_HANDLE;
        overlayMem_[frame_] = VK_NULL_HANDLE;
        if (createHostBuffer(bytes, VK_BUFFER_USAGE_VERTEX_BUFFER_BIT,
                             overlayCopy_.data(), &overlayBuf_[frame_],
                             &overlayMem_[frame_])) {
          overlayCap_[frame_] = bytes;
        }
      } else {
        void* p = nullptr;
        vkMapMemory(device_, overlayMem_[frame_], 0, bytes, 0, &p);
        std::memcpy(p, overlayCopy_.data(), static_cast<size_t>(bytes));
        vkUnmapMemory(device_, overlayMem_[frame_]);
      }
      if (overlayBuf_[frame_]) {
        vkCmdBindPipeline(cb, VK_PIPELINE_BIND_POINT_GRAPHICS, linePipelineNoDepth_);
        const light3d::Mat4 VP = P * V;
        vkCmdPushConstants(cb, lineLayout_, VK_SHADER_STAGE_VERTEX_BIT, 0,
                           sizeof(float) * 16, VP.m);
        VkDeviceSize off = 0;
        vkCmdBindVertexBuffers(cb, 0, 1, &overlayBuf_[frame_], &off);
        vkCmdDraw(cb, static_cast<uint32_t>(overlayCopy_.size()), 1, 0, 0);
      }
    }
    vkCmdEndRenderPass(cb);
  }

  // ---- Swapchain pass: ImGui ----
  VkClearValue clear{};
  clear.color = {{0.06f, 0.06f, 0.07f, 1.0f}};
  VkRenderPassBeginInfo rp{};
  rp.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
  rp.renderPass = swapRenderPass_;
  rp.framebuffer = swapFramebuffers_[imageIndex];
  rp.renderArea.extent = swapExtent_;
  rp.clearValueCount = 1;
  rp.pClearValues = &clear;
  vkCmdBeginRenderPass(cb, &rp, VK_SUBPASS_CONTENTS_INLINE);
  ImGui_ImplVulkan_RenderDrawData(ImGui::GetDrawData(), cb);
  vkCmdEndRenderPass(cb);

  vkEndCommandBuffer(cb);

  VkPipelineStageFlags waitStage = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  VkSubmitInfo si{};
  si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
  si.commandBufferCount = 1;
  si.pCommandBuffers = &cb;
  // Windowed: gate the composite pass on image acquisition and signal present.
  // Headless: no acquire/present, so the fence alone orders frames.
  if (!headless_) {
    si.waitSemaphoreCount = 1;
    si.pWaitSemaphores = &imageAvailable_[frame_];
    si.pWaitDstStageMask = &waitStage;
    si.signalSemaphoreCount = 1;
    si.pSignalSemaphores = &renderFinished_[frame_];
  }
  vkQueueSubmit(queue_, 1, &si, inFlight_[frame_]);

  if (headless_) {
    // The composite image is left in TRANSFER_SRC_OPTIMAL; captureWindow() reads it.
    lastSwapIndex_ = imageIndex;
  } else {
    VkPresentInfoKHR pi{};
    pi.sType = VK_STRUCTURE_TYPE_PRESENT_INFO_KHR;
    pi.waitSemaphoreCount = 1;
    pi.pWaitSemaphores = &renderFinished_[frame_];
    pi.swapchainCount = 1;
    pi.pSwapchains = &swapchain_;
    pi.pImageIndices = &imageIndex;
    VkResult pres = vkQueuePresentKHR(queue_, &pi);
    if (pres == VK_ERROR_OUT_OF_DATE_KHR || pres == VK_SUBOPTIMAL_KHR) {
      recreateSwapchain();
    }
  }
  frame_ = (frame_ + 1) % kFramesInFlight;
}

bool VulkanRenderer::captureViewport(std::vector<uint8_t>* rgba, int* w, int* h) {
  if (!device_ || !colorImg_ || vpW_ < 1 || vpH_ < 1) return false;
  vkDeviceWaitIdle(device_);
  const VkDeviceSize size = static_cast<VkDeviceSize>(vpW_) * vpH_ * 4;

  VkBuffer buf = VK_NULL_HANDLE;
  VkDeviceMemory mem = VK_NULL_HANDLE;
  VkBufferCreateInfo bi{};
  bi.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
  bi.size = size;
  bi.usage = VK_BUFFER_USAGE_TRANSFER_DST_BIT;
  bi.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
  if (vkCreateBuffer(device_, &bi, nullptr, &buf) != VK_SUCCESS) return false;
  VkMemoryRequirements req;
  vkGetBufferMemoryRequirements(device_, buf, &req);
  VkMemoryAllocateInfo ai{};
  ai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  ai.allocationSize = req.size;
  ai.memoryTypeIndex = findMemoryType(
      req.memoryTypeBits,
      VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
  vkAllocateMemory(device_, &ai, nullptr, &mem);
  vkBindBufferMemory(device_, buf, mem, 0);

  VkCommandBufferAllocateInfo cai{};
  cai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
  cai.commandPool = commandPool_;
  cai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
  cai.commandBufferCount = 1;
  VkCommandBuffer cb = VK_NULL_HANDLE;
  vkAllocateCommandBuffers(device_, &cai, &cb);
  VkCommandBufferBeginInfo cbi{};
  cbi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
  cbi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
  vkBeginCommandBuffer(cb, &cbi);

  VkImageMemoryBarrier toSrc{};
  toSrc.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
  toSrc.oldLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
  toSrc.newLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
  toSrc.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
  toSrc.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
  toSrc.image = colorImg_;
  toSrc.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
  toSrc.subresourceRange.levelCount = 1;
  toSrc.subresourceRange.layerCount = 1;
  toSrc.srcAccessMask = VK_ACCESS_SHADER_READ_BIT;
  toSrc.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
  vkCmdPipelineBarrier(cb, VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,
                       VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 0, nullptr, 0, nullptr, 1,
                       &toSrc);

  VkBufferImageCopy region{};
  region.imageSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
  region.imageSubresource.layerCount = 1;
  region.imageExtent = {static_cast<uint32_t>(vpW_), static_cast<uint32_t>(vpH_), 1};
  vkCmdCopyImageToBuffer(cb, colorImg_, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, buf, 1,
                         &region);

  VkImageMemoryBarrier back = toSrc;
  back.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
  back.newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
  back.srcAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
  back.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
  vkCmdPipelineBarrier(cb, VK_PIPELINE_STAGE_TRANSFER_BIT,
                       VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT, 0, 0, nullptr, 0, nullptr,
                       1, &back);

  vkEndCommandBuffer(cb);
  VkSubmitInfo si{};
  si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
  si.commandBufferCount = 1;
  si.pCommandBuffers = &cb;
  vkQueueSubmit(queue_, 1, &si, VK_NULL_HANDLE);
  vkQueueWaitIdle(queue_);

  void* mapped = nullptr;
  vkMapMemory(device_, mem, 0, size, 0, &mapped);
  rgba->resize(static_cast<size_t>(size));
  std::memcpy(rgba->data(), mapped, static_cast<size_t>(size));
  vkUnmapMemory(device_, mem);

  vkFreeCommandBuffers(device_, commandPool_, 1, &cb);
  vkDestroyBuffer(device_, buf, nullptr);
  vkFreeMemory(device_, mem, nullptr);

  *w = vpW_;
  *h = vpH_;
  return true;  // colorFormat_ is R8G8B8A8_UNORM, top-down (Y-flipped viewport)
}

bool VulkanRenderer::captureWindow(std::vector<uint8_t>* rgba, int* w, int* h) {
  // Headless only: read back the last composite image (UI + viewport). The swap
  // render pass left it in TRANSFER_SRC_OPTIMAL, so we can copy it straight out.
  if (!headless_ || !device_ || swapImages_.empty() ||
      lastSwapIndex_ >= swapImages_.size()) {
    return false;
  }
  vkDeviceWaitIdle(device_);
  const uint32_t cw = swapExtent_.width, ch = swapExtent_.height;
  const VkDeviceSize size = static_cast<VkDeviceSize>(cw) * ch * 4;

  VkBuffer buf = VK_NULL_HANDLE;
  VkDeviceMemory mem = VK_NULL_HANDLE;
  VkBufferCreateInfo bi{};
  bi.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
  bi.size = size;
  bi.usage = VK_BUFFER_USAGE_TRANSFER_DST_BIT;
  bi.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
  if (vkCreateBuffer(device_, &bi, nullptr, &buf) != VK_SUCCESS) return false;
  VkMemoryRequirements req;
  vkGetBufferMemoryRequirements(device_, buf, &req);
  VkMemoryAllocateInfo ai{};
  ai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  ai.allocationSize = req.size;
  ai.memoryTypeIndex = findMemoryType(
      req.memoryTypeBits,
      VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
  vkAllocateMemory(device_, &ai, nullptr, &mem);
  vkBindBufferMemory(device_, buf, mem, 0);

  VkCommandBuffer cb = beginOneShot();
  VkBufferImageCopy region{};
  region.imageSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
  region.imageSubresource.layerCount = 1;
  region.imageExtent = {cw, ch, 1};
  vkCmdCopyImageToBuffer(cb, swapImages_[lastSwapIndex_],
                         VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, buf, 1, &region);
  endOneShot(cb);

  void* mapped = nullptr;
  vkMapMemory(device_, mem, 0, size, 0, &mapped);
  rgba->resize(static_cast<size_t>(size));
  std::memcpy(rgba->data(), mapped, static_cast<size_t>(size));
  vkUnmapMemory(device_, mem);
  vkDestroyBuffer(device_, buf, nullptr);
  vkFreeMemory(device_, mem, nullptr);

  *w = static_cast<int>(cw);
  *h = static_cast<int>(ch);
  return true;  // R8G8B8A8_UNORM, top-down
}

void VulkanRenderer::destroySwapchain() {
  for (auto fb : swapFramebuffers_) vkDestroyFramebuffer(device_, fb, nullptr);
  swapFramebuffers_.clear();
  for (auto v : swapViews_) vkDestroyImageView(device_, v, nullptr);
  swapViews_.clear();
  if (headless_) {
    // We own the composite images + their memory in the headless path.
    for (auto img : swapImages_) {
      if (img) vkDestroyImage(device_, img, nullptr);
    }
    for (auto m : swapMem_) {
      if (m) vkFreeMemory(device_, m, nullptr);
    }
    swapImages_.clear();
    swapMem_.clear();
  } else if (swapchain_) {
    vkDestroySwapchainKHR(device_, swapchain_, nullptr);
    swapchain_ = VK_NULL_HANDLE;
  }
}

void VulkanRenderer::shutdown() {
  if (device_) vkDeviceWaitIdle(device_);
  destroyScene();
  destroyRt();
  destroyOffscreen();
  if (imguiInited_) {
    ImGui_ImplVulkan_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    imguiInited_ = false;
  }
  if (whiteView_) { vkDestroyImageView(device_, whiteView_, nullptr); whiteView_ = VK_NULL_HANDLE; }
  if (whiteImg_) { vkDestroyImage(device_, whiteImg_, nullptr); whiteImg_ = VK_NULL_HANDLE; }
  if (whiteMem_) { vkFreeMemory(device_, whiteMem_, nullptr); whiteMem_ = VK_NULL_HANDLE; }
  if (texPool_) { vkDestroyDescriptorPool(device_, texPool_, nullptr); texPool_ = VK_NULL_HANDLE; }
  if (texSetLayout_) { vkDestroyDescriptorSetLayout(device_, texSetLayout_, nullptr); texSetLayout_ = VK_NULL_HANDLE; }
  if (sampler_) { vkDestroySampler(device_, sampler_, nullptr); sampler_ = VK_NULL_HANDLE; }
  if (pipeline_) { vkDestroyPipeline(device_, pipeline_, nullptr); pipeline_ = VK_NULL_HANDLE; }
  if (pipelineLayout_) { vkDestroyPipelineLayout(device_, pipelineLayout_, nullptr); pipelineLayout_ = VK_NULL_HANDLE; }
  if (linePipeline_) { vkDestroyPipeline(device_, linePipeline_, nullptr); linePipeline_ = VK_NULL_HANDLE; }
  if (linePipelineNoDepth_) { vkDestroyPipeline(device_, linePipelineNoDepth_, nullptr); linePipelineNoDepth_ = VK_NULL_HANDLE; }
  if (lineLayout_) { vkDestroyPipelineLayout(device_, lineLayout_, nullptr); lineLayout_ = VK_NULL_HANDLE; }
  for (int i = 0; i < kFramesInFlight; ++i) {
    if (helperBuf_[i]) vkDestroyBuffer(device_, helperBuf_[i], nullptr);
    if (helperMem_[i]) vkFreeMemory(device_, helperMem_[i], nullptr);
    helperBuf_[i] = VK_NULL_HANDLE;
    helperMem_[i] = VK_NULL_HANDLE;
    if (overlayBuf_[i]) vkDestroyBuffer(device_, overlayBuf_[i], nullptr);
    if (overlayMem_[i]) vkFreeMemory(device_, overlayMem_[i], nullptr);
    overlayBuf_[i] = VK_NULL_HANDLE;
    overlayMem_[i] = VK_NULL_HANDLE;
  }
  if (offscreenPass_) { vkDestroyRenderPass(device_, offscreenPass_, nullptr); offscreenPass_ = VK_NULL_HANDLE; }
  for (int i = 0; i < kFramesInFlight; ++i) {
    if (imageAvailable_[i]) vkDestroySemaphore(device_, imageAvailable_[i], nullptr);
    if (renderFinished_[i]) vkDestroySemaphore(device_, renderFinished_[i], nullptr);
    if (inFlight_[i]) vkDestroyFence(device_, inFlight_[i], nullptr);
    imageAvailable_[i] = renderFinished_[i] = VK_NULL_HANDLE;
    inFlight_[i] = VK_NULL_HANDLE;
  }
  if (commandPool_) { vkDestroyCommandPool(device_, commandPool_, nullptr); commandPool_ = VK_NULL_HANDLE; }
  destroySwapchain();
  if (swapRenderPass_) { vkDestroyRenderPass(device_, swapRenderPass_, nullptr); swapRenderPass_ = VK_NULL_HANDLE; }
  if (device_) { vkDestroyDevice(device_, nullptr); device_ = VK_NULL_HANDLE; }
  if (surface_) { vkDestroySurfaceKHR(instance_, surface_, nullptr); surface_ = VK_NULL_HANDLE; }
  if (instance_) { vkDestroyInstance(instance_, nullptr); instance_ = VK_NULL_HANDLE; }
}

std::unique_ptr<Renderer> CreateVulkanRenderer() {
  return std::unique_ptr<Renderer>(new VulkanRenderer());
}

}  // namespace tusdview
