// SPDX-License-Identifier: Apache-2.0
#include "vk/vk_renderer.hh"

#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>

#include <cmath>
#include <cstdio>
#include <cstring>

#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_vulkan.h"
#include "light3d/math.h"

// Generated by glslangValidator (see vk/vulkan.cmake): unsigned int *_spv[].
#include "mesh_frag.spv.h"
#include "mesh_vert.spv.h"

namespace tusdview {

namespace {

#define VK_CHECK(expr, msg)                                  \
  do {                                                       \
    VkResult _r = (expr);                                    \
    if (_r != VK_SUCCESS) {                                  \
      if (err) *err = std::string(msg) + " (VkResult " +     \
                      std::to_string(static_cast<int>(_r)) + ")"; \
      return false;                                          \
    }                                                        \
  } while (0)

light3d::Mat4 ToMat4(const float* m) {
  light3d::Mat4 r;
  std::memcpy(r.m, m, sizeof(r.m));
  return r;
}

void NormalMatrix3(const float m[16], float out9[9]) {
  const float a00 = m[0], a01 = m[4], a02 = m[8];
  const float a10 = m[1], a11 = m[5], a12 = m[9];
  const float a20 = m[2], a21 = m[6], a22 = m[10];
  const float det = a00 * (a11 * a22 - a12 * a21) -
                    a01 * (a10 * a22 - a12 * a20) +
                    a02 * (a10 * a21 - a11 * a20);
  if (std::fabs(det) < 1e-12f) {
    out9[0] = 1; out9[1] = 0; out9[2] = 0;
    out9[3] = 0; out9[4] = 1; out9[5] = 0;
    out9[6] = 0; out9[7] = 0; out9[8] = 1;
    return;
  }
  const float inv = 1.0f / det;
  out9[0] = (a11 * a22 - a12 * a21) * inv;
  out9[1] = -(a01 * a22 - a02 * a21) * inv;
  out9[2] = (a01 * a12 - a02 * a11) * inv;
  out9[3] = -(a10 * a22 - a12 * a20) * inv;
  out9[4] = (a00 * a22 - a02 * a20) * inv;
  out9[5] = -(a00 * a12 - a02 * a10) * inv;
  out9[6] = (a10 * a21 - a11 * a20) * inv;
  out9[7] = -(a00 * a21 - a01 * a20) * inv;
  out9[8] = (a00 * a11 - a01 * a10) * inv;
}

struct PushC {
  float mvp[16];
  float nmat[12];  // 3 columns padded to vec4
  float baseColor[4];
};

}  // namespace

VulkanRenderer::~VulkanRenderer() { shutdown(); }

uint32_t VulkanRenderer::findMemoryType(uint32_t typeBits,
                                        VkMemoryPropertyFlags props) const {
  VkPhysicalDeviceMemoryProperties mp;
  vkGetPhysicalDeviceMemoryProperties(phys_, &mp);
  for (uint32_t i = 0; i < mp.memoryTypeCount; ++i) {
    if ((typeBits & (1u << i)) &&
        (mp.memoryTypes[i].propertyFlags & props) == props) {
      return i;
    }
  }
  return 0;
}

bool VulkanRenderer::createInstance(std::string* err) {
  VkApplicationInfo app{};
  app.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
  app.pApplicationName = "tusdview";
  app.apiVersion = VK_API_VERSION_1_1;

  uint32_t extCount = 0;
  const char** glfwExt = glfwGetRequiredInstanceExtensions(&extCount);
  std::vector<const char*> exts(glfwExt, glfwExt + extCount);

  VkInstanceCreateInfo ci{};
  ci.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
  ci.pApplicationInfo = &app;
  ci.enabledExtensionCount = static_cast<uint32_t>(exts.size());
  ci.ppEnabledExtensionNames = exts.data();
  VK_CHECK(vkCreateInstance(&ci, nullptr, &instance_), "vkCreateInstance");
  return true;
}

bool VulkanRenderer::createSurface(std::string* err) {
  VK_CHECK(glfwCreateWindowSurface(instance_, window_, nullptr, &surface_),
           "glfwCreateWindowSurface");
  return true;
}

bool VulkanRenderer::pickPhysicalDevice(std::string* err) {
  uint32_t n = 0;
  vkEnumeratePhysicalDevices(instance_, &n, nullptr);
  if (n == 0) {
    if (err) *err = "no Vulkan physical devices";
    return false;
  }
  std::vector<VkPhysicalDevice> devs(n);
  vkEnumeratePhysicalDevices(instance_, &n, devs.data());

  VkPhysicalDevice fallback = VK_NULL_HANDLE;
  uint32_t fallbackFam = 0;
  for (VkPhysicalDevice d : devs) {
    uint32_t qn = 0;
    vkGetPhysicalDeviceQueueFamilyProperties(d, &qn, nullptr);
    std::vector<VkQueueFamilyProperties> qfp(qn);
    vkGetPhysicalDeviceQueueFamilyProperties(d, &qn, qfp.data());
    for (uint32_t i = 0; i < qn; ++i) {
      VkBool32 present = VK_FALSE;
      vkGetPhysicalDeviceSurfaceSupportKHR(d, i, surface_, &present);
      if ((qfp[i].queueFlags & VK_QUEUE_GRAPHICS_BIT) && present) {
        VkPhysicalDeviceProperties props;
        vkGetPhysicalDeviceProperties(d, &props);
        if (props.deviceType == VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU) {
          phys_ = d;
          queueFamily_ = i;
          return true;
        }
        if (fallback == VK_NULL_HANDLE) {
          fallback = d;
          fallbackFam = i;
        }
      }
    }
  }
  if (fallback != VK_NULL_HANDLE) {
    phys_ = fallback;
    queueFamily_ = fallbackFam;
    return true;
  }
  if (err) *err = "no graphics+present queue family";
  return false;
}

bool VulkanRenderer::createDevice(std::string* err) {
  float prio = 1.0f;
  VkDeviceQueueCreateInfo qci{};
  qci.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
  qci.queueFamilyIndex = queueFamily_;
  qci.queueCount = 1;
  qci.pQueuePriorities = &prio;

  const char* devExts[] = {VK_KHR_SWAPCHAIN_EXTENSION_NAME};
  VkDeviceCreateInfo ci{};
  ci.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
  ci.queueCreateInfoCount = 1;
  ci.pQueueCreateInfos = &qci;
  ci.enabledExtensionCount = 1;
  ci.ppEnabledExtensionNames = devExts;
  VK_CHECK(vkCreateDevice(phys_, &ci, nullptr, &device_), "vkCreateDevice");
  vkGetDeviceQueue(device_, queueFamily_, 0, &queue_);
  return true;
}

bool VulkanRenderer::createSwapchain(std::string* err) {
  VkSurfaceCapabilitiesKHR caps;
  vkGetPhysicalDeviceSurfaceCapabilitiesKHR(phys_, surface_, &caps);

  uint32_t fn = 0;
  vkGetPhysicalDeviceSurfaceFormatsKHR(phys_, surface_, &fn, nullptr);
  std::vector<VkSurfaceFormatKHR> formats(fn);
  vkGetPhysicalDeviceSurfaceFormatsKHR(phys_, surface_, &fn, formats.data());
  VkSurfaceFormatKHR fmt = formats[0];
  for (const auto& f : formats) {
    if (f.format == VK_FORMAT_B8G8R8A8_UNORM &&
        f.colorSpace == VK_COLOR_SPACE_SRGB_NONLINEAR_KHR) {
      fmt = f;
      break;
    }
  }
  swapFormat_ = fmt.format;

  VkExtent2D extent = caps.currentExtent;
  if (extent.width == 0xFFFFFFFFu) {
    int w = 0, h = 0;
    glfwGetFramebufferSize(window_, &w, &h);
    extent.width = static_cast<uint32_t>(w);
    extent.height = static_cast<uint32_t>(h);
  }
  if (extent.width == 0) extent.width = 1;
  if (extent.height == 0) extent.height = 1;
  swapExtent_ = extent;

  uint32_t imageCount = caps.minImageCount + 1;
  if (caps.maxImageCount > 0 && imageCount > caps.maxImageCount) {
    imageCount = caps.maxImageCount;
  }

  VkSwapchainCreateInfoKHR ci{};
  ci.sType = VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR;
  ci.surface = surface_;
  ci.minImageCount = imageCount;
  ci.imageFormat = fmt.format;
  ci.imageColorSpace = fmt.colorSpace;
  ci.imageExtent = extent;
  ci.imageArrayLayers = 1;
  ci.imageUsage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
  ci.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
  ci.preTransform = caps.currentTransform;
  ci.compositeAlpha = VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;
  ci.presentMode = VK_PRESENT_MODE_FIFO_KHR;
  ci.clipped = VK_TRUE;
  VK_CHECK(vkCreateSwapchainKHR(device_, &ci, nullptr, &swapchain_),
           "vkCreateSwapchainKHR");

  uint32_t sc = 0;
  vkGetSwapchainImagesKHR(device_, swapchain_, &sc, nullptr);
  swapImages_.resize(sc);
  vkGetSwapchainImagesKHR(device_, swapchain_, &sc, swapImages_.data());
  return true;
}

bool VulkanRenderer::createSwapchainViews(std::string* err) {
  swapViews_.resize(swapImages_.size());
  for (size_t i = 0; i < swapImages_.size(); ++i) {
    VkImageViewCreateInfo ci{};
    ci.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    ci.image = swapImages_[i];
    ci.viewType = VK_IMAGE_VIEW_TYPE_2D;
    ci.format = swapFormat_;
    ci.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    ci.subresourceRange.levelCount = 1;
    ci.subresourceRange.layerCount = 1;
    VK_CHECK(vkCreateImageView(device_, &ci, nullptr, &swapViews_[i]),
             "swapchain image view");
  }
  return true;
}

bool VulkanRenderer::createSwapchainRenderPass(std::string* err) {
  VkAttachmentDescription color{};
  color.format = swapFormat_;
  color.samples = VK_SAMPLE_COUNT_1_BIT;
  color.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
  color.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
  color.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
  color.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
  color.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
  color.finalLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;

  VkAttachmentReference ref{};
  ref.attachment = 0;
  ref.layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;

  VkSubpassDescription sub{};
  sub.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
  sub.colorAttachmentCount = 1;
  sub.pColorAttachments = &ref;

  VkSubpassDependency dep{};
  dep.srcSubpass = VK_SUBPASS_EXTERNAL;
  dep.dstSubpass = 0;
  dep.srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  dep.dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  dep.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;

  VkRenderPassCreateInfo ci{};
  ci.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
  ci.attachmentCount = 1;
  ci.pAttachments = &color;
  ci.subpassCount = 1;
  ci.pSubpasses = &sub;
  ci.dependencyCount = 1;
  ci.pDependencies = &dep;
  VK_CHECK(vkCreateRenderPass(device_, &ci, nullptr, &swapRenderPass_),
           "swapchain render pass");
  return true;
}

bool VulkanRenderer::createSwapchainFramebuffers(std::string* err) {
  swapFramebuffers_.resize(swapViews_.size());
  for (size_t i = 0; i < swapViews_.size(); ++i) {
    VkFramebufferCreateInfo ci{};
    ci.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
    ci.renderPass = swapRenderPass_;
    ci.attachmentCount = 1;
    ci.pAttachments = &swapViews_[i];
    ci.width = swapExtent_.width;
    ci.height = swapExtent_.height;
    ci.layers = 1;
    VK_CHECK(vkCreateFramebuffer(device_, &ci, nullptr, &swapFramebuffers_[i]),
             "swapchain framebuffer");
  }
  return true;
}

bool VulkanRenderer::createOffscreenRenderPass(std::string* err) {
  VkAttachmentDescription atts[2]{};
  atts[0].format = colorFormat_;
  atts[0].samples = VK_SAMPLE_COUNT_1_BIT;
  atts[0].loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
  atts[0].storeOp = VK_ATTACHMENT_STORE_OP_STORE;
  atts[0].stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
  atts[0].stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
  atts[0].initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
  atts[0].finalLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
  atts[1].format = depthFormat_;
  atts[1].samples = VK_SAMPLE_COUNT_1_BIT;
  atts[1].loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
  atts[1].storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
  atts[1].stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
  atts[1].stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
  atts[1].initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
  atts[1].finalLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;

  VkAttachmentReference colorRef{0, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};
  VkAttachmentReference depthRef{1, VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL};

  VkSubpassDescription sub{};
  sub.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
  sub.colorAttachmentCount = 1;
  sub.pColorAttachments = &colorRef;
  sub.pDepthStencilAttachment = &depthRef;

  // Sync the offscreen color write with later fragment sampling by ImGui.
  VkSubpassDependency deps[2]{};
  deps[0].srcSubpass = VK_SUBPASS_EXTERNAL;
  deps[0].dstSubpass = 0;
  deps[0].srcStageMask = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
  deps[0].dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  deps[0].srcAccessMask = VK_ACCESS_SHADER_READ_BIT;
  deps[0].dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
  deps[1].srcSubpass = 0;
  deps[1].dstSubpass = VK_SUBPASS_EXTERNAL;
  deps[1].srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  deps[1].dstStageMask = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
  deps[1].srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
  deps[1].dstAccessMask = VK_ACCESS_SHADER_READ_BIT;

  VkRenderPassCreateInfo ci{};
  ci.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
  ci.attachmentCount = 2;
  ci.pAttachments = atts;
  ci.subpassCount = 1;
  ci.pSubpasses = &sub;
  ci.dependencyCount = 2;
  ci.pDependencies = deps;
  VK_CHECK(vkCreateRenderPass(device_, &ci, nullptr, &offscreenPass_),
           "offscreen render pass");
  return true;
}

VkShaderModule VulkanRenderer::createShader(const uint32_t* code, size_t bytes) {
  VkShaderModuleCreateInfo ci{};
  ci.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
  ci.codeSize = bytes;
  ci.pCode = code;
  VkShaderModule m = VK_NULL_HANDLE;
  vkCreateShaderModule(device_, &ci, nullptr, &m);
  return m;
}

bool VulkanRenderer::createPipeline(std::string* err) {
  VkPushConstantRange pcr{};
  pcr.stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT;
  pcr.offset = 0;
  pcr.size = sizeof(PushC);

  VkPipelineLayoutCreateInfo plci{};
  plci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
  plci.setLayoutCount = 1;
  plci.pSetLayouts = &texSetLayout_;
  plci.pushConstantRangeCount = 1;
  plci.pPushConstantRanges = &pcr;
  VK_CHECK(vkCreatePipelineLayout(device_, &plci, nullptr, &pipelineLayout_),
           "pipeline layout");

  VkShaderModule vs = createShader(mesh_vert_spv, sizeof(mesh_vert_spv));
  VkShaderModule fs = createShader(mesh_frag_spv, sizeof(mesh_frag_spv));
  if (!vs || !fs) {
    if (err) *err = "shader module creation failed";
    return false;
  }

  VkPipelineShaderStageCreateInfo stages[2]{};
  stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
  stages[0].module = vs;
  stages[0].pName = "main";
  stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
  stages[1].module = fs;
  stages[1].pName = "main";

  VkVertexInputBindingDescription bind{};
  bind.binding = 0;
  bind.stride = sizeof(DrawVertex);
  bind.inputRate = VK_VERTEX_INPUT_RATE_VERTEX;
  VkVertexInputAttributeDescription attrs[3]{};
  attrs[0] = {0, 0, VK_FORMAT_R32G32B32_SFLOAT, 0};
  attrs[1] = {1, 0, VK_FORMAT_R32G32B32_SFLOAT, 3 * sizeof(float)};
  attrs[2] = {2, 0, VK_FORMAT_R32G32_SFLOAT, 6 * sizeof(float)};

  VkPipelineVertexInputStateCreateInfo vin{};
  vin.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
  vin.vertexBindingDescriptionCount = 1;
  vin.pVertexBindingDescriptions = &bind;
  vin.vertexAttributeDescriptionCount = 3;
  vin.pVertexAttributeDescriptions = attrs;

  VkPipelineInputAssemblyStateCreateInfo ia{};
  ia.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
  ia.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

  VkPipelineViewportStateCreateInfo vp{};
  vp.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
  vp.viewportCount = 1;
  vp.scissorCount = 1;

  VkPipelineRasterizationStateCreateInfo rs{};
  rs.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
  rs.polygonMode = VK_POLYGON_MODE_FILL;
  rs.cullMode = VK_CULL_MODE_NONE;
  rs.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
  rs.lineWidth = 1.0f;

  VkPipelineMultisampleStateCreateInfo ms{};
  ms.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
  ms.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

  VkPipelineDepthStencilStateCreateInfo ds{};
  ds.sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
  ds.depthTestEnable = VK_TRUE;
  ds.depthWriteEnable = VK_TRUE;
  ds.depthCompareOp = VK_COMPARE_OP_LESS;

  VkPipelineColorBlendAttachmentState cba{};
  cba.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                       VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
  VkPipelineColorBlendStateCreateInfo cb{};
  cb.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
  cb.attachmentCount = 1;
  cb.pAttachments = &cba;

  VkDynamicState dyn[] = {VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR};
  VkPipelineDynamicStateCreateInfo dynState{};
  dynState.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
  dynState.dynamicStateCount = 2;
  dynState.pDynamicStates = dyn;

  VkGraphicsPipelineCreateInfo ci{};
  ci.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
  ci.stageCount = 2;
  ci.pStages = stages;
  ci.pVertexInputState = &vin;
  ci.pInputAssemblyState = &ia;
  ci.pViewportState = &vp;
  ci.pRasterizationState = &rs;
  ci.pMultisampleState = &ms;
  ci.pDepthStencilState = &ds;
  ci.pColorBlendState = &cb;
  ci.pDynamicState = &dynState;
  ci.layout = pipelineLayout_;
  ci.renderPass = offscreenPass_;
  ci.subpass = 0;
  VkResult r = vkCreateGraphicsPipelines(device_, VK_NULL_HANDLE, 1, &ci, nullptr,
                                         &pipeline_);
  vkDestroyShaderModule(device_, vs, nullptr);
  vkDestroyShaderModule(device_, fs, nullptr);
  if (r != VK_SUCCESS) {
    if (err) *err = "vkCreateGraphicsPipelines failed";
    return false;
  }
  return true;
}

bool VulkanRenderer::createCommands(std::string* err) {
  VkCommandPoolCreateInfo pci{};
  pci.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
  pci.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
  pci.queueFamilyIndex = queueFamily_;
  VK_CHECK(vkCreateCommandPool(device_, &pci, nullptr, &commandPool_),
           "command pool");

  VkCommandBufferAllocateInfo ai{};
  ai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
  ai.commandPool = commandPool_;
  ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
  ai.commandBufferCount = kFramesInFlight;
  VK_CHECK(vkAllocateCommandBuffers(device_, &ai, cmd_), "command buffers");
  return true;
}

bool VulkanRenderer::createSync(std::string* err) {
  VkSemaphoreCreateInfo si{};
  si.sType = VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO;
  VkFenceCreateInfo fi{};
  fi.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
  fi.flags = VK_FENCE_CREATE_SIGNALED_BIT;
  for (int i = 0; i < kFramesInFlight; ++i) {
    VK_CHECK(vkCreateSemaphore(device_, &si, nullptr, &imageAvailable_[i]), "sem");
    VK_CHECK(vkCreateSemaphore(device_, &si, nullptr, &renderFinished_[i]), "sem");
    VK_CHECK(vkCreateFence(device_, &fi, nullptr, &inFlight_[i]), "fence");
  }
  return true;
}

bool VulkanRenderer::createSampler(std::string* err) {
  VkSamplerCreateInfo ci{};
  ci.sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
  ci.magFilter = VK_FILTER_LINEAR;
  ci.minFilter = VK_FILTER_LINEAR;
  // REPEAT suits tiled UV textures; the offscreen-image display samples exactly
  // [0,1] so its wrap mode is irrelevant.
  ci.addressModeU = VK_SAMPLER_ADDRESS_MODE_REPEAT;
  ci.addressModeV = VK_SAMPLER_ADDRESS_MODE_REPEAT;
  ci.addressModeW = VK_SAMPLER_ADDRESS_MODE_REPEAT;
  ci.maxLod = 1.0f;
  VK_CHECK(vkCreateSampler(device_, &ci, nullptr, &sampler_), "sampler");
  return true;
}

bool VulkanRenderer::createDescriptorInfra(std::string* err) {
  VkDescriptorSetLayoutBinding b{};
  b.binding = 0;
  b.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
  b.descriptorCount = 1;
  b.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;
  VkDescriptorSetLayoutCreateInfo lci{};
  lci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
  lci.bindingCount = 1;
  lci.pBindings = &b;
  VK_CHECK(vkCreateDescriptorSetLayout(device_, &lci, nullptr, &texSetLayout_),
           "tex descriptor set layout");

  // One combined-image-sampler set per texture (cap = pool size); reset+realloc
  // on each uploadScene.
  const uint32_t kMaxTexSets = 1024;
  VkDescriptorPoolSize ps{};
  ps.type = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
  ps.descriptorCount = kMaxTexSets;
  VkDescriptorPoolCreateInfo pci{};
  pci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
  pci.maxSets = kMaxTexSets;
  pci.poolSizeCount = 1;
  pci.pPoolSizes = &ps;
  VK_CHECK(vkCreateDescriptorPool(device_, &pci, nullptr, &texPool_),
           "tex descriptor pool");
  return true;
}

VkCommandBuffer VulkanRenderer::beginOneShot() {
  VkCommandBufferAllocateInfo ai{};
  ai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
  ai.commandPool = commandPool_;
  ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
  ai.commandBufferCount = 1;
  VkCommandBuffer cb = VK_NULL_HANDLE;
  vkAllocateCommandBuffers(device_, &ai, &cb);
  VkCommandBufferBeginInfo bi{};
  bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
  bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
  vkBeginCommandBuffer(cb, &bi);
  return cb;
}

void VulkanRenderer::endOneShot(VkCommandBuffer cb) {
  vkEndCommandBuffer(cb);
  VkSubmitInfo si{};
  si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
  si.commandBufferCount = 1;
  si.pCommandBuffers = &cb;
  vkQueueSubmit(queue_, 1, &si, VK_NULL_HANDLE);
  vkQueueWaitIdle(queue_);
  vkFreeCommandBuffers(device_, commandPool_, 1, &cb);
}

VkDescriptorSet VulkanRenderer::allocTexDescriptor(VkImageView view) {
  VkDescriptorSetAllocateInfo ai{};
  ai.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
  ai.descriptorPool = texPool_;
  ai.descriptorSetCount = 1;
  ai.pSetLayouts = &texSetLayout_;
  VkDescriptorSet ds = VK_NULL_HANDLE;
  if (vkAllocateDescriptorSets(device_, &ai, &ds) != VK_SUCCESS) return VK_NULL_HANDLE;
  VkDescriptorImageInfo info{};
  info.sampler = sampler_;
  info.imageView = view;
  info.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
  VkWriteDescriptorSet w{};
  w.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
  w.dstSet = ds;
  w.dstBinding = 0;
  w.descriptorCount = 1;
  w.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
  w.pImageInfo = &info;
  vkUpdateDescriptorSets(device_, 1, &w, 0, nullptr);
  return ds;
}

bool VulkanRenderer::createTextureImage(const light3d::Image& img, VkImage* outImg,
                                        VkDeviceMemory* outMem, VkImageView* outView) {
  if (img.width <= 0 || img.height <= 0 || img.data.empty()) return false;
  const VkDeviceSize size = img.data.size();  // RGBA8

  VkBuffer staging = VK_NULL_HANDLE;
  VkDeviceMemory stagingMem = VK_NULL_HANDLE;
  if (!createHostBuffer(size, VK_BUFFER_USAGE_TRANSFER_SRC_BIT, img.data.data(),
                        &staging, &stagingMem)) {
    return false;
  }

  VkImageCreateInfo ici{};
  ici.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
  ici.imageType = VK_IMAGE_TYPE_2D;
  ici.format = VK_FORMAT_R8G8B8A8_UNORM;
  ici.extent = {static_cast<uint32_t>(img.width), static_cast<uint32_t>(img.height), 1};
  ici.mipLevels = 1;
  ici.arrayLayers = 1;
  ici.samples = VK_SAMPLE_COUNT_1_BIT;
  ici.tiling = VK_IMAGE_TILING_OPTIMAL;
  ici.usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
  ici.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
  if (vkCreateImage(device_, &ici, nullptr, outImg) != VK_SUCCESS) {
    vkDestroyBuffer(device_, staging, nullptr);
    vkFreeMemory(device_, stagingMem, nullptr);
    return false;
  }
  VkMemoryRequirements req;
  vkGetImageMemoryRequirements(device_, *outImg, &req);
  VkMemoryAllocateInfo mai{};
  mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  mai.allocationSize = req.size;
  mai.memoryTypeIndex = findMemoryType(req.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
  vkAllocateMemory(device_, &mai, nullptr, outMem);
  vkBindImageMemory(device_, *outImg, *outMem, 0);

  VkCommandBuffer cb = beginOneShot();
  VkImageMemoryBarrier toDst{};
  toDst.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
  toDst.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
  toDst.newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
  toDst.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
  toDst.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
  toDst.image = *outImg;
  toDst.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
  toDst.subresourceRange.levelCount = 1;
  toDst.subresourceRange.layerCount = 1;
  toDst.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
  vkCmdPipelineBarrier(cb, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
                       VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 0, nullptr, 0, nullptr, 1,
                       &toDst);
  VkBufferImageCopy region{};
  region.imageSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
  region.imageSubresource.layerCount = 1;
  region.imageExtent = {static_cast<uint32_t>(img.width), static_cast<uint32_t>(img.height), 1};
  vkCmdCopyBufferToImage(cb, staging, *outImg, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1,
                         &region);
  VkImageMemoryBarrier toRead = toDst;
  toRead.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
  toRead.newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
  toRead.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
  toRead.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
  vkCmdPipelineBarrier(cb, VK_PIPELINE_STAGE_TRANSFER_BIT,
                       VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT, 0, 0, nullptr, 0, nullptr,
                       1, &toRead);
  endOneShot(cb);

  vkDestroyBuffer(device_, staging, nullptr);
  vkFreeMemory(device_, stagingMem, nullptr);

  VkImageViewCreateInfo vci{};
  vci.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
  vci.image = *outImg;
  vci.viewType = VK_IMAGE_VIEW_TYPE_2D;
  vci.format = VK_FORMAT_R8G8B8A8_UNORM;
  vci.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
  vci.subresourceRange.levelCount = 1;
  vci.subresourceRange.layerCount = 1;
  return vkCreateImageView(device_, &vci, nullptr, outView) == VK_SUCCESS;
}

bool VulkanRenderer::createWhiteTexture(std::string* err) {
  light3d::Image w;
  w.width = 1;
  w.height = 1;
  w.channels = 4;
  w.data = {255, 255, 255, 255};
  if (!createTextureImage(w, &whiteImg_, &whiteMem_, &whiteView_)) {
    if (err) *err = "failed to create white texture";
    return false;
  }
  return true;
}

bool VulkanRenderer::init(GLFWwindow* window, std::string* err) {
  window_ = window;
  caps_.backend_name = "Vulkan";
  caps_.usesZeroToOneDepth = true;
  caps_.flipViewportV = false;  // we Y-flip via a negative-height viewport

  if (!createInstance(err)) return false;
  if (!createSurface(err)) return false;
  if (!pickPhysicalDevice(err)) return false;
  if (!createDevice(err)) return false;
  if (!createSwapchain(err)) return false;
  if (!createSwapchainViews(err)) return false;
  if (!createSwapchainRenderPass(err)) return false;
  if (!createSwapchainFramebuffers(err)) return false;
  if (!createOffscreenRenderPass(err)) return false;
  if (!createCommands(err)) return false;
  if (!createSync(err)) return false;
  if (!createSampler(err)) return false;
  if (!createDescriptorInfra(err)) return false;
  if (!createPipeline(err)) return false;       // needs texSetLayout_
  if (!createWhiteTexture(err)) return false;   // needs commandPool_ + texPool_
  return true;
}

bool VulkanRenderer::initImGui(std::string* err) {
  if (!ImGui_ImplGlfw_InitForVulkan(window_, true)) {
    if (err) *err = "ImGui_ImplGlfw_InitForVulkan failed";
    return false;
  }
  ImGui_ImplVulkan_InitInfo info{};
  info.ApiVersion = VK_API_VERSION_1_1;
  info.Instance = instance_;
  info.PhysicalDevice = phys_;
  info.Device = device_;
  info.QueueFamily = queueFamily_;
  info.Queue = queue_;
  info.DescriptorPool = VK_NULL_HANDLE;
  info.DescriptorPoolSize = 16;  // backend creates its own pool (fonts + AddTexture)
  info.MinImageCount = static_cast<uint32_t>(swapImages_.size());
  info.ImageCount = static_cast<uint32_t>(swapImages_.size());
  info.PipelineInfoMain.RenderPass = swapRenderPass_;
  info.UseDynamicRendering = false;
  if (!ImGui_ImplVulkan_Init(&info)) {
    if (err) *err = "ImGui_ImplVulkan_Init failed";
    return false;
  }
  imguiInited_ = true;
  return true;
}

bool VulkanRenderer::createHostBuffer(VkDeviceSize size, VkBufferUsageFlags usage,
                                      const void* data, VkBuffer* buf,
                                      VkDeviceMemory* mem) {
  std::string* err = nullptr;
  VkBufferCreateInfo bi{};
  bi.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
  bi.size = size;
  bi.usage = usage;
  bi.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
  if (vkCreateBuffer(device_, &bi, nullptr, buf) != VK_SUCCESS) return false;

  VkMemoryRequirements req;
  vkGetBufferMemoryRequirements(device_, *buf, &req);
  VkMemoryAllocateInfo ai{};
  ai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  ai.allocationSize = req.size;
  ai.memoryTypeIndex = findMemoryType(
      req.memoryTypeBits,
      VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
  if (vkAllocateMemory(device_, &ai, nullptr, mem) != VK_SUCCESS) return false;
  vkBindBufferMemory(device_, *buf, *mem, 0);

  void* mapped = nullptr;
  vkMapMemory(device_, *mem, 0, size, 0, &mapped);
  std::memcpy(mapped, data, static_cast<size_t>(size));
  vkUnmapMemory(device_, *mem);
  (void)err;
  return true;
}

void VulkanRenderer::destroyScene() {
  for (auto& m : meshes_) {
    if (m.vbo) vkDestroyBuffer(device_, m.vbo, nullptr);
    if (m.vboMem) vkFreeMemory(device_, m.vboMem, nullptr);
    if (m.ebo) vkDestroyBuffer(device_, m.ebo, nullptr);
    if (m.eboMem) vkFreeMemory(device_, m.eboMem, nullptr);
  }
  meshes_.clear();
  matColor_.clear();
  matBaseTex_.clear();

  for (auto v : texViews_) vkDestroyImageView(device_, v, nullptr);
  for (auto i : texImgs_) vkDestroyImage(device_, i, nullptr);
  for (auto m : texMems_) vkFreeMemory(device_, m, nullptr);
  texViews_.clear();
  texImgs_.clear();
  texMems_.clear();
  texDescs_.clear();
  // Free all per-texture descriptor sets (incl. whiteDesc_) in one shot.
  if (texPool_) vkResetDescriptorPool(device_, texPool_, 0);
  whiteDesc_ = VK_NULL_HANDLE;
}

bool VulkanRenderer::uploadScene(const DrawScene& scene, std::string* err) {
  (void)err;
  if (device_) vkDeviceWaitIdle(device_);
  destroyScene();

  // Default white texture descriptor (used by untextured submeshes).
  whiteDesc_ = allocTexDescriptor(whiteView_);

  // Base-color textures.
  texImgs_.reserve(scene.textures.size());
  for (const auto& t : scene.textures) {
    VkImage img = VK_NULL_HANDLE;
    VkDeviceMemory mem = VK_NULL_HANDLE;
    VkImageView view = VK_NULL_HANDLE;
    if (createTextureImage(t.image, &img, &mem, &view)) {
      texImgs_.push_back(img);
      texMems_.push_back(mem);
      texViews_.push_back(view);
      texDescs_.push_back(allocTexDescriptor(view));
    } else {
      // Keep indices aligned with DrawScene::textures; fall back to white.
      texDescs_.push_back(whiteDesc_);
    }
  }

  matColor_.resize(scene.materials.size() * 4);
  matBaseTex_.resize(scene.materials.size());
  for (size_t i = 0; i < scene.materials.size(); ++i) {
    matColor_[i * 4 + 0] = scene.materials[i].baseColor[0];
    matColor_[i * 4 + 1] = scene.materials[i].baseColor[1];
    matColor_[i * 4 + 2] = scene.materials[i].baseColor[2];
    matColor_[i * 4 + 3] = scene.materials[i].alpha;
    matBaseTex_[i] = scene.materials[i].baseColorTex;
  }

  for (const auto& sm : scene.meshes) {
    if (sm.vertices.empty() || sm.indices.empty()) continue;
    VkMeshGPU gm;
    gm.submeshes = sm.submeshes;
    std::memcpy(gm.world, sm.world, sizeof(gm.world));
    if (!createHostBuffer(sm.vertices.size() * sizeof(DrawVertex),
                          VK_BUFFER_USAGE_VERTEX_BUFFER_BIT, sm.vertices.data(),
                          &gm.vbo, &gm.vboMem)) {
      continue;
    }
    if (!createHostBuffer(sm.indices.size() * sizeof(uint32_t),
                          VK_BUFFER_USAGE_INDEX_BUFFER_BIT, sm.indices.data(),
                          &gm.ebo, &gm.eboMem)) {
      vkDestroyBuffer(device_, gm.vbo, nullptr);
      vkFreeMemory(device_, gm.vboMem, nullptr);
      continue;
    }
    meshes_.push_back(gm);
  }
  return true;
}

void VulkanRenderer::destroyOffscreen() {
  if (offscreenTexId_ && imguiInited_) {
    ImGui_ImplVulkan_RemoveTexture(offscreenTexId_);
    offscreenTexId_ = VK_NULL_HANDLE;
  }
  if (offscreenFb_) { vkDestroyFramebuffer(device_, offscreenFb_, nullptr); offscreenFb_ = VK_NULL_HANDLE; }
  if (colorView_) { vkDestroyImageView(device_, colorView_, nullptr); colorView_ = VK_NULL_HANDLE; }
  if (colorImg_) { vkDestroyImage(device_, colorImg_, nullptr); colorImg_ = VK_NULL_HANDLE; }
  if (colorMem_) { vkFreeMemory(device_, colorMem_, nullptr); colorMem_ = VK_NULL_HANDLE; }
  if (depthView_) { vkDestroyImageView(device_, depthView_, nullptr); depthView_ = VK_NULL_HANDLE; }
  if (depthImg_) { vkDestroyImage(device_, depthImg_, nullptr); depthImg_ = VK_NULL_HANDLE; }
  if (depthMem_) { vkFreeMemory(device_, depthMem_, nullptr); depthMem_ = VK_NULL_HANDLE; }
}

void VulkanRenderer::resizeViewport(int width, int height) {
  if (width < 1) width = 1;
  if (height < 1) height = 1;
  if (offscreenFb_ && width == vpW_ && height == vpH_) return;
  if (!device_) return;
  vkDeviceWaitIdle(device_);
  destroyOffscreen();
  vpW_ = width;
  vpH_ = height;

  auto makeImage = [&](VkFormat fmt, VkImageUsageFlags usage, VkImageAspectFlags aspect,
                       VkImage* img, VkDeviceMemory* mem, VkImageView* view) -> bool {
    VkImageCreateInfo ici{};
    ici.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    ici.imageType = VK_IMAGE_TYPE_2D;
    ici.format = fmt;
    ici.extent = {static_cast<uint32_t>(vpW_), static_cast<uint32_t>(vpH_), 1};
    ici.mipLevels = 1;
    ici.arrayLayers = 1;
    ici.samples = VK_SAMPLE_COUNT_1_BIT;
    ici.tiling = VK_IMAGE_TILING_OPTIMAL;
    ici.usage = usage;
    ici.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    if (vkCreateImage(device_, &ici, nullptr, img) != VK_SUCCESS) return false;
    VkMemoryRequirements req;
    vkGetImageMemoryRequirements(device_, *img, &req);
    VkMemoryAllocateInfo ai{};
    ai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    ai.allocationSize = req.size;
    ai.memoryTypeIndex = findMemoryType(req.memoryTypeBits,
                                        VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (vkAllocateMemory(device_, &ai, nullptr, mem) != VK_SUCCESS) return false;
    vkBindImageMemory(device_, *img, *mem, 0);
    VkImageViewCreateInfo vci{};
    vci.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    vci.image = *img;
    vci.viewType = VK_IMAGE_VIEW_TYPE_2D;
    vci.format = fmt;
    vci.subresourceRange.aspectMask = aspect;
    vci.subresourceRange.levelCount = 1;
    vci.subresourceRange.layerCount = 1;
    return vkCreateImageView(device_, &vci, nullptr, view) == VK_SUCCESS;
  };

  makeImage(colorFormat_,
            VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_SAMPLED_BIT,
            VK_IMAGE_ASPECT_COLOR_BIT, &colorImg_, &colorMem_, &colorView_);
  makeImage(depthFormat_, VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT,
            VK_IMAGE_ASPECT_DEPTH_BIT, &depthImg_, &depthMem_, &depthView_);

  VkImageView atts[2] = {colorView_, depthView_};
  VkFramebufferCreateInfo fci{};
  fci.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
  fci.renderPass = offscreenPass_;
  fci.attachmentCount = 2;
  fci.pAttachments = atts;
  fci.width = static_cast<uint32_t>(vpW_);
  fci.height = static_cast<uint32_t>(vpH_);
  fci.layers = 1;
  vkCreateFramebuffer(device_, &fci, nullptr, &offscreenFb_);

  if (imguiInited_) {
    offscreenTexId_ = ImGui_ImplVulkan_AddTexture(
        sampler_, colorView_, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
  }
}

void VulkanRenderer::newFrame() { ImGui_ImplVulkan_NewFrame(); }

void VulkanRenderer::renderFrame(const RenderFrameParams& params) {
  if (params.view) std::memcpy(view_, params.view, sizeof(view_));
  if (params.proj) std::memcpy(proj_, params.proj, sizeof(proj_));
  for (int i = 0; i < 3; ++i) cameraPos_[i] = params.cameraPos[i];
  for (int i = 0; i < 4; ++i) clear_[i] = params.clearColor[i];
  hasParams_ = (params.view && params.proj);
}

ViewportTexHandle VulkanRenderer::viewportTexture() const {
  return reinterpret_cast<ViewportTexHandle>(offscreenTexId_);
}

bool VulkanRenderer::recreateSwapchain() {
  std::string* err = nullptr;
  int w = 0, h = 0;
  glfwGetFramebufferSize(window_, &w, &h);
  if (w == 0 || h == 0) return true;  // minimized; skip
  vkDeviceWaitIdle(device_);
  destroySwapchain();
  if (!createSwapchain(err)) return false;
  if (!createSwapchainViews(err)) return false;
  if (!createSwapchainFramebuffers(err)) return false;
  return true;
}

void VulkanRenderer::present() {
  if (!device_) return;
  vkWaitForFences(device_, 1, &inFlight_[frame_], VK_TRUE, UINT64_MAX);

  uint32_t imageIndex = 0;
  VkResult acq = vkAcquireNextImageKHR(device_, swapchain_, UINT64_MAX,
                                       imageAvailable_[frame_], VK_NULL_HANDLE,
                                       &imageIndex);
  if (acq == VK_ERROR_OUT_OF_DATE_KHR) {
    recreateSwapchain();
    return;
  }
  vkResetFences(device_, 1, &inFlight_[frame_]);

  VkCommandBuffer cb = cmd_[frame_];
  vkResetCommandBuffer(cb, 0);
  VkCommandBufferBeginInfo bi{};
  bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
  vkBeginCommandBuffer(cb, &bi);

  // ---- Offscreen 3D pass ----
  if (offscreenFb_ && hasParams_) {
    VkClearValue clears[2];
    clears[0].color = {{clear_[0], clear_[1], clear_[2], clear_[3]}};
    clears[1].depthStencil = {1.0f, 0};
    VkRenderPassBeginInfo rp{};
    rp.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
    rp.renderPass = offscreenPass_;
    rp.framebuffer = offscreenFb_;
    rp.renderArea.extent = {static_cast<uint32_t>(vpW_), static_cast<uint32_t>(vpH_)};
    rp.clearValueCount = 2;
    rp.pClearValues = clears;
    vkCmdBeginRenderPass(cb, &rp, VK_SUBPASS_CONTENTS_INLINE);

    // Y-flipped viewport so the offscreen image is upright (top-left origin).
    VkViewport vpRect{};
    vpRect.x = 0.0f;
    vpRect.y = static_cast<float>(vpH_);
    vpRect.width = static_cast<float>(vpW_);
    vpRect.height = -static_cast<float>(vpH_);
    vpRect.minDepth = 0.0f;
    vpRect.maxDepth = 1.0f;
    vkCmdSetViewport(cb, 0, 1, &vpRect);
    VkRect2D sc{{0, 0}, {static_cast<uint32_t>(vpW_), static_cast<uint32_t>(vpH_)}};
    vkCmdSetScissor(cb, 0, 1, &sc);
    vkCmdBindPipeline(cb, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline_);

    light3d::Mat4 P = ToMat4(proj_);
    light3d::Mat4 V = ToMat4(view_);
    for (const auto& mesh : meshes_) {
      light3d::Mat4 W = ToMat4(mesh.world);
      light3d::Mat4 MVP = P * V * W;
      float nmat9[9];
      NormalMatrix3(mesh.world, nmat9);
      VkDeviceSize off = 0;
      vkCmdBindVertexBuffers(cb, 0, 1, &mesh.vbo, &off);
      vkCmdBindIndexBuffer(cb, mesh.ebo, 0, VK_INDEX_TYPE_UINT32);
      for (const auto& sub : mesh.submeshes) {
        // Bind the submesh's base-color texture (white if untextured).
        VkDescriptorSet ds = whiteDesc_;
        if (sub.materialId >= 0 &&
            static_cast<size_t>(sub.materialId) < matBaseTex_.size()) {
          const int bt = matBaseTex_[static_cast<size_t>(sub.materialId)];
          if (bt >= 0 && static_cast<size_t>(bt) < texDescs_.size()) {
            ds = texDescs_[static_cast<size_t>(bt)];
          }
        }
        if (ds != VK_NULL_HANDLE) {
          vkCmdBindDescriptorSets(cb, VK_PIPELINE_BIND_POINT_GRAPHICS, pipelineLayout_,
                                  0, 1, &ds, 0, nullptr);
        }
        PushC pc{};
        std::memcpy(pc.mvp, MVP.m, sizeof(pc.mvp));
        // mat3 columns padded to vec4
        for (int c = 0; c < 3; ++c) {
          pc.nmat[c * 4 + 0] = nmat9[c * 3 + 0];
          pc.nmat[c * 4 + 1] = nmat9[c * 3 + 1];
          pc.nmat[c * 4 + 2] = nmat9[c * 3 + 2];
          pc.nmat[c * 4 + 3] = 0.0f;
        }
        if (sub.materialId >= 0 &&
            static_cast<size_t>(sub.materialId) * 4 + 3 < matColor_.size()) {
          const float* mc = &matColor_[static_cast<size_t>(sub.materialId) * 4];
          pc.baseColor[0] = mc[0]; pc.baseColor[1] = mc[1];
          pc.baseColor[2] = mc[2]; pc.baseColor[3] = mc[3];
        } else {
          pc.baseColor[0] = pc.baseColor[1] = pc.baseColor[2] = 0.6f;
          pc.baseColor[3] = 1.0f;
        }
        vkCmdPushConstants(cb, pipelineLayout_,
                           VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
                           0, sizeof(PushC), &pc);
        vkCmdDrawIndexed(cb, sub.indexCount, 1, sub.indexOffset, 0, 0);
      }
    }
    vkCmdEndRenderPass(cb);
  }

  // ---- Swapchain pass: ImGui ----
  VkClearValue clear{};
  clear.color = {{0.06f, 0.06f, 0.07f, 1.0f}};
  VkRenderPassBeginInfo rp{};
  rp.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
  rp.renderPass = swapRenderPass_;
  rp.framebuffer = swapFramebuffers_[imageIndex];
  rp.renderArea.extent = swapExtent_;
  rp.clearValueCount = 1;
  rp.pClearValues = &clear;
  vkCmdBeginRenderPass(cb, &rp, VK_SUBPASS_CONTENTS_INLINE);
  ImGui_ImplVulkan_RenderDrawData(ImGui::GetDrawData(), cb);
  vkCmdEndRenderPass(cb);

  vkEndCommandBuffer(cb);

  VkPipelineStageFlags waitStage = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
  VkSubmitInfo si{};
  si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
  si.waitSemaphoreCount = 1;
  si.pWaitSemaphores = &imageAvailable_[frame_];
  si.pWaitDstStageMask = &waitStage;
  si.commandBufferCount = 1;
  si.pCommandBuffers = &cb;
  si.signalSemaphoreCount = 1;
  si.pSignalSemaphores = &renderFinished_[frame_];
  vkQueueSubmit(queue_, 1, &si, inFlight_[frame_]);

  VkPresentInfoKHR pi{};
  pi.sType = VK_STRUCTURE_TYPE_PRESENT_INFO_KHR;
  pi.waitSemaphoreCount = 1;
  pi.pWaitSemaphores = &renderFinished_[frame_];
  pi.swapchainCount = 1;
  pi.pSwapchains = &swapchain_;
  pi.pImageIndices = &imageIndex;
  VkResult pres = vkQueuePresentKHR(queue_, &pi);
  if (pres == VK_ERROR_OUT_OF_DATE_KHR || pres == VK_SUBOPTIMAL_KHR) {
    recreateSwapchain();
  }
  frame_ = (frame_ + 1) % kFramesInFlight;
}

bool VulkanRenderer::captureViewport(std::vector<uint8_t>* rgba, int* w, int* h) {
  if (!device_ || !colorImg_ || vpW_ < 1 || vpH_ < 1) return false;
  vkDeviceWaitIdle(device_);
  const VkDeviceSize size = static_cast<VkDeviceSize>(vpW_) * vpH_ * 4;

  VkBuffer buf = VK_NULL_HANDLE;
  VkDeviceMemory mem = VK_NULL_HANDLE;
  VkBufferCreateInfo bi{};
  bi.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
  bi.size = size;
  bi.usage = VK_BUFFER_USAGE_TRANSFER_DST_BIT;
  bi.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
  if (vkCreateBuffer(device_, &bi, nullptr, &buf) != VK_SUCCESS) return false;
  VkMemoryRequirements req;
  vkGetBufferMemoryRequirements(device_, buf, &req);
  VkMemoryAllocateInfo ai{};
  ai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  ai.allocationSize = req.size;
  ai.memoryTypeIndex = findMemoryType(
      req.memoryTypeBits,
      VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
  vkAllocateMemory(device_, &ai, nullptr, &mem);
  vkBindBufferMemory(device_, buf, mem, 0);

  VkCommandBufferAllocateInfo cai{};
  cai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
  cai.commandPool = commandPool_;
  cai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
  cai.commandBufferCount = 1;
  VkCommandBuffer cb = VK_NULL_HANDLE;
  vkAllocateCommandBuffers(device_, &cai, &cb);
  VkCommandBufferBeginInfo cbi{};
  cbi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
  cbi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
  vkBeginCommandBuffer(cb, &cbi);

  VkImageMemoryBarrier toSrc{};
  toSrc.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
  toSrc.oldLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
  toSrc.newLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
  toSrc.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
  toSrc.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
  toSrc.image = colorImg_;
  toSrc.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
  toSrc.subresourceRange.levelCount = 1;
  toSrc.subresourceRange.layerCount = 1;
  toSrc.srcAccessMask = VK_ACCESS_SHADER_READ_BIT;
  toSrc.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
  vkCmdPipelineBarrier(cb, VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,
                       VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 0, nullptr, 0, nullptr, 1,
                       &toSrc);

  VkBufferImageCopy region{};
  region.imageSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
  region.imageSubresource.layerCount = 1;
  region.imageExtent = {static_cast<uint32_t>(vpW_), static_cast<uint32_t>(vpH_), 1};
  vkCmdCopyImageToBuffer(cb, colorImg_, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, buf, 1,
                         &region);

  VkImageMemoryBarrier back = toSrc;
  back.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
  back.newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
  back.srcAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
  back.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
  vkCmdPipelineBarrier(cb, VK_PIPELINE_STAGE_TRANSFER_BIT,
                       VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT, 0, 0, nullptr, 0, nullptr,
                       1, &back);

  vkEndCommandBuffer(cb);
  VkSubmitInfo si{};
  si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
  si.commandBufferCount = 1;
  si.pCommandBuffers = &cb;
  vkQueueSubmit(queue_, 1, &si, VK_NULL_HANDLE);
  vkQueueWaitIdle(queue_);

  void* mapped = nullptr;
  vkMapMemory(device_, mem, 0, size, 0, &mapped);
  rgba->resize(static_cast<size_t>(size));
  std::memcpy(rgba->data(), mapped, static_cast<size_t>(size));
  vkUnmapMemory(device_, mem);

  vkFreeCommandBuffers(device_, commandPool_, 1, &cb);
  vkDestroyBuffer(device_, buf, nullptr);
  vkFreeMemory(device_, mem, nullptr);

  *w = vpW_;
  *h = vpH_;
  return true;  // colorFormat_ is R8G8B8A8_UNORM, top-down (Y-flipped viewport)
}

void VulkanRenderer::destroySwapchain() {
  for (auto fb : swapFramebuffers_) vkDestroyFramebuffer(device_, fb, nullptr);
  swapFramebuffers_.clear();
  for (auto v : swapViews_) vkDestroyImageView(device_, v, nullptr);
  swapViews_.clear();
  if (swapchain_) {
    vkDestroySwapchainKHR(device_, swapchain_, nullptr);
    swapchain_ = VK_NULL_HANDLE;
  }
}

void VulkanRenderer::shutdown() {
  if (device_) vkDeviceWaitIdle(device_);
  destroyScene();
  destroyOffscreen();
  if (imguiInited_) {
    ImGui_ImplVulkan_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    imguiInited_ = false;
  }
  if (whiteView_) { vkDestroyImageView(device_, whiteView_, nullptr); whiteView_ = VK_NULL_HANDLE; }
  if (whiteImg_) { vkDestroyImage(device_, whiteImg_, nullptr); whiteImg_ = VK_NULL_HANDLE; }
  if (whiteMem_) { vkFreeMemory(device_, whiteMem_, nullptr); whiteMem_ = VK_NULL_HANDLE; }
  if (texPool_) { vkDestroyDescriptorPool(device_, texPool_, nullptr); texPool_ = VK_NULL_HANDLE; }
  if (texSetLayout_) { vkDestroyDescriptorSetLayout(device_, texSetLayout_, nullptr); texSetLayout_ = VK_NULL_HANDLE; }
  if (sampler_) { vkDestroySampler(device_, sampler_, nullptr); sampler_ = VK_NULL_HANDLE; }
  if (pipeline_) { vkDestroyPipeline(device_, pipeline_, nullptr); pipeline_ = VK_NULL_HANDLE; }
  if (pipelineLayout_) { vkDestroyPipelineLayout(device_, pipelineLayout_, nullptr); pipelineLayout_ = VK_NULL_HANDLE; }
  if (offscreenPass_) { vkDestroyRenderPass(device_, offscreenPass_, nullptr); offscreenPass_ = VK_NULL_HANDLE; }
  for (int i = 0; i < kFramesInFlight; ++i) {
    if (imageAvailable_[i]) vkDestroySemaphore(device_, imageAvailable_[i], nullptr);
    if (renderFinished_[i]) vkDestroySemaphore(device_, renderFinished_[i], nullptr);
    if (inFlight_[i]) vkDestroyFence(device_, inFlight_[i], nullptr);
    imageAvailable_[i] = renderFinished_[i] = VK_NULL_HANDLE;
    inFlight_[i] = VK_NULL_HANDLE;
  }
  if (commandPool_) { vkDestroyCommandPool(device_, commandPool_, nullptr); commandPool_ = VK_NULL_HANDLE; }
  destroySwapchain();
  if (swapRenderPass_) { vkDestroyRenderPass(device_, swapRenderPass_, nullptr); swapRenderPass_ = VK_NULL_HANDLE; }
  if (device_) { vkDestroyDevice(device_, nullptr); device_ = VK_NULL_HANDLE; }
  if (surface_) { vkDestroySurfaceKHR(instance_, surface_, nullptr); surface_ = VK_NULL_HANDLE; }
  if (instance_) { vkDestroyInstance(instance_, nullptr); instance_ = VK_NULL_HANDLE; }
}

std::unique_ptr<Renderer> CreateVulkanRenderer() {
  return std::unique_ptr<Renderer>(new VulkanRenderer());
}

}  // namespace tusdview
