CXX = g++
CXXFLAGS = -std=c++14 -I../../../src -I../../../
LDFLAGS = -L../../../build -ltinyusdz_static -lpthread

test_grouped_params: test_grouped_params.cc
	$(CXX) $(CXXFLAGS) -o test_grouped_params test_grouped_params.cc $(LDFLAGS)

clean:
	rm -f test_grouped_params

.PHONY: clean
