#include "tinysubdiv.hh"
#include <iostream>
#include <vector>
#include <fstream>
#include <chrono>
#include <cstring>

using namespace tinysubdiv;

void write_obj(const std::string& filename, const std::vector<float>& vertices, const std::vector<uint32_t>& indices) {
  std::ofstream out(filename);
  if (!out) {
    std::cerr << "Failed to open " << filename << " for writing\n";
    return;
  }

  out << "# Generated by tinysubdiv\n";

  // Write vertices
  for (size_t i = 0; i < vertices.size(); i += 3) {
    out << "v " << vertices[i] << " " << vertices[i + 1] << " " << vertices[i + 2] << "\n";
  }

  // Write faces (OBJ uses 1-based indexing)
  for (size_t i = 0; i < indices.size(); i += 3) {
    out << "f " << (indices[i] + 1) << " " << (indices[i + 1] + 1) << " " << (indices[i + 2] + 1) << "\n";
  }

  std::cout << "Wrote " << filename << " (" << vertices.size() / 3 << " vertices, "
            << indices.size() / 3 << " triangles)\n";
}

void test_cube_subdivision() {
  std::cout << "\n=== Testing Cube Subdivision ===\n";

  // Define a cube
  float cube_vertices[] = {
    // Front face
    -1.0f, -1.0f,  1.0f,
     1.0f, -1.0f,  1.0f,
     1.0f,  1.0f,  1.0f,
    -1.0f,  1.0f,  1.0f,
    // Back face
    -1.0f, -1.0f, -1.0f,
     1.0f, -1.0f, -1.0f,
     1.0f,  1.0f, -1.0f,
    -1.0f,  1.0f, -1.0f
  };

  // Cube faces (quads)
  uint32_t cube_indices[] = {
    0, 1, 2, 3,  // Front
    4, 7, 6, 5,  // Back
    0, 4, 5, 1,  // Bottom
    3, 2, 6, 7,  // Top
    0, 3, 7, 4,  // Left
    1, 5, 6, 2   // Right
  };

  uint32_t face_counts[] = {4, 4, 4, 4, 4, 4}; // All quads

  SubdivisionMesh mesh;
  mesh.set_vertices(cube_vertices, 8);
  mesh.set_faces(cube_indices, face_counts, 6);

  // Test different subdivision levels
  for (int level = 0; level <= 3; ++level) {
    SubdivisionMesh test_mesh;
    test_mesh.set_vertices(cube_vertices, 8);
    test_mesh.set_faces(cube_indices, face_counts, 6);

    auto start = std::chrono::high_resolution_clock::now();
    test_mesh.subdivide_catmull_clark(level);
    auto end = std::chrono::high_resolution_clock::now();

    std::chrono::duration<double, std::milli> elapsed = end - start;

    std::vector<float> vertices;
    std::vector<uint32_t> indices;
    test_mesh.get_triangulated(vertices, indices);

    std::cout << "Level " << level << ": "
              << vertices.size() / 3 << " vertices, "
              << indices.size() / 3 << " triangles, "
              << "Time: " << elapsed.count() << " ms\n";

    std::string filename = "cube_subdiv_level_" + std::to_string(level) + ".obj";
    write_obj(filename, vertices, indices);
  }
}

void test_plane_subdivision_with_creases() {
  std::cout << "\n=== Testing Plane with Creases ===\n";

  // Define a 3x3 grid plane
  float plane_vertices[] = {
    -1.0f, 0.0f, -1.0f,
     0.0f, 0.0f, -1.0f,
     1.0f, 0.0f, -1.0f,
    -1.0f, 0.0f,  0.0f,
     0.0f, 0.0f,  0.0f,
     1.0f, 0.0f,  0.0f,
    -1.0f, 0.0f,  1.0f,
     0.0f, 0.0f,  1.0f,
     1.0f, 0.0f,  1.0f
  };

  // 4 quad faces
  uint32_t plane_indices[] = {
    0, 1, 4, 3,
    1, 2, 5, 4,
    3, 4, 7, 6,
    4, 5, 8, 7
  };

  uint32_t face_counts[] = {4, 4, 4, 4};

  // Define creases along the middle
  uint32_t crease_indices[] = {
    1, 4,
    4, 7
  };
  float crease_sharpness[] = {10.0f, 10.0f};

  SubdivisionMesh mesh;
  mesh.set_vertices(plane_vertices, 9);
  mesh.set_faces(plane_indices, face_counts, 4);
  mesh.set_creases(crease_indices, crease_sharpness, 2);

  auto start = std::chrono::high_resolution_clock::now();
  mesh.subdivide_catmull_clark(2);
  auto end = std::chrono::high_resolution_clock::now();

  std::chrono::duration<double, std::milli> elapsed = end - start;

  std::vector<float> vertices;
  std::vector<uint32_t> indices;
  mesh.get_triangulated(vertices, indices);

  std::cout << "Plane with creases: "
            << vertices.size() / 3 << " vertices, "
            << indices.size() / 3 << " triangles, "
            << "Time: " << elapsed.count() << " ms\n";

  write_obj("plane_with_creases.obj", vertices, indices);
}

void benchmark_chunked_array() {
  std::cout << "\n=== Benchmarking ChunkedTypedArray ===\n";

  const size_t test_sizes[] = {1000, 10000, 100000, 1000000};

  for (size_t size : test_sizes) {
    ChunkedTypedArray<Vec3f> chunked_array;
    std::vector<Vec3f> std_vector;

    // Benchmark push_back
    auto start = std::chrono::high_resolution_clock::now();
    for (size_t i = 0; i < size; ++i) {
      chunked_array.push_back(Vec3f(i, i * 2, i * 3));
    }
    auto end = std::chrono::high_resolution_clock::now();
    auto chunked_time = std::chrono::duration<double, std::micro>(end - start).count();

    start = std::chrono::high_resolution_clock::now();
    for (size_t i = 0; i < size; ++i) {
      std_vector.push_back(Vec3f(i, i * 2, i * 3));
    }
    end = std::chrono::high_resolution_clock::now();
    auto vector_time = std::chrono::duration<double, std::micro>(end - start).count();

    // Benchmark random access
    size_t sum = 0;
    start = std::chrono::high_resolution_clock::now();
    for (size_t i = 0; i < std::min(size, size_t(10000)); ++i) {
      size_t idx = (i * 7919) % size; // Prime number for pseudo-random access
      sum += static_cast<size_t>(chunked_array[idx].x);
    }
    end = std::chrono::high_resolution_clock::now();
    auto chunked_access_time = std::chrono::duration<double, std::micro>(end - start).count();

    start = std::chrono::high_resolution_clock::now();
    for (size_t i = 0; i < std::min(size, size_t(10000)); ++i) {
      size_t idx = (i * 7919) % size;
      sum += static_cast<size_t>(std_vector[idx].x);
    }
    end = std::chrono::high_resolution_clock::now();
    auto vector_access_time = std::chrono::duration<double, std::micro>(end - start).count();

    std::cout << "Size " << size << ":\n";
    std::cout << "  Push back: ChunkedArray=" << chunked_time << "μs, std::vector=" << vector_time << "μs\n";
    std::cout << "  Random access: ChunkedArray=" << chunked_access_time << "μs, std::vector=" << vector_access_time << "μs\n";
    std::cout << "  Memory chunks used: " << chunked_array.get_chunk_count() << "\n";
  }
}

void test_mixed_topology() {
  std::cout << "\n=== Testing Mixed Triangle/Quad Mesh ===\n";

  // Pyramid with quad base
  float vertices[] = {
    -1.0f, 0.0f, -1.0f,
     1.0f, 0.0f, -1.0f,
     1.0f, 0.0f,  1.0f,
    -1.0f, 0.0f,  1.0f,
     0.0f, 2.0f,  0.0f  // apex
  };

  uint32_t indices[] = {
    0, 1, 2, 3,  // Base (quad)
    0, 1, 4,     // Triangle faces
    1, 2, 4,
    2, 3, 4,
    3, 0, 4
  };

  uint32_t face_counts[] = {4, 3, 3, 3, 3};

  SubdivisionMesh mesh;
  mesh.set_vertices(vertices, 5);
  mesh.set_faces(indices, face_counts, 5);

  mesh.subdivide_catmull_clark(2);

  std::vector<float> out_vertices;
  std::vector<uint32_t> out_indices;
  mesh.get_triangulated(out_vertices, out_indices);

  std::cout << "Mixed topology result: "
            << out_vertices.size() / 3 << " vertices, "
            << out_indices.size() / 3 << " triangles\n";

  write_obj("pyramid_subdiv.obj", out_vertices, out_indices);
}

void test_loop_subdivision() {
  std::cout << "\n=== Testing Loop Subdivision (Triangles Only) ===\n";

  // Create an octahedron
  float vertices[] = {
     1.0f,  0.0f,  0.0f,
    -1.0f,  0.0f,  0.0f,
     0.0f,  1.0f,  0.0f,
     0.0f, -1.0f,  0.0f,
     0.0f,  0.0f,  1.0f,
     0.0f,  0.0f, -1.0f
  };

  uint32_t indices[] = {
    0, 2, 4,  // Top front
    2, 1, 4,  // Top left
    1, 3, 4,  // Bottom left
    3, 0, 4,  // Bottom right
    2, 0, 5,  // Top front (negative z)
    1, 2, 5,  // Top left (negative z)
    3, 1, 5,  // Bottom left (negative z)
    0, 3, 5   // Bottom right (negative z)
  };

  uint32_t face_counts[] = {3, 3, 3, 3, 3, 3, 3, 3};

  // Test different subdivision levels
  for (int level = 0; level <= 3; ++level) {
    SubdivisionMesh mesh;
    mesh.set_vertices(vertices, 6);
    mesh.set_faces(indices, face_counts, 8);

    auto start = std::chrono::high_resolution_clock::now();
    mesh.subdivide_loop(level);
    auto end = std::chrono::high_resolution_clock::now();

    std::chrono::duration<double, std::milli> elapsed = end - start;

    std::vector<float> out_verts;
    std::vector<uint32_t> out_indices;
    mesh.get_triangulated(out_verts, out_indices);

    std::cout << "Loop Level " << level << ": "
              << out_verts.size() / 3 << " vertices, "
              << out_indices.size() / 3 << " triangles, "
              << "Time: " << elapsed.count() << " ms\n";

    std::string filename = "octahedron_loop_level_" + std::to_string(level) + ".obj";
    write_obj(filename, out_verts, out_indices);
  }
}

int main(int argc, char** argv) {
  std::cout << "TinySubdiv Example Program\n";
  std::cout << "==========================\n";

  // Check for SIMD support
#ifdef TINYSUBDIV_USE_SSE
  std::cout << "SSE support: ENABLED\n";
#else
  std::cout << "SSE support: DISABLED\n";
#endif

#ifdef TINYSUBDIV_USE_AVX
  std::cout << "AVX support: ENABLED\n";
#else
  std::cout << "AVX support: DISABLED\n";
#endif

#ifdef TINYSUBDIV_USE_AVX512
  std::cout << "AVX512 support: ENABLED\n";
#else
  std::cout << "AVX512 support: DISABLED\n";
#endif

#ifdef TINYSUBDIV_USE_NEON
  std::cout << "NEON support: ENABLED\n";
#else
  std::cout << "NEON support: DISABLED\n";
#endif

  // Run tests
  test_cube_subdivision();
  test_plane_subdivision_with_creases();
  test_mixed_topology();
  test_loop_subdivision();
  benchmark_chunked_array();

  std::cout << "\nAll tests completed!\n";
  return 0;
}