#include "tinysubdiv.hh"
#include <cassert>
#include <cmath>
#include <iostream>
#include <vector>
#include <fstream>
#include <chrono>

using namespace tinysubdiv;

void write_obj(const std::string& filename, const std::vector<float>& vertices, const std::vector<uint32_t>& indices) {
  std::ofstream out(filename);
  if (!out) {
    std::cerr << "Failed to open " << filename << " for writing\n";
    return;
  }

  out << "# Generated by tinysubdiv Loop subdivision\n";

  // Write vertices
  for (size_t i = 0; i < vertices.size(); i += 3) {
    out << "v " << vertices[i] << " " << vertices[i + 1] << " " << vertices[i + 2] << "\n";
  }

  // Write faces (OBJ uses 1-based indexing)
  for (size_t i = 0; i < indices.size(); i += 3) {
    out << "f " << (indices[i] + 1) << " " << (indices[i + 1] + 1) << " " << (indices[i + 2] + 1) << "\n";
  }

  std::cout << "Wrote " << filename << " (" << vertices.size() / 3 << " vertices, "
            << indices.size() / 3 << " triangles)\n";
}

void test_tetrahedron_loop() {
  std::cout << "Testing Loop subdivision on tetrahedron..." << std::endl;

  // Create a regular tetrahedron
  const float sqrt2 = std::sqrt(2.0f);
  const float sqrt6 = std::sqrt(6.0f);

  float vertices[] = {
    0.0f, 0.0f, 1.0f,                    // Top vertex
    2.0f * sqrt2 / 3.0f, 0.0f, -1.0f/3.0f,  // Base vertex 1
    -sqrt2 / 3.0f, sqrt6 / 3.0f, -1.0f/3.0f,   // Base vertex 2
    -sqrt2 / 3.0f, -sqrt6 / 3.0f, -1.0f/3.0f   // Base vertex 3
  };

  // Tetrahedron faces (4 triangles)
  uint32_t indices[] = {
    0, 1, 2,  // Face 1
    0, 2, 3,  // Face 2
    0, 3, 1,  // Face 3
    1, 3, 2   // Face 4 (base)
  };

  uint32_t face_counts[] = {3, 3, 3, 3};

  SubdivisionMesh mesh;
  mesh.set_vertices(vertices, 4);
  mesh.set_faces(indices, face_counts, 4);

  // Test Loop subdivision
  mesh.subdivide_loop(2);

  std::vector<float> out_vertices;
  std::vector<uint32_t> out_indices;
  mesh.get_triangulated(out_vertices, out_indices);

  write_obj("tetrahedron_loop.obj", out_vertices, out_indices);

  // After 2 levels: 4 triangles -> 16 -> 64 triangles
  assert(out_indices.size() == 64 * 3);
  std::cout << "  Tetrahedron Loop subdivision test passed!" << std::endl;
}

void test_icosahedron_loop() {
  std::cout << "Testing Loop subdivision on icosahedron..." << std::endl;

  // Golden ratio
  const float phi = (1.0f + std::sqrt(5.0f)) / 2.0f;

  // Icosahedron vertices
  float vertices[] = {
    -1,  phi,  0,
     1,  phi,  0,
    -1, -phi,  0,
     1, -phi,  0,
     0, -1,  phi,
     0,  1,  phi,
     0, -1, -phi,
     0,  1, -phi,
     phi,  0, -1,
     phi,  0,  1,
    -phi,  0, -1,
    -phi,  0,  1
  };

  // Normalize vertices to unit sphere
  for (int i = 0; i < 12; ++i) {
    float x = vertices[i * 3];
    float y = vertices[i * 3 + 1];
    float z = vertices[i * 3 + 2];
    float len = std::sqrt(x*x + y*y + z*z);
    vertices[i * 3] /= len;
    vertices[i * 3 + 1] /= len;
    vertices[i * 3 + 2] /= len;
  }

  // Icosahedron faces (20 triangles)
  uint32_t indices[] = {
    0, 11, 5,
    0, 5, 1,
    0, 1, 7,
    0, 7, 10,
    0, 10, 11,
    1, 5, 9,
    5, 11, 4,
    11, 10, 2,
    10, 7, 6,
    7, 1, 8,
    3, 9, 4,
    3, 4, 2,
    3, 2, 6,
    3, 6, 8,
    3, 8, 9,
    4, 9, 5,
    2, 4, 11,
    6, 2, 10,
    8, 6, 7,
    9, 8, 1
  };

  uint32_t face_counts[20];
  for (int i = 0; i < 20; ++i) {
    face_counts[i] = 3;
  }

  SubdivisionMesh mesh;
  mesh.set_vertices(vertices, 12);
  mesh.set_faces(indices, face_counts, 20);

  // Apply Loop subdivision
  mesh.subdivide_loop(1);

  std::vector<float> out_vertices;
  std::vector<uint32_t> out_indices;
  mesh.get_triangulated(out_vertices, out_indices);

  write_obj("icosahedron_loop.obj", out_vertices, out_indices);

  // After 1 level: 20 triangles -> 80 triangles
  assert(out_indices.size() == 80 * 3);
  std::cout << "  Icosahedron Loop subdivision test passed!" << std::endl;
}

void test_triangle_with_boundary() {
  std::cout << "Testing Loop subdivision with boundary..." << std::endl;

  // Create a simple triangle strip (2 triangles sharing an edge)
  float vertices[] = {
    0.0f, 0.0f, 0.0f,
    1.0f, 0.0f, 0.0f,
    0.5f, 1.0f, 0.0f,
    1.5f, 1.0f, 0.0f
  };

  uint32_t indices[] = {
    0, 1, 2,  // First triangle
    1, 3, 2   // Second triangle
  };

  uint32_t face_counts[] = {3, 3};

  SubdivisionMesh mesh;
  mesh.set_vertices(vertices, 4);
  mesh.set_faces(indices, face_counts, 2);

  // Apply Loop subdivision
  mesh.subdivide_loop(2);

  std::vector<float> out_vertices;
  std::vector<uint32_t> out_indices;
  mesh.get_triangulated(out_vertices, out_indices);

  write_obj("triangle_strip_loop.obj", out_vertices, out_indices);

  // After 2 levels: 2 triangles -> 8 -> 32 triangles
  assert(out_indices.size() == 32 * 3);
  std::cout << "  Triangle with boundary Loop test passed!" << std::endl;
}

void test_loop_beta_weights() {
  std::cout << "Testing Loop beta weight calculation..." << std::endl;

  SubdivisionMesh mesh;

  // Test Warren's beta formula
  float beta3 = mesh.loop_beta(3);
  float expected3 = 3.0f / 16.0f;
  assert(std::abs(beta3 - expected3) < 1e-6f);

  float beta4 = mesh.loop_beta(4);
  float expected4 = 3.0f / 32.0f;
  assert(std::abs(beta4 - expected4) < 1e-6f);

  float beta6 = mesh.loop_beta(6);
  float expected6 = 1.0f / 16.0f;
  assert(std::abs(beta6 - expected6) < 1e-6f);

  std::cout << "  Beta weight tests passed!" << std::endl;
}

void benchmark_loop_vs_catmull_clark() {
  std::cout << "\nBenchmarking Loop vs Catmull-Clark..." << std::endl;

  // Create an octahedron (all triangles)
  float vertices[] = {
     1.0f,  0.0f,  0.0f,
    -1.0f,  0.0f,  0.0f,
     0.0f,  1.0f,  0.0f,
     0.0f, -1.0f,  0.0f,
     0.0f,  0.0f,  1.0f,
     0.0f,  0.0f, -1.0f
  };

  uint32_t indices[] = {
    0, 2, 4,
    2, 1, 4,
    1, 3, 4,
    3, 0, 4,
    2, 0, 5,
    1, 2, 5,
    3, 1, 5,
    0, 3, 5
  };

  uint32_t face_counts[8];
  for (int i = 0; i < 8; ++i) {
    face_counts[i] = 3;
  }

  // Test Loop subdivision
  {
    SubdivisionMesh mesh;
    mesh.set_vertices(vertices, 6);
    mesh.set_faces(indices, face_counts, 8);

    auto start = std::chrono::high_resolution_clock::now();
    mesh.subdivide_loop(3);
    auto end = std::chrono::high_resolution_clock::now();

    std::chrono::duration<double, std::milli> elapsed = end - start;

    std::vector<float> out_verts;
    std::vector<uint32_t> out_indices;
    mesh.get_triangulated(out_verts, out_indices);

    std::cout << "  Loop (3 levels): "
              << out_verts.size() / 3 << " vertices, "
              << out_indices.size() / 3 << " triangles, "
              << "Time: " << elapsed.count() << " ms\n";
  }

  // For comparison with Catmull-Clark (converts triangles to quads)
  {
    SubdivisionMesh mesh;
    mesh.set_vertices(vertices, 6);
    mesh.set_faces(indices, face_counts, 8);

    auto start = std::chrono::high_resolution_clock::now();
    mesh.subdivide_catmull_clark(3);
    auto end = std::chrono::high_resolution_clock::now();

    std::chrono::duration<double, std::milli> elapsed = end - start;

    std::vector<float> out_verts;
    std::vector<uint32_t> out_indices;
    mesh.get_triangulated(out_verts, out_indices);

    std::cout << "  Catmull-Clark (3 levels): "
              << out_verts.size() / 3 << " vertices, "
              << out_indices.size() / 3 << " triangles, "
              << "Time: " << elapsed.count() << " ms\n";
  }
}

int main() {
  std::cout << "Loop Subdivision Tests\n";
  std::cout << "======================\n";

  try {
    test_loop_beta_weights();
    test_tetrahedron_loop();
    test_icosahedron_loop();
    test_triangle_with_boundary();
    benchmark_loop_vs_catmull_clark();

    std::cout << "\nAll Loop subdivision tests passed successfully!" << std::endl;
    return 0;
  } catch (const std::exception& e) {
    std::cerr << "Test failed with exception: " << e.what() << std::endl;
    return 1;
  }
}