#include "usd-subdiv.hh"
#include <iostream>
#include <fstream>
#include <cassert>

using namespace tinysubdiv;

void write_obj(const std::string& filename,
               const std::vector<float>& vertices,
               const std::vector<uint32_t>& indices) {
  std::ofstream out(filename);
  if (!out) {
    std::cerr << "Failed to open " << filename << " for writing\n";
    return;
  }

  out << "# Generated by tinysubdiv USD subdivision test\n";

  // Write vertices
  for (size_t i = 0; i < vertices.size(); i += 3) {
    out << "v " << vertices[i] << " " << vertices[i + 1] << " " << vertices[i + 2] << "\n";
  }

  // Write faces
  for (size_t i = 0; i < indices.size(); i += 3) {
    out << "f " << (indices[i] + 1) << " " << (indices[i + 1] + 1)
        << " " << (indices[i + 2] + 1) << "\n";
  }
}

void test_usd_creases() {
  std::cout << "\n=== Testing USD Creases with Sharpness ===\n";

  // Create a grid mesh
  float vertices[] = {
    0.0f, 0.0f, 0.0f,   1.0f, 0.0f, 0.0f,   2.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 1.0f,   1.0f, 0.0f, 1.0f,   2.0f, 0.0f, 1.0f,
    0.0f, 0.0f, 2.0f,   1.0f, 0.0f, 2.0f,   2.0f, 0.0f, 2.0f
  };

  uint32_t indices[] = {
    0, 1, 4, 3,
    1, 2, 5, 4,
    3, 4, 7, 6,
    4, 5, 8, 7
  };

  uint32_t face_counts[] = {4, 4, 4, 4};

  UsdSubdivisionMesh mesh;
  mesh.set_vertices(vertices, 9);
  mesh.set_faces(indices, face_counts, 4);

  // Set up USD subdivision descriptor
  UsdSubdivisionDescriptor desc;
  desc.scheme = SubdivisionScheme::CatmullClark;
  desc.interpolateBoundary = InterpolateBoundary::EdgeAndCorner;

  // Add creases with USD sharpness values
  desc.creaseIndices = {1, 4, 4, 7};  // Middle vertical and horizontal
  desc.creaseLengths = {2, 2};
  desc.creaseSharpnesses = {5.0f, 10.0f};  // USD scale: 5 = half sharp, 10 = fully sharp

  // Add corner with sharpness
  desc.cornerIndices = {4};  // Center vertex
  desc.cornerSharpnesses = {7.5f};

  mesh.set_subdivision_descriptor(desc);

  // Subdivide
  mesh.subdivide_usd(2);

  // Get result
  std::vector<float> out_verts;
  std::vector<uint32_t> out_indices;
  mesh.get_triangulated(out_verts, out_indices);

  write_obj("usd_creases_test.obj", out_verts, out_indices);

  auto stats = mesh.get_subdivision_stats();
  std::cout << "Stats: " << stats.num_creases << " creases, "
            << stats.num_corners << " corners\n";
}

void test_usd_holes() {
  std::cout << "\n=== Testing USD Holes ===\n";

  // Create a 3x3 grid of quads
  std::vector<float> vertices;
  for (int y = 0; y < 4; ++y) {
    for (int x = 0; x < 4; ++x) {
      vertices.push_back(static_cast<float>(x));
      vertices.push_back(0.0f);
      vertices.push_back(static_cast<float>(y));
    }
  }

  std::vector<uint32_t> indices;
  std::vector<uint32_t> face_counts;

  for (int y = 0; y < 3; ++y) {
    for (int x = 0; x < 3; ++x) {
      int idx = y * 4 + x;
      indices.push_back(idx);
      indices.push_back(idx + 1);
      indices.push_back(idx + 5);
      indices.push_back(idx + 4);
      face_counts.push_back(4);
    }
  }

  UsdSubdivisionMesh mesh;
  mesh.set_vertices(vertices.data(), vertices.size() / 3);
  mesh.set_faces(indices.data(), face_counts.data(), face_counts.size());

  // Set up USD descriptor with holes
  UsdSubdivisionDescriptor desc;
  desc.scheme = SubdivisionScheme::CatmullClark;
  desc.holeIndices = {4, 1, 7};  // Mark center and two corners as holes

  mesh.set_subdivision_descriptor(desc);

  std::cout << "Before subdivision: " << face_counts.size() << " faces, "
            << desc.holeIndices.size() << " holes\n";

  // Subdivide
  mesh.subdivide_usd(1);

  // Get result
  std::vector<float> out_verts;
  std::vector<uint32_t> out_indices;
  mesh.get_triangulated(out_verts, out_indices);

  write_obj("usd_holes_test.obj", out_verts, out_indices);

  std::cout << "After subdivision: " << out_indices.size() / 3 << " triangles\n";
}

void test_interpolate_boundary_modes() {
  std::cout << "\n=== Testing Interpolate Boundary Modes ===\n";

  // L-shaped mesh to test boundary interpolation
  float vertices[] = {
    0.0f, 0.0f, 0.0f,
    1.0f, 0.0f, 0.0f,
    2.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 1.0f,
    1.0f, 0.0f, 1.0f,
    0.0f, 0.0f, 2.0f,
    1.0f, 0.0f, 2.0f
  };

  uint32_t indices[] = {
    0, 1, 4, 3,
    1, 2, 4,    // triangle to test mixed topology
    3, 4, 6, 5
  };

  uint32_t face_counts[] = {4, 3, 4};

  const char* mode_names[] = {"None", "EdgeAndCorner", "EdgeOnly"};
  InterpolateBoundary modes[] = {
    InterpolateBoundary::None,
    InterpolateBoundary::EdgeAndCorner,
    InterpolateBoundary::EdgeOnly
  };

  for (int i = 0; i < 3; ++i) {
    UsdSubdivisionMesh mesh;
    mesh.set_vertices(vertices, 7);
    mesh.set_faces(indices, face_counts, 3);

    UsdSubdivisionDescriptor desc;
    desc.scheme = SubdivisionScheme::CatmullClark;
    desc.interpolateBoundary = modes[i];

    mesh.set_subdivision_descriptor(desc);
    mesh.subdivide_usd(2);

    std::vector<float> out_verts;
    std::vector<uint32_t> out_indices;
    mesh.get_triangulated(out_verts, out_indices);

    std::string filename = std::string("usd_boundary_") + mode_names[i] + ".obj";
    write_obj(filename, out_verts, out_indices);

    std::cout << "  " << mode_names[i] << ": "
              << out_verts.size() / 3 << " vertices\n";
  }
}

void test_subdivision_schemes() {
  std::cout << "\n=== Testing Different Subdivision Schemes ===\n";

  // Triangle mesh for Loop subdivision
  float tri_vertices[] = {
    0.0f, 0.0f, 0.0f,
    2.0f, 0.0f, 0.0f,
    1.0f, 2.0f, 0.0f,
    1.0f, 1.0f, 2.0f
  };

  uint32_t tri_indices[] = {
    0, 1, 2,
    0, 1, 3,
    1, 2, 3,
    2, 0, 3
  };

  uint32_t tri_face_counts[] = {3, 3, 3, 3};

  // Test Loop subdivision
  {
    UsdSubdivisionMesh mesh;
    mesh.set_vertices(tri_vertices, 4);
    mesh.set_faces(tri_indices, tri_face_counts, 4);

    UsdSubdivisionDescriptor desc;
    desc.scheme = SubdivisionScheme::Loop;
    desc.triangleRule = TriangleSubdivisionRule::Smooth;

    mesh.set_subdivision_descriptor(desc);
    mesh.subdivide_usd(2);

    std::vector<float> out_verts;
    std::vector<uint32_t> out_indices;
    mesh.get_triangulated(out_verts, out_indices);

    write_obj("usd_loop_scheme.obj", out_verts, out_indices);
    std::cout << "  Loop scheme: " << out_indices.size() / 3 << " triangles\n";
  }

  // Test Catmull-Clark on same mesh
  {
    UsdSubdivisionMesh mesh;
    mesh.set_vertices(tri_vertices, 4);
    mesh.set_faces(tri_indices, tri_face_counts, 4);

    UsdSubdivisionDescriptor desc;
    desc.scheme = SubdivisionScheme::CatmullClark;

    mesh.set_subdivision_descriptor(desc);
    mesh.subdivide_usd(2);

    std::vector<float> out_verts;
    std::vector<uint32_t> out_indices;
    mesh.get_triangulated(out_verts, out_indices);

    write_obj("usd_catmullclark_scheme.obj", out_verts, out_indices);
    std::cout << "  Catmull-Clark scheme: " << out_indices.size() / 3 << " triangles\n";
  }
}

void test_usd_utils() {
  std::cout << "\n=== Testing USD Utils ===\n";

  // Test scheme parsing
  assert(usd_utils::parse_subdivision_scheme("catmullClark") == SubdivisionScheme::CatmullClark);
  assert(usd_utils::parse_subdivision_scheme("loop") == SubdivisionScheme::Loop);
  assert(usd_utils::to_string(SubdivisionScheme::Bilinear) == "bilinear");

  // Test boundary mode parsing
  assert(usd_utils::parse_interpolate_boundary("edgeAndCorner") == InterpolateBoundary::EdgeAndCorner);
  assert(usd_utils::to_string(InterpolateBoundary::EdgeOnly) == "edgeOnly");

  // Test sharpness conversion
  float usd_sharp = 7.5f;
  float internal = usd_utils::usd_to_internal_sharpness(usd_sharp);
  assert(internal == 0.75f);
  assert(usd_utils::internal_to_usd_sharpness(internal) == usd_sharp);

  // Test crease validation
  std::vector<int32_t> indices = {0, 1, 2, 3, 4, 5};
  std::vector<int32_t> lengths = {2, 3};  // 2 + 3 = 5, but have 6 indices
  std::vector<float> sharpnesses = {5.0f, 10.0f};
  assert(!usd_utils::validate_creases(indices, lengths, sharpnesses));

  lengths = {2, 4};  // 2 + 4 = 6, matches indices
  assert(usd_utils::validate_creases(indices, lengths, sharpnesses));

  std::cout << "  All USD utils tests passed!\n";
}

int main() {
  std::cout << "USD Subdivision Tests\n";
  std::cout << "=====================\n";

  test_usd_utils();
  test_usd_creases();
  test_usd_holes();
  test_interpolate_boundary_modes();
  test_subdivision_schemes();

  std::cout << "\nAll USD subdivision tests completed!\n";
  return 0;
}