curdir=`pwd`

builddir=${curdir}/build

rm -rf ${builddir}
mkdir ${builddir}


cd ${builddir} && CXX=clang++ CC=clang cmake \
  -DCMAKE_VERBOSE_MAKEFILE=1 \
  -DCMAKE_BUILD_TYPE=Debug \
  -DLIGHTUSD_WITH_AUDIO=0 \
  -DLIGHTUSD_WITH_EXR=0 \
  -DLIGHTUSD_WITH_MODULE_USDA_READER=1 \
  -DLIGHTUSD_WITH_MODULE_USDA_WRITER=1 \
  -DLIGHTUSD_WITH_MODULE_USDC_READER=1 \
  -DLIGHTUSD_WITH_MODULE_USDC_WRITER=1 \
  -DLIGHTUSD_WITH_USDOBJ=0 \
  -DLIGHTUSD_WITH_USDVOX=0 \
  -DLIGHTUSD_COMPILE_TIME_TRACE=0 \
  -DSANITIZE_ADDRESS=0 \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  ..
