curdir=`pwd`

builddir=${curdir}/build

rm -rf ${builddir}
mkdir ${builddir}


cd ${builddir} && CXX=clang++ CC=clang cmake \
  -DCMAKE_VERBOSE_MAKEFILE=1 \
  -DCMAKE_BUILD_TYPE=Debug \
  -DTINYUSDZ_WITH_OPENSUBDIV=0 \
  -DTINYUSDZ_WITH_AUDIO=0 \
  -DTINYUSDZ_WITH_EXR=0 \
  -DTINYUSDZ_WITH_MODULE_USDA_PARSER=0 \
  -DTINYUSDZ_WITH_MODULE_USDA_WRITER=0 \
  -DTINYUSDZ_WITH_MODULE_USDC_WRITER=0 \
  -DTINYUSDZ_WITH_PYTHON=0 \
  -DTINYUSDZ_WITH_USDOBJ=0 \
  -DTINYUSDZ_WITH_USDVOX=0 \
  -DTINYUSDZ_COMPILE_TIME_TRACE=1 \
  -DSANITIZE_ADDRESS=0 \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  ..

