#!/usr/bin/env python3
"""Generate the UsdPreviewSurface input-type table for the validator.

Reads src/usd-preview-surface-schema.json and emits the initializer entries for
`UsdPreviewSurfaceInputTypes()` into src/usd-preview-surface-inputs.inc, which is
`#include`d inside the std::unordered_map initializer in src/usd-validation.cc.

This makes the schema JSON the single source of truth: the validator's table and
the test fixtures (tests/usda/validation/gen_validation_fixtures.py) are both
derived from it.

Usage:
  python3 scripts/gen-usd-preview-surface-inputs.py            # regenerate the .inc
  python3 scripts/gen-usd-preview-surface-inputs.py --check    # fail if the .inc is stale
"""

import argparse
import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_SCHEMA = os.path.join(REPO_ROOT, "src", "usd-preview-surface-schema.json")
DEFAULT_OUT = os.path.join(REPO_ROOT, "src", "usd-preview-surface-inputs.inc")
SHADER_TYPE = "UsdPreviewSurface"

HEADER = (
    "// SPDX-License-Identifier: Apache 2.0\n"
    "// AUTO-GENERATED by scripts/gen-usd-preview-surface-inputs.py from\n"
    "// src/usd-preview-surface-schema.json. Do not edit by hand; run the script\n"
    "// to regenerate. Included inside the UsdPreviewSurfaceInputTypes() map\n"
    "// initializer in src/usd-validation.cc.\n"
)


def render(schema_path):
    with open(schema_path) as f:
        schema = json.load(f)

    inputs = schema["shaders"][SHADER_TYPE]["inputs"]
    lines = [HEADER]
    for name in sorted(inputs):
        lines.append('{"%s", "%s"},\n' % (name, inputs[name]))
    return "".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--schema", default=DEFAULT_SCHEMA)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if --out is not up to date (do not write)")
    args = ap.parse_args()

    generated = render(args.schema)

    if args.check:
        existing = ""
        if os.path.exists(args.out):
            with open(args.out) as f:
                existing = f.read()
        if existing != generated:
            sys.stderr.write(
                "ERROR: %s is out of date with %s.\n"
                "Run: python3 scripts/gen-usd-preview-surface-inputs.py\n"
                % (os.path.relpath(args.out, REPO_ROOT),
                   os.path.relpath(args.schema, REPO_ROOT)))
            sys.exit(1)
        print("%s is up to date." % os.path.relpath(args.out, REPO_ROOT))
        return

    with open(args.out, "w") as f:
        f.write(generated)
    print("Wrote %s" % os.path.relpath(args.out, REPO_ROOT))


if __name__ == "__main__":
    main()
