<#
.SYNOPSIS
  Set up the Vulkan loader + Khronos validation layers for debugging the
  lusdview / lusdrender Vulkan backends on Windows.

.DESCRIPTION
  Two modes:

    (default, -Prebuilt)  Download the official LunarG Vulkan SDK for Windows
                          (it ships a prebuilt vulkan-1.dll loader AND the
                          VK_LAYER_KHRONOS_validation layer) and unattended-
                          install it to a local directory. This is the
                          recommended path on Windows -- no compiler needed.

    (-FromSource)         git clone + CMake-build Vulkan-Loader and
                          Vulkan-ValidationLayers from KhronosGroup. Slow
                          (pulls SPIRV-Tools/SPIRV-Headers/glslang/robin-hood
                          via the layers' update_deps.py) but works when the
                          prebuilt SDK cannot be used. Needs cmake + ninja +
                          a C++ compiler (e.g. the llvm-mingw / MSVC toolchain).

  After it finishes it prints the environment variables to export so the
  Vulkan loader finds the layer, and a ready-to-run validation command.

.PARAMETER InstallDir
  Where to place the SDK / built artifacts. Default: <repo>\third_party\vulkan.

.PARAMETER Version
  LunarG SDK version (e.g. 1.3.296.0). Default: the latest Windows SDK that
  LunarG advertises. Prebuilt mode only.

.PARAMETER FromSource
  Build the loader + layers from source instead of downloading the SDK.

.PARAMETER Force
  Re-download / rebuild even if an existing install is detected.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File scripts\setup-vulkan-validation.ps1
  # then follow the printed `$env:...` lines, or dot-source the generated
  # activate-vulkan-validation.ps1

.EXAMPLE
  powershell -File scripts\setup-vulkan-validation.ps1 -FromSource -Version 1.3.296.0
#>
[CmdletBinding()]
param(
  [string]$InstallDir,
  [string]$Version = "",
  [switch]$FromSource,
  [switch]$BuildLoader,
  [switch]$Force
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

# Repo root = parent of this script's directory.
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot  = Split-Path -Parent $ScriptDir
if (-not $InstallDir) { $InstallDir = Join-Path $RepoRoot "third_party\vulkan" }

function Write-Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Warn2($msg) { Write-Host "WARN: $msg" -ForegroundColor Yellow }

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null

# ---------------------------------------------------------------------------
# Emit the activation script + final instructions, given the directory that
# contains VkLayer_khronos_validation.json (the "layer manifest dir") and the
# directory that contains vulkan-1.dll (the loader, may be the same).
# ---------------------------------------------------------------------------
function Emit-Activation([string]$LayerManifestDir, [string]$LoaderBinDir, [string]$SdkRoot) {
  $activate = Join-Path $RepoRoot "activate-vulkan-validation.ps1"
  $lines = @(
    "# Auto-generated by scripts/setup-vulkan-validation.ps1 -- dot-source this:",
    "#   . .\activate-vulkan-validation.ps1",
    "`$env:VK_LAYER_PATH = `"$LayerManifestDir`"",
    "`$env:VK_ADD_LAYER_PATH = `"$LayerManifestDir`"",
    "`$env:VK_LOADER_LAYERS_ENABLE = `"VK_LAYER_KHRONOS_validation`""
  )
  if ($SdkRoot) { $lines += "`$env:VULKAN_SDK = `"$SdkRoot`"" }
  if ($LoaderBinDir) { $lines += "`$env:PATH = `"$LoaderBinDir;`" + `$env:PATH" }
  $lines += "Write-Host 'Vulkan validation layer activated (VK_LAYER_KHRONOS_validation).' -ForegroundColor Green"
  Set-Content -Path $activate -Value $lines -Encoding UTF8

  Write-Host ""
  Write-Step "Validation layer ready."
  Write-Host "  layer manifest: $LayerManifestDir"
  if ($LoaderBinDir) { Write-Host "  loader (vulkan-1.dll): $LoaderBinDir" }
  Write-Host ""
  Write-Host "Activate it in your shell with:" -ForegroundColor Green
  Write-Host "  . .\activate-vulkan-validation.ps1"
  Write-Host ""
  Write-Host "Then run lusdview under validation, e.g.:" -ForegroundColor Green
  Write-Host "  .\build-msvc\Release\lusdview.exe --headless --frames 2 --screenshot out.ppm models\cube.usdc"
  Write-Host "Validation errors print to stderr as 'VUID-...' messages (a clean run prints none)."
  Write-Host ""
  Write-Host "For shader-side faults (device loss / corrupt frame) enable GPU-Assisted Validation:" -ForegroundColor Green
  Write-Host "  `$env:VK_LAYER_SETTINGS_PATH = (Resolve-Path .\vk_layer_settings.txt)"
  Write-Host "  (see scripts/setup-vulkan-validation.ps1 header / doc/lusdview.md)"
}

# Locate VkLayer_khronos_validation.json under a root (returns its directory).
function Find-LayerManifest([string]$root) {
  $hit = Get-ChildItem -Path $root -Recurse -Filter "VkLayer_khronos_validation.json" -ErrorAction SilentlyContinue |
         Select-Object -First 1
  if ($hit) { return $hit.DirectoryName }
  return $null
}

# ===========================================================================
# Mode A: prebuilt LunarG Vulkan SDK (default, Windows)
# ===========================================================================
function Setup-Prebuilt {
  if (-not $Version) {
    Write-Step "Querying latest LunarG Windows SDK version..."
    try {
      $j = Invoke-RestMethod -Uri "https://vulkan.lunarg.com/sdk/latest/windows.json" -TimeoutSec 30
      $Version = $j.windows
    } catch {
      throw "Could not query LunarG latest SDK version ($_). Pass -Version x.y.z.w explicitly, or use -FromSource."
    }
  }
  Write-Step "LunarG Vulkan SDK version: $Version"

  # The LunarG (Qt IFW) installer always elevates -- it refuses to run from a
  # plain command line ("Cannot elevate access rights..."). So install to the
  # standard C:\VulkanSDK\<ver> via an elevated child process (a UAC prompt
  # appears once). An admin install also registers the layer manifests in the
  # registry, so the loader auto-discovers VK_LAYER_KHRONOS_validation.
  $sdkRoot = if ($InstallDir -and (Split-Path $InstallDir -Leaf) -ne 'vulkan') {
               Join-Path $InstallDir "VulkanSDK\$Version"
             } else { "C:\VulkanSDK\$Version" }
  $existing = if (Test-Path $sdkRoot) { Find-LayerManifest $sdkRoot } else { $null }
  if ($existing -and -not $Force) {
    Write-Step "SDK already present (use -Force to reinstall)."
    Emit-Activation $existing (Join-Path $sdkRoot "Bin") $sdkRoot
    return
  }

  $installer = Join-Path $InstallDir "vulkansdk-windows-X64-$Version.exe"
  $url = "https://sdk.lunarg.com/sdk/download/$Version/windows/vulkansdk-windows-X64-$Version.exe"
  if ((-not (Test-Path $installer)) -or $Force) {
    Write-Step "Downloading $url"
    $old = $ProgressPreference; $ProgressPreference = 'SilentlyContinue'
    try { Invoke-WebRequest -Uri $url -OutFile $installer -TimeoutSec 1800 }
    finally { $ProgressPreference = $old }
  } else {
    Write-Step "Using cached installer: $installer"
  }

  $len = (Get-Item $installer).Length
  if ($len -lt 10MB) { throw "Downloaded installer looks too small ($len bytes) -- download likely failed." }

  Write-Step "Installing to $sdkRoot (elevated -- approve the UAC prompt)"
  # Qt IFW unattended flags. --confirm-command install with a component id keeps
  # the install minimal but the validation layer lives in com.lunarg.vulkan.core.
  $iargs = @("--root", $sdkRoot, "--accept-licenses", "--default-answer",
             "--confirm-command", "install")
  try {
    $p = Start-Process -FilePath $installer -ArgumentList $iargs -Verb RunAs -Wait -PassThru
    if ($p.ExitCode -ne 0) { Write-Warn2 "Installer exit code $($p.ExitCode); checking for the layer anyway..." }
  } catch {
    throw "Could not launch the installer elevated ($_). Run this script from an elevated PowerShell, or run manually:`n  $installer $($iargs -join ' ')"
  }

  $manifest = Find-LayerManifest $sdkRoot
  if (-not $manifest) {
    throw "Install finished but VkLayer_khronos_validation.json was not found under $sdkRoot. Try -FromSource, or install the SDK manually from https://vulkan.lunarg.com/sdk/home"
  }
  $loaderBin = Join-Path $sdkRoot "Bin"
  if (-not (Test-Path (Join-Path $loaderBin "vulkan-1.dll"))) { $loaderBin = $manifest }
  Emit-Activation $manifest $loaderBin $sdkRoot
}

# Import the MSVC build environment (cl.exe, libs) into this PS session by
# running vcvars64.bat and copying back the variables it sets. Needed because a
# Ninja build of the loader/layers requires a C/C++ compiler in the env.
function Import-VcVars {
  $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
  if (-not (Test-Path $vswhere)) { Write-Warn2 "vswhere not found; assuming a compiler is already on PATH."; return }
  $vs = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
  if (-not $vs) { Write-Warn2 "No VS C++ toolset found; assuming a compiler is already on PATH."; return }
  $vcvars = Join-Path $vs "VC\Auxiliary\Build\vcvars64.bat"
  if (-not (Test-Path $vcvars)) { Write-Warn2 "vcvars64.bat not found under $vs."; return }
  Write-Step "Importing MSVC environment from $vcvars"
  cmd /c "`"$vcvars`" >nul 2>&1 && set" | ForEach-Object {
    if ($_ -match '^([^=]+)=(.*)$') { Set-Item -Path ("env:" + $matches[1]) -Value $matches[2] }
  }
}

# ===========================================================================
# Mode B: build the loader + validation layers from source
# ===========================================================================
function Setup-FromSource {
# Return the path to a Ninja >= 1.11 (needed for C++20 modules in recent
# Vulkan-Headers). Downloads ninja 1.12 into $InstallDir if the one on PATH is
# too old. Returns the directory to prepend to PATH (or $null if PATH ninja ok).
function Ensure-Ninja {
  $ng = Get-Command ninja -ErrorAction SilentlyContinue
  if ($ng) {
    $v = (& $ng.Source --version) 2>$null
    if ($v -match '^(\d+)\.(\d+)') {
      if ([int]$matches[1] -gt 1 -or ([int]$matches[1] -eq 1 -and [int]$matches[2] -ge 11)) { return $null }
    }
    Write-Warn2 "ninja $v is too old for C++20 modules (need >= 1.11); fetching 1.12.1."
  }
  $ndir = Join-Path $InstallDir "ninja"
  if (-not (Test-Path (Join-Path $ndir "ninja.exe"))) {
    New-Item -ItemType Directory -Force -Path $ndir | Out-Null
    $zip = Join-Path $ndir "ninja-win.zip"
    $old = $ProgressPreference; $ProgressPreference='SilentlyContinue'
    try { Invoke-WebRequest -Uri "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-win.zip" -OutFile $zip -TimeoutSec 300 }
    finally { $ProgressPreference = $old }
    Expand-Archive -Path $zip -DestinationPath $ndir -Force
  }
  return $ndir
}

# Pick a clean CPython for update_deps.py. The rez-wrapped 'python' on PATH and
# the Windows Store 'python3' stub both misbehave for the deps build; prefer a
# real standalone interpreter (VS shared Python, py launcher, etc.).
function Find-CleanPython {
  $cands = @()
  $vsroot = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Shared"
  if (Test-Path $vsroot) {
    $cands += Get-ChildItem -Path $vsroot -Filter "python.exe" -Recurse -ErrorAction SilentlyContinue | ForEach-Object { $_.FullName }
  }
  foreach ($pv in @("-3.12","-3.11","-3.10","-3")) {
    $py = Get-Command py -ErrorAction SilentlyContinue
    if ($py) { $p = (& py $pv -c "import sys;print(sys.executable)" 2>$null); if ($p -and (Test-Path $p)) { $cands += $p } }
  }
  $onpath = Get-Command python -ErrorAction SilentlyContinue
  if ($onpath -and $onpath.Source -notmatch 'rez|WindowsApps') { $cands += $onpath.Source }
  foreach ($c in $cands) { if ($c -and (Test-Path $c)) { return $c } }
  throw "No clean CPython found for update_deps.py (rez/Store python won't work). Install Python 3.x."
}

function Setup-FromSource {
  Import-VcVars
  foreach ($tool in @("git", "cmake")) {
    if (-not (Get-Command $tool -ErrorAction SilentlyContinue)) { throw "-FromSource needs '$tool' on PATH." }
  }
  $ninjaDir = Ensure-Ninja
  if ($ninjaDir) { $env:PATH = "$ninjaDir;$env:PATH" }
  $py = Find-CleanPython
  Write-Step "Using python: $py"

  # Match the layer release to a known-good SDK tag; default to our vendored
  # header version (Vulkan-Headers VK_HEADER_VERSION 296 => vulkan-sdk-1.3.296.0).
  $tag = if ($Version) { "vulkan-sdk-$Version" } else { "vulkan-sdk-1.3.296.0" }
  Write-Step "Building Vulkan-ValidationLayers at tag $tag"

  $src = Join-Path $InstallDir "src"
  New-Item -ItemType Directory -Force -Path $src | Out-Null

  # The validation layer is the goal. The Vulkan *loader* (vulkan-1.dll) is
  # already present on any machine with a Vulkan driver, and lusdview loads it
  # at runtime via volk -- so we do NOT build the loader here (its UPDATE_DEPS
  # path is an extra failure point). Pass -BuildLoader to build it anyway.
  if ($BuildLoader) {
    $loaderSrc = Join-Path $src "Vulkan-Loader"
    if (-not (Test-Path $loaderSrc)) { git clone --branch $tag --depth 1 https://github.com/KhronosGroup/Vulkan-Loader.git $loaderSrc }
    $loaderBuild = Join-Path $loaderSrc "build"
    cmake -S $loaderSrc -B $loaderBuild -G Ninja -DCMAKE_BUILD_TYPE=Release -DUPDATE_DEPS=ON -DUPDATE_DEPS_DIR="$InstallDir\loader-deps" -DPYTHON_EXECUTABLE="$py" -DCMAKE_INSTALL_PREFIX="$InstallDir\install"
    cmake --build $loaderBuild --config Release
    cmake --install $loaderBuild --config Release
  }

  $vvlSrc = Join-Path $src "Vulkan-ValidationLayers"
  if (-not (Test-Path $vvlSrc)) { git clone --branch $tag --depth 1 https://github.com/KhronosGroup/Vulkan-ValidationLayers.git $vvlSrc }
  Write-Step "Fetching layer dependencies (Vulkan-Headers, SPIRV-Tools, glslang, robin-hood, mimalloc). Slow (~5-10 min)."
  & $py (Join-Path $vvlSrc "scripts\update_deps.py") --dir (Join-Path $vvlSrc "external") --arch x64 --config release --generator Ninja
  if ($LASTEXITCODE -ne 0) { throw "update_deps.py failed (exit $LASTEXITCODE)." }
  $vvlBuild = Join-Path $vvlSrc "build"
  cmake -S $vvlSrc -B $vvlBuild -G Ninja -C (Join-Path $vvlSrc "external\helper.cmake") `
        -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX="$InstallDir\install"
  if ($LASTEXITCODE -ne 0) { throw "validation-layer configure failed." }
  cmake --build $vvlBuild --config Release
  if ($LASTEXITCODE -ne 0) { throw "validation-layer build failed." }
  cmake --install $vvlBuild --config Release

  $manifest = Find-LayerManifest "$InstallDir\install"
  if (-not $manifest) { $manifest = Find-LayerManifest $vvlBuild }
  if (-not $manifest) { throw "Built the layers but could not locate VkLayer_khronos_validation.json." }
  $loaderBin = Join-Path "$InstallDir\install" "bin"
  if (-not (Test-Path (Join-Path $loaderBin "vulkan-1.dll"))) { $loaderBin = $null }  # use the system loader
  Emit-Activation $manifest $loaderBin "$InstallDir\install"
}

# ===========================================================================
if ($FromSource) { Setup-FromSource } else { Setup-Prebuilt }
