#!/usr/bin/env bash
# Build Khronos Vulkan ValidationLayers from source for optional local testing.
set -euo pipefail

if [[ "$(uname -s)" != "Linux" ]]; then
  echo "ERROR: this setup script currently supports Linux only" >&2
  exit 1
fi

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
install_root="${VVL_INSTALL_ROOT:-$root/build_vulkan_validation}"
jobs="${VVL_JOBS:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4)}"

for tool in git cmake ninja python3; do
  command -v "$tool" >/dev/null 2>&1 || {
    echo "ERROR: required tool not found: $tool" >&2
    exit 1
  }
done

# Prefer the installed Vulkan development package version. Override VVL_TAG
# when the loader/SDK requires another Khronos release.
sdk_version="${VVL_VERSION:-}"
if [[ -z "$sdk_version" ]] && command -v pkg-config >/dev/null 2>&1; then
  sdk_version="$(pkg-config --modversion vulkan 2>/dev/null || true)"
fi
sdk_version="${sdk_version:-1.3.275}"
tag="${VVL_TAG:-vulkan-sdk-${sdk_version}.0}"

src="$install_root/src/Vulkan-ValidationLayers"
deps="$install_root/deps"
build="$install_root/build"
prefix="$install_root/install"
mkdir -p "$install_root/src" "$deps" "$prefix"

if [[ ! -d "$src/.git" ]]; then
  git clone --branch "$tag" --depth 1 \
    https://github.com/KhronosGroup/Vulkan-ValidationLayers.git "$src"
else
  git -C "$src" fetch --depth 1 origin "refs/tags/$tag:refs/tags/$tag"
  git -C "$src" checkout --detach "$tag"
fi

python3 "$src/scripts/update_deps.py" --dir "$deps" --arch x64 \
  --config release --generator Ninja

cmake -S "$src" -B "$build" -G Ninja -C "$deps/helper.cmake" \
  -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF \
  -DCMAKE_INSTALL_PREFIX="$prefix"
cmake --build "$build" -j"$jobs"
cmake --install "$build"

manifest="$(find "$prefix" "$build" -name VkLayer_khronos_validation.json \
  -print -quit)"
if [[ -z "$manifest" ]]; then
  echo "ERROR: build completed but validation-layer manifest was not found" >&2
  exit 1
fi
layer_dir="$(dirname "$manifest")"
activation="$install_root/activate-vulkan-validation.sh"
{
  printf '# Generated by scripts/setup-vulkan-validation-linux.sh\n'
  printf 'export VK_LAYER_PATH=%q\n' "$layer_dir"
  printf 'export VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation\n'
} >"$activation"

echo "Vulkan ValidationLayers $tag installed in $prefix"
echo "Activate with: source $activation"
echo "$layer_dir"
