/* Auto-generated by scripts/embed_binary_resource.py. */
#ifndef HACK_REGULAR_TTF_H
#define HACK_REGULAR_TTF_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

const unsigned char *lui_embedded_font_data(void);
size_t lui_embedded_font_size(void);

#ifdef __cplusplus
}
#endif

#endif /* HACK_REGULAR_TTF_H */
