"""USDC quaternion wire-format fence.

pxr's USDC wire layout for `GfQuat<T>` is `(imag.x, imag.y, imag.z, real)`
— matching the `{_imaginary, _real}` member order. tinyusdz historically
emitted `(real, imag.x, imag.y, imag.z)`, which made tinyusdz↔tinyusdz
scalar quats *appear* to round-trip (both writer and reader agreed on
the wrong order) while array quats produced shuffled components and
files were unreadable by pxr.

These tests fence:
  1. Scalar quat roundtrip authored value matches loaded value.
  2. Array quat roundtrip authored values match loaded values
     (this regressed silently before the fix).
  3. The shipped fixture `timesamples-scalar-quatf-001.usdc` (authored
     by pxr usdcat) reads with the source quaternion components, not
     a circular rotation of them.
"""
import os
import struct

import tinyusdz


REPO_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", ".."))


def test_scalar_quatf_roundtrip(tmp_path):
    s = tinyusdz.Stage()
    p = tinyusdz.Prim("Xform", name="X")
    p.set_attribute("q", (1.0, 0.0, 0.0, 0.0), dtype="quatf")  # identity
    s.add_root_prim(p)
    out = tmp_path / "q.usdc"
    s.save(str(out))
    s2 = tinyusdz.load(str(out))
    assert "quatf q = (1, 0, 0, 0)" in s2.export_to_string()


def test_quatf_array_roundtrip(tmp_path):
    """Pre-fix this would silently shuffle components inside each
    element because the writer wrote (real, imag) per element while
    the reader memcpy'd raw bytes into the {imag, real} struct."""
    s = tinyusdz.Stage()
    p = tinyusdz.Prim("Xform", name="X")
    p.set_attribute("q", [(1.0, 0.0, 0.0, 0.0),
                          (0.5, 0.5, 0.5, 0.5)], dtype="quatf[]")
    s.add_root_prim(p)
    out = tmp_path / "qa.usdc"
    s.save(str(out))
    s2 = tinyusdz.load(str(out))
    txt = s2.export_to_string()
    assert "(1, 0, 0, 0)" in txt
    assert "(0.5, 0.5, 0.5, 0.5)" in txt


def test_pxr_authored_quatf_timesamples_fixture():
    """The shipped fixture was generated by pxr usdcat; its bytes are
    pxr wire format. Reading it must give the same component values
    as the source USDA (real, imag.x, imag.y, imag.z print order)."""
    p = os.path.join(
        REPO_ROOT, "tests", "usdc", "timesamples-scalar-quatf-001.usdc")
    if not os.path.exists(p):
        return  # fixture not present in this checkout
    s = tinyusdz.load(p)
    txt = s.export_to_string()
    assert "0: (1, 0, 0, 0)" in txt
    assert "10: (0.707, 0.707, 0, 0)" in txt
    assert "20: (0, 1, 0, 0)" in txt


def test_quatd_roundtrip(tmp_path):
    s = tinyusdz.Stage()
    p = tinyusdz.Prim("Xform", name="X")
    p.set_attribute("q", (0.7071, 0.0, 0.7071, 0.0), dtype="quatd")
    s.add_root_prim(p)
    out = tmp_path / "qd.usdc"
    s.save(str(out))
    s2 = tinyusdz.load(str(out))
    assert "(0.7071, 0, 0.7071, 0)" in s2.export_to_string()


def test_pxr_can_read_tinyusdz_quat_output(tmp_path):
    """Sanity: the bytes tinyusdz writes for a quatf must be in pxr
    wire layout (imag.x, imag.y, imag.z, real). We can verify without
    invoking pxr by inspecting the raw USDC bytes."""
    s = tinyusdz.Stage()
    p = tinyusdz.Prim("Xform", name="X")
    # real=1, imag=(0.25, 0.5, 0.75) — distinct components so order
    # mistakes are obvious.
    p.set_attribute("q", (1.0, 0.25, 0.5, 0.75), dtype="quatf")
    s.add_root_prim(p)
    out = tmp_path / "q.usdc"
    s.save(str(out))
    data = out.read_bytes()
    # Find the 16-byte payload (4 floats matching 0.25, 0.5, 0.75, 1.0).
    needle = struct.pack("<ffff", 0.25, 0.5, 0.75, 1.0)
    assert needle in data, "expected pxr wire order (imag.x, imag.y, imag.z, real) in USDC bytes"