// SPDX-License-Identifier: Apache 2.0
// Copyright 2026 - Present Light Transport Entertainment Inc.
//
/// @file urdf-to-usd.hh
/// @brief Build USD Physics + MuJoCo stages from URDF-derived JSON.
#pragma once

#include <cstdint>
#include <map>
#include <string>
#include <vector>

namespace tinyusdz {

class Stage;

namespace tydra {

struct URDFMeshBuffer {
  std::vector<float> positions;
  std::vector<float> normals;
  std::vector<float> uvs;
  std::vector<int32_t> indices;
};

/// Build a USD stage from a compact URDF export payload.
///
/// The JSON payload is intentionally renderer-neutral so it can be generated by
/// browser tools or native URDF frontends:
/// - links[].visuals/collisions[].geometry contain positions, indices, normals,
///   and UVs.
/// - links[].collisions[].shape may contain native USD collision shapes
///   (`box`, `sphere`, `cylinder`, `capsule`, or `plane`) when tessellation is
///   not requested by the frontend.
/// - joints[] contain URDF joint metadata, axes, limits, dynamics, and link
///   names.
///
/// The generated stage authors both standard UsdPhysics and MuJoCo API schema
/// properties where TinyUSDZ has schema support.
bool ConvertURDFJsonToUSDStage(
    const std::string &robot_json,
    Stage *stage,
    std::string *warn = nullptr,
    std::string *err = nullptr);

bool ConvertURDFJsonToUSDStage(
    const std::string &robot_json,
    const std::map<std::string, URDFMeshBuffer> *mesh_buffers,
    Stage *stage,
    std::string *warn = nullptr,
    std::string *err = nullptr);

}  // namespace tydra
}  // namespace tinyusdz
