# SPDX-License-Identifier: Apache-2.0
"""Type stubs for the tinyusdz._core extension."""
from typing import Any, Iterator, Optional, Sequence, Union

__version__: str

Matrix4 = tuple[
    tuple[float, float, float, float],
    tuple[float, float, float, float],
    tuple[float, float, float, float],
    tuple[float, float, float, float],
]
Value = Any  # bool | int | float | str | tuple | Array | ValueBlock | dict

class UsdError(Exception): ...
class UsdParseError(UsdError, ValueError): ...
class UsdIoError(UsdError, OSError): ...
class StaleHandleError(UsdError): ...

class _ValueBlockType:
    def __repr__(self) -> str: ...

ValueBlock: _ValueBlockType

class Array:
    """Zero-copy view of an array-valued attribute / render buffer.

    Interops with numpy without copying: ``numpy.asarray(array)``.
    """

    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def dtype(self) -> str: ...
    @property
    def type_name(self) -> str: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def __array_interface__(self) -> dict[str, Any]: ...
    def memoryview(self) -> memoryview: ...
    def tolist(self) -> list[Any]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...

class TimeSamples:
    @property
    def times(self) -> tuple[float, ...]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> tuple[float, Value]: ...
    def __iter__(self) -> Iterator[tuple[float, Value]]: ...

class Attribute:
    @property
    def name(self) -> str: ...
    @property
    def type_name(self) -> str: ...
    @property
    def is_array(self) -> bool: ...
    @property
    def is_custom(self) -> bool: ...
    @property
    def is_uniform(self) -> bool: ...
    @property
    def is_connection(self) -> bool: ...
    @property
    def has_timesamples(self) -> bool: ...
    @property
    def connections(self) -> tuple[str, ...]: ...
    @property
    def timesamples(self) -> TimeSamples: ...
    @property
    def interpolation(self) -> Optional[str]: ...
    @property
    def custom_data(self) -> dict[str, Any]: ...
    def get(self, time: Optional[float] = None,
            interpolation: str = "linear") -> Value: ...
    def eval(self, time: float = 0.0) -> Value: ...
    def set(self, value: Any, type: Optional[str] = None,
            time: Optional[float] = None) -> None: ...
    def block(self) -> None: ...
    def connect(self, target_path: str) -> None: ...
    def metadata(self, key: str) -> Optional[Value]: ...
    def set_metadata(self, key: str, value: Any) -> None: ...

class Relationship:
    @property
    def name(self) -> str: ...
    @property
    def targets(self) -> tuple[str, ...]: ...
    def add_target(self, path: str) -> None: ...
    def set_targets(self, paths: Sequence[str]) -> None: ...
    def remove(self) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> str: ...
    def __iter__(self) -> Iterator[str]: ...

class VariantSet:
    @property
    def name(self) -> str: ...
    @property
    def names(self) -> tuple[str, ...]: ...
    selection: Optional[str]
    def add_variant(self, name: str) -> None: ...

class VariantSets:
    def names(self) -> tuple[str, ...]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, name: str) -> VariantSet: ...
    def __contains__(self, name: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...

class Prim:
    @property
    def name(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def type_name(self) -> str: ...
    @property
    def specifier(self) -> str: ...
    @property
    def active(self) -> bool: ...
    @property
    def kind(self) -> Optional[str]: ...
    @property
    def parent(self) -> Optional["Prim"]: ...
    @property
    def children(self) -> tuple["Prim", ...]: ...
    @property
    def attributes(self) -> tuple[str, ...]: ...
    @property
    def relationships(self) -> tuple[str, ...]: ...
    @property
    def variant_sets(self) -> VariantSets: ...
    @property
    def custom_data(self) -> dict[str, Any]: ...
    @property
    def asset_info(self) -> dict[str, Any]: ...
    def get(self, name: str, default: Any = None,
            time: Optional[float] = None) -> Value: ...
    def attribute(self, name: str) -> Attribute: ...
    def relationship(self, name: str) -> Relationship: ...
    def child(self, name: str) -> "Prim": ...
    def metadata(self, key: str) -> Optional[Value]: ...
    def local_transform(self, time: float = 0.0) -> Matrix4: ...
    def world_transform(self, time: float = 0.0) -> Matrix4: ...
    def set(self, name: str, value: Any, type: Optional[str] = None,
            time: Optional[float] = None, uniform: bool = False,
            custom: bool = False) -> None: ...
    def set_metadata(self, key: str, value: Any) -> None: ...
    def add_reference(self, asset_path: str,
                      prim_path: Optional[str] = None) -> None: ...
    def add_payload(self, asset_path: str,
                    prim_path: Optional[str] = None) -> None: ...
    def add_inherit(self, prim_path: str) -> None: ...
    def add_specialize(self, prim_path: str) -> None: ...
    def add_relationship(self, name: str, targets: Sequence[str]) -> None: ...
    def add_variant_set(self, name: str) -> None: ...
    def remove_property(self, name: str) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator["Prim"]: ...
    def __contains__(self, name: str) -> bool: ...
    def __getitem__(self, name: str) -> Value: ...

class Stage:
    @classmethod
    def create(cls) -> "Stage": ...
    def close(self) -> None: ...
    def __enter__(self) -> "Stage": ...
    def __exit__(self, *exc: Any) -> None: ...
    @property
    def root_prims(self) -> tuple[Prim, ...]: ...
    @property
    def pseudo_root(self) -> Prim: ...
    @property
    def default_prim(self) -> Optional[Prim]: ...
    @property
    def default_prim_path(self) -> Optional[str]: ...
    up_axis: str
    meters_per_unit: float
    time_codes_per_second: float
    start_time: float
    end_time: float
    frames_per_second: float
    doc: str
    @property
    def sublayers(self) -> tuple[str, ...]: ...
    @property
    def custom_layer_data(self) -> dict[str, Any]: ...
    @property
    def stats(self) -> dict[str, int]: ...
    def prim_at(self, path: str) -> Prim: ...
    def get_prim_at(self, path: str, default: Any = None) -> Optional[Prim]: ...
    def prims_of_type(self, type_name: str) -> list[Prim]: ...
    def get_metadata(self, key: str) -> Optional[Value]: ...
    def set_metadata(self, key: str, value: Any) -> None: ...
    def set_default_prim(self, prim_name: str) -> None: ...
    def add_sublayer(self, asset_path: str) -> None: ...
    def warnings(self) -> str: ...
    def define_prim(self, path: str, type_name: Optional[str] = None,
                    specifier: str = "def") -> Prim: ...
    def override_prim(self, path: str) -> Prim: ...
    def remove_prim(self, path: str) -> None: ...
    def save(self, path: str, format: Optional[str] = None) -> None: ...
    def export_usda(self) -> str: ...
    def export_usdc(self) -> bytes: ...
    def flattened(self) -> "Stage": ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Prim]: ...
    def __contains__(self, path: str) -> bool: ...

# ---- tydra render types ----

class RenderMesh:
    name: str
    prim_path: str
    point_count: int
    face_count: int
    material_id: int
    primvar_count: int
    blend_shape_count: int
    skeleton_id: int
    is_triangulated: bool
    has_skin: bool
    points: Optional[Array]
    face_vertex_counts: Optional[Array]
    face_vertex_indices: Optional[Array]
    triangulated_indices: Optional[Array]
    normals: Optional[Array]
    tangents: Optional[Array]
    texcoords0: Optional[Array]
    texcoords1: Optional[Array]
    colors: Optional[Array]
    joint_indices: Optional[Array]
    joint_weights: Optional[Array]
    bbox: Optional[tuple[tuple[float, float, float],
                         tuple[float, float, float]]]
    subsets: list[tuple[int, int, int]]
    def primvar(self, index: int) -> dict[str, Any]: ...
    def blend_shape(self, index: int) -> dict[str, Any]: ...

class RenderTexture:
    name: str
    asset_path: str
    image_id: int
    wrap_s: str
    wrap_t: str
    uv_offset: tuple[float, float]
    uv_scale: tuple[float, float]
    uv_rotation: float
    image: Optional["RenderImage"]

class RenderImage:
    name: str
    resolved_path: str
    width: int
    height: int
    channels: int
    is_loaded: bool
    data: Optional[Array]

class RenderMaterial:
    name: str
    prim_path: str
    shader: Optional[str]
    double_sided: bool
    alpha_mode: str
    alpha_cutoff: float
    def param(self, name: str) -> Union[tuple[float, float, float, float],
                                        RenderTexture, None]: ...

class RenderNode:
    name: str
    prim_path: str
    type: str
    visible: bool
    data_id: int
    parent_id: int
    local_transform: Matrix4
    world_transform: Matrix4
    children: tuple["RenderNode", ...]

class RenderLight:
    name: str
    prim_path: str
    type: str
    color: tuple[float, float, float]
    intensity: float
    exposure: float
    transform: Matrix4

class RenderCamera:
    name: str
    prim_path: str
    type: str
    focal_length: float
    horizontal_aperture: float
    vertical_aperture: float
    near_clip: float
    far_clip: float
    fov_x: float
    fov_y: float
    transform: Matrix4

class RenderScene:
    meshes: tuple[RenderMesh, ...]
    materials: tuple[RenderMaterial, ...]
    textures: tuple[RenderTexture, ...]
    images: tuple[RenderImage, ...]
    nodes: tuple[RenderNode, ...]
    lights: tuple[RenderLight, ...]
    cameras: tuple[RenderCamera, ...]
    root_nodes: tuple[RenderNode, ...]
    default_prim: str
    up_axis: str
    meters_per_unit: float
    start_time: float
    end_time: float
    def mesh_by_path(self, prim_path: str) -> Optional[RenderMesh]: ...
    def material_by_path(self, prim_path: str) -> Optional[RenderMaterial]: ...
    def warnings(self) -> list[str]: ...

# ---- module functions ----

def load(path: str, *, format: Optional[str] = None, composed: bool = True,
         variants: Optional[dict[str, str]] = None,
         load_payloads: bool = True, max_memory: int = 0) -> Stage: ...
def loads(usda_text: str) -> Stage: ...
def load_bytes(data: Union[bytes, bytearray, memoryview], *,
               format: Optional[str] = None,
               max_memory: int = 0) -> Stage: ...
def flatten_file(src: str, dst: str, *, max_memory: int = 0) -> None: ...
def to_render_scene(stage: Stage, *, triangulate: bool = True,
                    compute_normals: bool = True,
                    compute_tangents: bool = False,
                    load_textures: bool = True, time: float = 0.0,
                    duplicate_instance_meshes: bool = False) -> RenderScene: ...
def type_from_name(usd_type_name: str) -> int: ...
def type_name(type_id: int) -> str: ...
def _set_normalizer(fn: Any) -> None: ...
