#pragma once

void tydra_connection_validation_test(void);
void tydra_inplace_conversion_guard_test(void);
void tydra_geommesh_property_accessor_test(void);
void tydra_memory_tracking_test(void);
void tydra_scene_access_helper_test(void);
void tydra_shader_scene_access_test(void);
void tydra_skel_scene_access_test(void);
void tydra_blendshape_resolution_test(void);
void tydra_material_binding_validation_test(void);
void tydra_texture_loader_policy_test(void);
void tydra_envmap_loader_policy_test(void);
void tydra_geometry_light_validation_test(void);
void tydra_mesh_fallback_policy_test(void);
void tydra_progress_cancellation_test(void);
void tydra_skel_animation_validation_test(void);
void tydra_skin_binding_validation_test(void);
void tydra_value_clip_animation_conversion_test(void);
void tydra_value_clip_animation_resample_test(void);
void tydra_value_clip_animation_retime_test(void);
void tydra_value_clip_animation_primpath_test(void);
void tydra_value_clip_animation_fallback_test(void);
void tydra_value_clip_animation_custom_property_test(void);
