// SPDX-License-Identifier: Apache 2.0

#pragma once

void usd_validation_valid_core_schema_test(void);
void usd_validation_invalid_default_prim_test(void);
void usd_validation_invalid_collection_rule_test(void);
void usd_validation_invalid_color_space_test(void);
void usd_validation_layer_metadata_test(void);
void usd_validation_xformop_order_test(void);
void usd_validation_xformop_order_gated_test(void);
void usd_validation_nested_gprim_test(void);
void usd_validation_shader_encapsulation_test(void);
void usd_validation_material_binding_test(void);
void usd_validation_preview_surface_test(void);
void usd_validation_material_output_connection_test(void);
void usd_validation_uv_texture_test(void);
void usd_validation_primvar_reader_test(void);
void usd_validation_preview_surface_range_test(void);
void usd_validation_usdskel_test(void);
void usd_validation_materialx_test(void);
void usd_validation_composition_arcs_test(void);
void usd_validation_report_format_test(void);
void usd_validation_group_gating_test(void);
void usd_validation_mesh_topology_test(void);
void usd_validation_geom_subset_indices_test(void);
void usd_validation_primvar_indices_metadata_test(void);
void usd_validation_usdc_crate_test(void);
void usd_validation_validate_usd_memory_entrypoint_test(void);
void usd_validation_usdskel_animation_timesamples_test(void);
void usd_validation_blendshape_test(void);
void usd_validation_value_clips_test(void);
void usd_validation_metadata_semantics_test(void);
void usd_validation_geom_common_metadata_test(void);
void usd_validation_geom_primitives_test(void);
void usd_validation_geom_points_curves_test(void);
void usd_validation_point_instancer_test(void);
void usd_validation_camera_test(void);
void usd_validation_lux_light_test(void);
void usd_validation_physics_test(void);
void usd_validation_physics_inertia_and_joint_transform_test(void);
void usd_validation_physics_mjc_extension_test(void);
void usd_validation_physics_newton_extension_test(void);
void usd_validation_physics_preliminary_test(void);
void usd_validation_relationship_bind_material_as_metadata_test(void);
