#ifdef _MSC_VER
#define NOMINMAX
#endif

#include "acutest.h"

#include "unit-ascii-parse.h"
#include "unit-prim-types.h"
#include "unit-primvar.h"
#include "unit-pathutil.h"
#include "unit-value-types.h"
#include "unit-xform.h"
#include "unit-customdata.h"
#include "unit-handle-allocator.h"
#include "unit-math.h"
#include "unit-ioutil.h"
#include "unit-strutil.h"
#include "unit-timesamples.h"
#include "unit-fp-parse-print.h"
#include "unit-pprint.h"
#include "unit-materialx.h"
#include "unit-task-queue.h"
#include "unit-tydra.h"
//#include "unit-dedup.h"  // Temporarily disabled - needs API updates
#include "unit-crate-writer.h"
#include "unit-stage.h"
#include "unit-tiny-container.h"
#include "unit-usda-roundtrip.h"
#include "unit-usdc-reconstruct.h"
#include "unit-half-roundtrip.h"
#include "unit-prim-reconstruct.h"
#include "unit-composition.h"
#include "unit-usda-reader.h"
#include "unit-usdc-reader.h"
// Phase 0A: feat tests merged into unit suite
#include "unit-value-view.h"
#include "unit-typed-array-view.h"
#include "unit-typed-array-timesamples.h"
// Phase 1: composition arcs
#include "unit-composition-arcs.h"
// Phase 1b: DAG-based composition graph
#include "unit-composition-graph.h"
// Phase 2: layer API
#include "unit-layer.h"
// Phase 3: primspec and prim API
#include "unit-primspec.h"
#include "unit-prim-api.h"
// Phase 4: USDA writer
#include "unit-usda-writer.h"
// Phase 5: Tydra end-to-end + shader
#include "unit-tydra-renderscene.h"
#include "unit-tydra-shader.h"
// Phase 6: security
#include "unit-security.h"
// Phase 7: USDZ writer
#include "unit-usdz-writer.h"
#include "unit-usdc-writer.h"
#include "unit-usd-validation.h"
// Physics + MuJoCo
#include "unit-physics.h"
// IK solver
#include "unit-ik.h"

#if defined(TINYUSDZ_WITH_PXR_COMPAT_API)
#include "unit-pxr-compat-api.h"
#endif



TEST_LIST = {
  { "ascii_parse_int64_valid_test", ascii_parse_int64_valid_test },
  { "ascii_parse_int64_excessive_digits_test", ascii_parse_int64_excessive_digits_test },
  { "ascii_parse_uint64_valid_test", ascii_parse_uint64_valid_test },
  { "ascii_parse_uint64_excessive_digits_test", ascii_parse_uint64_excessive_digits_test },
  { "ascii_parse_string_array_test", ascii_parse_string_array_test },
  { "ascii_parse_array_comments_int_test", ascii_parse_array_comments_int_test },
  { "ascii_parse_array_comments_float_test", ascii_parse_array_comments_float_test },
  { "ascii_parse_array_comments_double_test", ascii_parse_array_comments_double_test },
  { "ascii_parse_array_comments_matrix4d_test", ascii_parse_array_comments_matrix4d_test },
  { "ascii_parse_array_comments_token_test", ascii_parse_array_comments_token_test },
  { "ascii_parse_array_comments_quatf_test", ascii_parse_array_comments_quatf_test },
  { "prim_type_test", prim_type_test },
  { "prim_add_test", prim_add_test },
  { "prim_element_name_test", prim_element_name_test },
  { "primvar_test", primvar_test },
  { "value_types_test", value_types_test },
  { "role_type_cast_test", role_type_cast_test },
  { "value_types_typed_array_memory_test", value_types_typed_array_memory_test },
  { "xformOp_test", xformOp_test },
  { "rotation_order_quat_vs_matrix_test", rotation_order_quat_vs_matrix_test },
  { "rotation_order_distinct_test", rotation_order_distinct_test },
  { "rotation_order_inverted_test", rotation_order_inverted_test },
  { "single_axis_rotation_test", single_axis_rotation_test },
  { "customdata_test", customdata_test },
  { "handle_allocator_test", handle_allocator_test },
  { "math_cos_pi_test", math_cos_pi_test },
  { "math_sin_pi_test", math_sin_pi_test },
  { "math_sin_cos_pi_test", math_sin_cos_pi_test },
  { "quat_to_quaternion_test", quat_to_quaternion_test },
  { "quat_to_matrix_roundtrip_test", quat_to_matrix_roundtrip_test },
  { "quat_operator_bracket_test", quat_operator_bracket_test },
  { "quat_decompose_roundtrip_test", quat_decompose_roundtrip_test },
  { "pathutil_test", pathutil_test },
  { "ioutil_test", ioutil_test },
  { "strutil_test", strutil_test },
  { "tinystring_test", tinystring_test },
  { "parse_int_test", parse_int_test },
  { "fp_string_conversion_test", fp_string_conversion_test },
  { "timesamples_test", timesamples_test },
  { "fp_roundtrip_basic_test", fp_roundtrip_basic_test },
  { "fp_roundtrip_edge_cases_test", fp_roundtrip_edge_cases_test },
  { "fp_roundtrip_special_values_test", fp_roundtrip_special_values_test },
  { "fp_roundtrip_precision_test", fp_roundtrip_precision_test },
  { "fp_roundtrip_buffer_test", fp_roundtrip_buffer_test },
  { "fp_shortest_representation_test", fp_shortest_representation_test },
  { "fp_format_range_test", fp_format_range_test },
  { "parse_array_test", parse_array_test },
  { "materialx_config_api_struct_test", materialx_config_api_struct_test },
  { "materialx_config_api_parsing_test", materialx_config_api_parsing_test },
  { "openpbr_surface_reconstruction_test", openpbr_surface_reconstruction_test },
  { "mtlx_standard_surface_reconstruction_test", mtlx_standard_surface_reconstruction_test },
  { "nodegraph_support_test", nodegraph_support_test },
  { "materialx_shader_constants_test", materialx_shader_constants_test },
  { "materialx_shader_fallback_values_test", materialx_shader_fallback_values_test },
  { "task_queue_basic_test", task_queue_basic_test },
  { "task_queue_func_test", task_queue_func_test },
  { "task_queue_full_test", task_queue_full_test },
  { "task_queue_multithreaded_test", task_queue_multithreaded_test },
  { "task_queue_clear_test", task_queue_clear_test },
  { "tydra_connection_validation_test", tydra_connection_validation_test },
  { "tydra_inplace_conversion_guard_test", tydra_inplace_conversion_guard_test },
  { "tydra_geommesh_property_accessor_test", tydra_geommesh_property_accessor_test },
  { "tydra_memory_tracking_test", tydra_memory_tracking_test },
  { "tydra_scene_access_helper_test", tydra_scene_access_helper_test },
  { "tydra_shader_scene_access_test", tydra_shader_scene_access_test },
  { "tydra_skel_scene_access_test", tydra_skel_scene_access_test },
  { "tydra_blendshape_resolution_test", tydra_blendshape_resolution_test },
  { "tydra_material_binding_validation_test",
    tydra_material_binding_validation_test },
  { "tydra_texture_loader_policy_test", tydra_texture_loader_policy_test },
  { "tydra_envmap_loader_policy_test", tydra_envmap_loader_policy_test },
  { "tydra_geometry_light_validation_test",
    tydra_geometry_light_validation_test },
  { "tydra_mesh_fallback_policy_test", tydra_mesh_fallback_policy_test },
  { "tydra_progress_cancellation_test", tydra_progress_cancellation_test },
  { "tydra_skel_animation_validation_test",
    tydra_skel_animation_validation_test },
  { "tydra_skin_binding_validation_test",
    tydra_skin_binding_validation_test },
  // Temporarily disabled - unit-dedup needs API updates
  //{ "dedup_float_array_test", dedup_float_array_test },
  //{ "dedup_double_array_test", dedup_double_array_test },
  //{ "dedup_int_array_test", dedup_int_array_test },
  //{ "dedup_unique_arrays_test", dedup_unique_arrays_test },
  //{ "dedup_string_array_test", dedup_string_array_test },
  //{ "dedup_matrix4d_test", dedup_matrix4d_test },
  { "crate_writer_basic_creation_test", crate_writer_basic_creation_test },
  { "crate_writer_simple_prim_test", crate_writer_simple_prim_test },
  { "crate_writer_typename_encoding_test", crate_writer_typename_encoding_test },
  { "crate_writer_timesamples_test", crate_writer_timesamples_test },
  { "crate_writer_pseudoroot_ordering_test", crate_writer_pseudoroot_ordering_test },
  { "crate_writer_roundtrip_test", crate_writer_roundtrip_test },
  { "crate_writer_multiple_prims_test", crate_writer_multiple_prims_test },
  { "crate_writer_nested_prims_test", crate_writer_nested_prims_test },
  { "crate_writer_error_handling_test", crate_writer_error_handling_test },
  { "crate_writer_material_shader_test", crate_writer_material_shader_test },
  { "crate_writer_layer_metadata_test", crate_writer_layer_metadata_test },
  { "crate_writer_usd_preview_surface_test", crate_writer_usd_preview_surface_test },
  { "crate_writer_usd_uv_texture_test", crate_writer_usd_uv_texture_test },
  { "crate_writer_usd_primvar_reader_test", crate_writer_usd_primvar_reader_test },
  { "crate_writer_usd_transform2d_test", crate_writer_usd_transform2d_test },
  { "crate_writer_cone_test", crate_writer_cone_test },
  { "crate_writer_cylinder_test", crate_writer_cylinder_test },
  { "crate_writer_capsule_test", crate_writer_capsule_test },
  { "crate_writer_points_test", crate_writer_points_test },
  { "crate_writer_camera_test", crate_writer_camera_test },
  { "crate_writer_basis_curves_test", crate_writer_basis_curves_test },
  { "crate_writer_nurbs_curves_test", crate_writer_nurbs_curves_test },
  { "crate_writer_geom_subset_test", crate_writer_geom_subset_test },
  { "crate_writer_point_instancer_test", crate_writer_point_instancer_test },
  { "crate_writer_material_binding_test", crate_writer_material_binding_test },
  { "crate_writer_xform_hierarchy_test", crate_writer_xform_hierarchy_test },
  { "crate_writer_model_test", crate_writer_model_test },
  { "crate_writer_scope_test", crate_writer_scope_test },
  { "crate_writer_mesh_advanced_features_test", crate_writer_mesh_advanced_features_test },
  { "crate_writer_blend_shape_test", crate_writer_blend_shape_test },
  { "crate_writer_relationship_features_test", crate_writer_relationship_features_test },
  { "crate_writer_material_shader_enhancements_test", crate_writer_material_shader_enhancements_test },
  { "crate_writer_layer_composition_test", crate_writer_layer_composition_test },
  { "crate_writer_skeletal_animation_test", crate_writer_skeletal_animation_test },
  { "crate_writer_advanced_attributes_test", crate_writer_advanced_attributes_test },
  { "crate_writer_assetinfo_test", crate_writer_assetinfo_test },
  { "crate_writer_shader_types_test", crate_writer_shader_types_test },
  { "crate_writer_skelBinding_test", crate_writer_skelBinding_test },
  { "crate_writer_references_payloads_test", crate_writer_references_payloads_test },
  { "crate_writer_custom_metadata_types_test", crate_writer_custom_metadata_types_test },
  { "crate_writer_complex_hierarchy_test", crate_writer_complex_hierarchy_test },
  { "crate_writer_advanced_geometry_test", crate_writer_advanced_geometry_test },
  { "crate_writer_normal_interpolation_test", crate_writer_normal_interpolation_test },
  { "crate_writer_visibility_purpose_test", crate_writer_visibility_purpose_test },
  { "crate_writer_instance_offsets_test", crate_writer_instance_offsets_test },
  { "crate_writer_large_array_types_test", crate_writer_large_array_types_test },
  { "crate_writer_sphere_light_test", crate_writer_sphere_light_test },
  { "crate_writer_rect_light_test", crate_writer_rect_light_test },
  { "crate_writer_distant_light_test", crate_writer_distant_light_test },
  { "crate_writer_dome_light_test", crate_writer_dome_light_test },
  { "crate_writer_multiple_lights_test", crate_writer_multiple_lights_test },
  { "crate_writer_light_filters_test", crate_writer_light_filters_test },
  { "crate_writer_nodegraph_test", crate_writer_nodegraph_test },
  { "crate_writer_error_context_test", crate_writer_error_context_test },
  { "crate_writer_memory_limit_test", crate_writer_memory_limit_test },
  { "crate_writer_filesize_limit_test", crate_writer_filesize_limit_test },
  { "crate_writer_limit_disable_test", crate_writer_limit_disable_test },
  { "crate_writer_validation_enabled_test", crate_writer_validation_enabled_test },
  { "crate_writer_validation_disabled_test", crate_writer_validation_disabled_test },
  { "crate_writer_compression_test", crate_writer_compression_test },
  { "crate_writer_compressed_int_array_roundtrip_test", crate_writer_compressed_int_array_roundtrip_test },
  { "crate_writer_compressed_uint_array_roundtrip_test", crate_writer_compressed_uint_array_roundtrip_test },
  { "crate_writer_specializes_test", crate_writer_specializes_test },
  { "crate_writer_nan_dedup_test", crate_writer_nan_dedup_test },
  { "crate_writer_prim_meta_roundtrip_test", crate_writer_prim_meta_roundtrip_test },
  { "crate_writer_props_map_roundtrip_test", crate_writer_props_map_roundtrip_test },
  { "crate_writer_skeleton_properties_test", crate_writer_skeleton_properties_test },
  { "crate_writer_skelanim_properties_test", crate_writer_skelanim_properties_test },
  { "crate_writer_prim_children_test", crate_writer_prim_children_test },
  { "stage_get_prim_at_path_test", stage_get_prim_at_path_test },
  { "stage_find_prim_by_id_test", stage_find_prim_by_id_test },
  { "usdc_reconstruct_variant_properties_test", usdc_reconstruct_variant_properties_test },
  { "usdc_reconstruct_variant_prim_children_test", usdc_reconstruct_variant_prim_children_test },
  { "usdc_reconstruct_nested_variant_sets_test", usdc_reconstruct_nested_variant_sets_test },
  { "usdc_reconstruct_variant_name_collision_test", usdc_reconstruct_variant_name_collision_test },
  { "usdc_reconstruct_variant_selection_test", usdc_reconstruct_variant_selection_test },
  { "usdc_memory_budget_customdata_limit_test", usdc_memory_budget_customdata_limit_test },
  { "usdc_memory_budget_customdata_success_test", usdc_memory_budget_customdata_success_test },
  { "usdc_memory_budget_references_limit_test", usdc_memory_budget_references_limit_test },
  { "usdc_memory_budget_references_success_test", usdc_memory_budget_references_success_test },
  { "usdc_memory_budget_stage_meta_sublayers_limit_test", usdc_memory_budget_stage_meta_sublayers_limit_test },
  { "usdc_memory_budget_stage_meta_sublayers_success_test", usdc_memory_budget_stage_meta_sublayers_success_test },
  { "usdc_memory_budget_stage_meta_customdata_limit_test", usdc_memory_budget_stage_meta_customdata_limit_test },
  { "usdc_memory_budget_stage_meta_customdata_success_test", usdc_memory_budget_stage_meta_customdata_success_test },
  { "usdc_memory_budget_composition_limit_test", usdc_memory_budget_composition_limit_test },
  { "usdc_memory_budget_composition_success_test", usdc_memory_budget_composition_success_test },
  { "usdc_layer_variant_roundtrip_test", usdc_layer_variant_roundtrip_test },
  { "usdc_layer_variant_nested_roundtrip_test", usdc_layer_variant_nested_roundtrip_test },
  { "usdc_stage_variant_roundtrip_test", usdc_stage_variant_roundtrip_test },
  { "usdc_layer_nested_variant_sets_test", usdc_layer_nested_variant_sets_test },
  { "usdc_layer_variant_name_collision_test", usdc_layer_variant_name_collision_test },
  { "usdc_layer_variant_selection_test", usdc_layer_variant_selection_test },
  { "usdc_layer_nested_variant_props_roundtrip_test", usdc_layer_nested_variant_props_roundtrip_test },
  { "usdc_layer_multiple_variant_sets_roundtrip_test", usdc_layer_multiple_variant_sets_roundtrip_test },
  { "usdc_layer_3level_nested_roundtrip_test", usdc_layer_3level_nested_roundtrip_test },
  { "usdc_stage_variant_props_roundtrip_test", usdc_stage_variant_props_roundtrip_test },
  { "stack_vector_basic_test", stack_vector_basic_test },
  { "stack_vector_overflow_test", stack_vector_overflow_test },
  { "stack_vector_copy_test", stack_vector_copy_test },
  { "stack_vector_move_test", stack_vector_move_test },
  { "stack_vector_iterator_test", stack_vector_iterator_test },
  { "stack_vector_complex_type_test", stack_vector_complex_type_test },
  { "usda_roundtrip_basic_test", usda_roundtrip_basic_test },
  { "usda_roundtrip_xform_test", usda_roundtrip_xform_test },
  { "usda_roundtrip_mesh_test", usda_roundtrip_mesh_test },
  { "usda_roundtrip_material_test", usda_roundtrip_material_test },
  { "usda_roundtrip_timesamples_test", usda_roundtrip_timesamples_test },
  { "half_roundtrip_exhaustive_test", half_roundtrip_exhaustive_test },
  { "half_roundtrip_edge_cases_test", half_roundtrip_edge_cases_test },
  { "half_shortest_representation_test", half_shortest_representation_test },
  { "prim_reconstruct_xform_test", prim_reconstruct_xform_test },
  { "prim_reconstruct_mesh_test", prim_reconstruct_mesh_test },
  { "prim_reconstruct_material_shader_test", prim_reconstruct_material_shader_test },
  { "prim_reconstruct_sphere_light_test", prim_reconstruct_sphere_light_test },
  { "prim_reconstruct_skeleton_test", prim_reconstruct_skeleton_test },
  { "prim_reconstruct_camera_test", prim_reconstruct_camera_test },
  { "prim_reconstruct_nested_hierarchy_test", prim_reconstruct_nested_hierarchy_test },
  { "composition_inherits_test", composition_inherits_test },
  { "composition_specializes_test", composition_specializes_test },
  { "composition_variant_test", composition_variant_test },
  { "composition_has_inherits_test", composition_has_inherits_test },
  { "composition_has_specializes_test", composition_has_specializes_test },
  { "composition_has_variants_test", composition_has_variants_test },
  // USDA reader tests
  { "usda_reader_scalar_int_float_double_test", usda_reader_scalar_int_float_double_test },
  { "usda_reader_scalar_string_token_path_test", usda_reader_scalar_string_token_path_test },
  { "usda_reader_vector_matrix_types_test", usda_reader_vector_matrix_types_test },
  { "usda_reader_array_int_float_test", usda_reader_array_int_float_test },
  { "usda_reader_array_string_token_test", usda_reader_array_string_token_test },
  { "usda_reader_array_vector_types_test", usda_reader_array_vector_types_test },
  { "usda_reader_timesamples_scalar_test", usda_reader_timesamples_scalar_test },
  { "usda_reader_timesamples_array_test", usda_reader_timesamples_array_test },
  { "usda_reader_timesamples_blocked_test", usda_reader_timesamples_blocked_test },
  { "usda_reader_timesamples_token_enum_test", usda_reader_timesamples_token_enum_test },
  { "usda_reader_attribute_connection_test", usda_reader_attribute_connection_test },
  { "usda_reader_relationship_test", usda_reader_relationship_test },
  { "usda_reader_prim_metadata_test", usda_reader_prim_metadata_test },
  { "usda_reader_stage_metadata_test", usda_reader_stage_metadata_test },
  { "usda_reader_variantset_basic_test", usda_reader_variantset_basic_test },
  { "usda_reader_variantset_with_properties_test", usda_reader_variantset_with_properties_test },
  { "usd_validation_valid_core_schema_test", usd_validation_valid_core_schema_test },
  { "usd_validation_invalid_default_prim_test", usd_validation_invalid_default_prim_test },
  { "usd_validation_invalid_collection_rule_test", usd_validation_invalid_collection_rule_test },
  { "usd_validation_invalid_color_space_test", usd_validation_invalid_color_space_test },
  { "usda_reader_class_inherits_test", usda_reader_class_inherits_test },
  { "usda_reader_internal_reference_test", usda_reader_internal_reference_test },
  { "usda_reader_nested_hierarchy_test", usda_reader_nested_hierarchy_test },
  { "usda_reader_specifiers_def_over_class_test", usda_reader_specifiers_def_over_class_test },
  { "usda_reader_trailing_comma_test", usda_reader_trailing_comma_test },
  { "usda_reader_empty_prim_test", usda_reader_empty_prim_test },
  { "usda_reader_unicode_and_special_strings_test", usda_reader_unicode_and_special_strings_test },
  { "usda_reader_malformed_input_test", usda_reader_malformed_input_test },
  { "usda_reader_large_nesting_depth_test", usda_reader_large_nesting_depth_test },
  // USDC reader tests
  { "usdc_reader_scalar_types_roundtrip_test", usdc_reader_scalar_types_roundtrip_test },
  { "usdc_reader_string_token_types_roundtrip_test", usdc_reader_string_token_types_roundtrip_test },
  { "usdc_reader_vector_matrix_roundtrip_test", usdc_reader_vector_matrix_roundtrip_test },
  { "usdc_reader_array_int_float_roundtrip_test", usdc_reader_array_int_float_roundtrip_test },
  { "usdc_reader_array_string_token_roundtrip_test", usdc_reader_array_string_token_roundtrip_test },
  { "usdc_reader_array_vector_roundtrip_test", usdc_reader_array_vector_roundtrip_test },
  { "usdc_reader_timesamples_scalar_roundtrip_test", usdc_reader_timesamples_scalar_roundtrip_test },
  { "usdc_reader_timesamples_array_roundtrip_test", usdc_reader_timesamples_array_roundtrip_test },
  { "usdc_reader_timesamples_blocked_roundtrip_test", usdc_reader_timesamples_blocked_roundtrip_test },
  { "usdc_reader_timesamples_token_roundtrip_test", usdc_reader_timesamples_token_roundtrip_test },
  { "usdc_reader_connection_roundtrip_test", usdc_reader_connection_roundtrip_test },
  { "usdc_reader_relationship_roundtrip_test", usdc_reader_relationship_roundtrip_test },
  { "usdc_reader_prim_metadata_roundtrip_test", usdc_reader_prim_metadata_roundtrip_test },
  { "usdc_reader_stage_metadata_roundtrip_test", usdc_reader_stage_metadata_roundtrip_test },
  { "usdc_reader_nested_hierarchy_roundtrip_test", usdc_reader_nested_hierarchy_roundtrip_test },
  { "usdc_reader_variantset_roundtrip_test", usdc_reader_variantset_roundtrip_test },
  { "usdc_reader_large_array_compression_test", usdc_reader_large_array_compression_test },
  { "usdc_reader_inlined_scalar_test", usdc_reader_inlined_scalar_test },
  { "usdc_reader_multiple_prims_roundtrip_test", usdc_reader_multiple_prims_roundtrip_test },
  { "usdc_reader_truncated_input_test", usdc_reader_truncated_input_test },
  { "usdc_reader_corrupt_header_test", usdc_reader_corrupt_header_test },
  { "usdc_reader_corrupt_body_test", usdc_reader_corrupt_body_test },
  // Phase 0A: ValueView tests
  { "value_view_size_test", value_view_size_test },
  { "value_view_construct_test", value_view_construct_test },
  { "value_view_vector_test", value_view_vector_test },
  { "value_view_as_view_test", value_view_as_view_test },
  { "value_view_reset_test", value_view_reset_test },
  { "value_view_role_types_test", value_view_role_types_test },
  { "value_view_storage_flags_test", value_view_storage_flags_test },
  { "value_view_equality_test", value_view_equality_test },
  // Phase 0A: TypedArrayView tests
  { "typed_array_view_binary_float_test", typed_array_view_binary_float_test },
  { "typed_array_view_vector_storage_test", typed_array_view_vector_storage_test },
  { "typed_array_view_at_time_test", typed_array_view_at_time_test },
  { "typed_array_view_blocked_sample_test", typed_array_view_blocked_sample_test },
  // Phase 0A: TypedArray TimeSamples tests
  { "typed_array_dedup_int_test", typed_array_dedup_int_test },
  { "typed_array_dedup_float_double_test", typed_array_dedup_float_double_test },
  { "typed_array_vector_compat_test", typed_array_vector_compat_test },
  { "typed_array_scalar_values_test", typed_array_scalar_values_test },
  // Phase 1: Composition arcs tests
  { "comp_inherits_child_prims_test", comp_inherits_child_prims_test },
  { "comp_inherits_multiple_bases_test", comp_inherits_multiple_bases_test },
  { "comp_specializes_child_prims_test", comp_specializes_child_prims_test },
  { "comp_variant_two_sets_test", comp_variant_two_sets_test },
  { "comp_variant_no_selection_test", comp_variant_no_selection_test },
  { "comp_variant_nested_children_test", comp_variant_nested_children_test },
  { "comp_override_basic_test", comp_override_basic_test },
  { "comp_override_replace_property_test", comp_override_replace_property_test },
  { "comp_override_add_new_property_test", comp_override_add_new_property_test },
  { "comp_inherit_primspec_api_test", comp_inherit_primspec_api_test },
  { "comp_override_primspec_api_test", comp_override_primspec_api_test },
  { "comp_has_references_test", comp_has_references_test },
  { "comp_has_payload_test", comp_has_payload_test },
  { "comp_has_over_test", comp_has_over_test },
  { "comp_extract_variants_from_layer_test", comp_extract_variants_from_layer_test },
  { "comp_extract_variants_from_stage_test", comp_extract_variants_from_stage_test },
  { "comp_layer_to_stage_test", comp_layer_to_stage_test },
  { "comp_list_variant_selections_test", comp_list_variant_selections_test },
  { "comp_variant_select_primspec_test", comp_variant_select_primspec_test },
  { "comp_apply_variant_selector_test", comp_apply_variant_selector_test },
  { "comp_implied_inherits_test", comp_implied_inherits_test },
  { "comp_inherits_cycle_detection_test", comp_inherits_cycle_detection_test },
  { "comp_specializes_cycle_detection_test", comp_specializes_cycle_detection_test },
  { "comp_active_false_filtering_test", comp_active_false_filtering_test },
  { "comp_multi_target_specializes_test", comp_multi_target_specializes_test },
  { "comp_inherits_append_listop_test", comp_inherits_append_listop_test },
  { "comp_implied_specializes_test", comp_implied_specializes_test },
  { "comp_liverps_integration_test", comp_liverps_integration_test },
  { "comp_specializes_globally_weaker_test", comp_specializes_globally_weaker_test },
  { "comp_payload_load_policy_test", comp_payload_load_policy_test },
  { "comp_inherits_delete_listop_test", comp_inherits_delete_listop_test },
  { "comp_inherits_order_listop_test", comp_inherits_order_listop_test },
  { "comp_relocates_simple_rename_test", comp_relocates_simple_rename_test },
  { "comp_relocates_root_rename_test", comp_relocates_root_rename_test },
  { "comp_relocates_cross_parent_test", comp_relocates_cross_parent_test },
  { "comp_relocates_path_remap_test", comp_relocates_path_remap_test },
  // Phase 1b: DAG-based composition graph tests
  { "compgraph_basic_prim_index_test", compgraph_basic_prim_index_test },
  { "compgraph_strength_order_test", compgraph_strength_order_test },
  { "compgraph_inherits_dag_test", compgraph_inherits_dag_test },
  { "compgraph_specializes_globally_weak_test", compgraph_specializes_globally_weak_test },
  { "compgraph_references_dag_test", compgraph_references_dag_test },
  { "compgraph_variants_deferred_test", compgraph_variants_deferred_test },
  { "compgraph_cycle_detection_test", compgraph_cycle_detection_test },
  { "compgraph_implied_inherits_test", compgraph_implied_inherits_test },
  { "compgraph_instance_key_identical_test", compgraph_instance_key_identical_test },
  { "compgraph_instance_key_different_test", compgraph_instance_key_different_test },
  { "compgraph_payload_deferred_test", compgraph_payload_deferred_test },
  { "compgraph_build_stage_simple_test", compgraph_build_stage_simple_test },
  { "compgraph_build_stage_inherits_test", compgraph_build_stage_inherits_test },
  { "compgraph_random_flat_prims_test", compgraph_random_flat_prims_test },
  { "compgraph_random_deep_hierarchy_test", compgraph_random_deep_hierarchy_test },
  { "compgraph_random_inherits_chain_test", compgraph_random_inherits_chain_test },
  { "compgraph_random_mixed_arcs_test", compgraph_random_mixed_arcs_test },
  { "compgraph_random_specializes_vs_inherits_test", compgraph_random_specializes_vs_inherits_test },
  // Phase 2: Stage API tests (extended)
  { "stage_add_root_prim_test", stage_add_root_prim_test },
  { "stage_replace_root_prim_test", stage_replace_root_prim_test },
  { "stage_export_to_string_test", stage_export_to_string_test },
  { "stage_commit_prim_id_test", stage_commit_prim_id_test },
  { "stage_metas_test", stage_metas_test },
  { "stage_memory_estimation_test", stage_memory_estimation_test },
  { "stage_empty_test", stage_empty_test },
  { "stage_nested_hierarchy_test", stage_nested_hierarchy_test },
  // Phase 2: Layer API tests
  { "layer_create_empty_test", layer_create_empty_test },
  { "layer_add_primspec_test", layer_add_primspec_test },
  { "layer_emplace_primspec_test", layer_emplace_primspec_test },
  { "layer_replace_primspec_test", layer_replace_primspec_test },
  { "layer_find_primspec_at_test", layer_find_primspec_at_test },
  { "layer_check_unresolved_refs_test", layer_check_unresolved_refs_test },
  { "layer_check_unresolved_payload_test", layer_check_unresolved_payload_test },
  { "layer_check_unresolved_inherits_test", layer_check_unresolved_inherits_test },
  { "layer_check_unresolved_specializes_test", layer_check_unresolved_specializes_test },
  { "layer_check_unresolved_variant_test", layer_check_unresolved_variant_test },
  { "layer_check_over_primspec_test", layer_check_over_primspec_test },
  { "layer_metas_test", layer_metas_test },
  { "layer_asset_resolution_state_test", layer_asset_resolution_state_test },
  { "layer_memory_estimation_test", layer_memory_estimation_test },
  // PrimSpec tests
  { "primspec_create_test", primspec_create_test },
  { "primspec_specifiers_test", primspec_specifiers_test },
  { "primspec_properties_test", primspec_properties_test },
  { "primspec_children_test", primspec_children_test },
  { "primspec_variant_selection_test", primspec_variant_selection_test },
  { "primspec_metas_test", primspec_metas_test },
  // Prim API tests
  { "prim_type_check_test", prim_type_check_test },
  { "prim_add_child_test", prim_add_child_test },
  { "prim_element_name_test", prim_element_name_test },
  { "prim_specifier_test", prim_specifier_test },
  { "prim_absolute_path_test", prim_absolute_path_test },
  { "prim_data_access_test", prim_data_access_test },
  { "prim_replace_child_test", prim_replace_child_test },
  // USDA writer tests
  { "usda_writer_empty_stage_test", usda_writer_empty_stage_test },
  { "usda_writer_xform_test", usda_writer_xform_test },
  { "usda_writer_mesh_test", usda_writer_mesh_test },
  { "usda_writer_material_test", usda_writer_material_test },
  { "usda_writer_metadata_test", usda_writer_metadata_test },
  { "usda_writer_hierarchy_test", usda_writer_hierarchy_test },
  { "usda_writer_special_chars_test", usda_writer_special_chars_test },
  { "usda_writer_idempotent_test", usda_writer_idempotent_test },
  { "usda_writer_api_test", usda_writer_api_test },
  // Phase 5: Tydra RenderScene end-to-end tests
  { "tydra_renderscene_empty_stage_test", tydra_renderscene_empty_stage_test },
  { "tydra_renderscene_single_mesh_test", tydra_renderscene_single_mesh_test },
  { "tydra_renderscene_xform_hierarchy_test",
    tydra_renderscene_xform_hierarchy_test },
  { "tydra_renderscene_material_binding_test",
    tydra_renderscene_material_binding_test },
  { "tydra_renderscene_sphere_light_test",
    tydra_renderscene_sphere_light_test },
  { "tydra_renderscene_camera_test", tydra_renderscene_camera_test },
  { "tydra_renderscene_memory_estimation_test",
    tydra_renderscene_memory_estimation_test },
  // Phase 5: Tydra shader / scene-access tests
  { "tydra_shader_list_prims_test", tydra_shader_list_prims_test },
  { "tydra_shader_list_shaders_test", tydra_shader_list_shaders_test },
  { "tydra_shader_get_bound_material_test",
    tydra_shader_get_bound_material_test },
  { "tydra_shader_property_access_test", tydra_shader_property_access_test },
  { "tydra_shader_xform_node_build_test",
    tydra_shader_xform_node_build_test },
  // Security tests
  { "security_empty_input_test", security_empty_input_test },
  { "security_truncated_header_test", security_truncated_header_test },
  { "security_null_bytes_test", security_null_bytes_test },
  { "security_deeply_nested_test", security_deeply_nested_test },
  { "security_huge_array_test", security_huge_array_test },
  { "security_malformed_utf8_test", security_malformed_utf8_test },
  { "security_recursive_reference_test", security_recursive_reference_test },
  // USDZ writer and validation tests
  { "usdz_writer_basic_roundtrip_test", usdz_writer_basic_roundtrip_test },
  { "usdz_writer_with_assets_test", usdz_writer_with_assets_test },
  { "usdz_validator_alignment_test", usdz_validator_alignment_test },
  { "usdz_validator_crc32_test", usdz_validator_crc32_test },
  { "usdz_validator_size_consistency_test", usdz_validator_size_consistency_test },
  { "usdz_validator_empty_input_test", usdz_validator_empty_input_test },
  { "usdz_writer_file_roundtrip_test", usdz_writer_file_roundtrip_test },
  { "usdz_validator_large_asset_test", usdz_validator_large_asset_test },
  { "usdz_validator_bad_extension_test", usdz_validator_bad_extension_test },
  // Pretty-printer column wrap tests
  { "column_wrap_disabled_test", column_wrap_disabled_test },
  { "column_wrap_float3_array_test", column_wrap_float3_array_test },
  { "column_wrap_int_array_test", column_wrap_int_array_test },
  { "column_wrap_deep_indent_test", column_wrap_deep_indent_test },
  { "column_wrap_string_no_wrap_test", column_wrap_string_no_wrap_test },
  // USDC writer — usdGeom and usdSkel roundtrip
  { "usdc_writer_mesh_basic_test", usdc_writer_mesh_basic_test },
  { "usdc_writer_mesh_subdiv_test", usdc_writer_mesh_subdiv_test },
  { "usdc_writer_mesh_velocities_test", usdc_writer_mesh_velocities_test },
  { "usdc_writer_points_test", usdc_writer_points_test },
  { "usdc_writer_basiscurves_test", usdc_writer_basiscurves_test },
  { "usdc_writer_geomsubset_test", usdc_writer_geomsubset_test },
  { "usdc_writer_camera_test", usdc_writer_camera_test },
  { "usdc_writer_primitives_test", usdc_writer_primitives_test },
  { "usdc_writer_skeleton_test", usdc_writer_skeleton_test },
  { "usdc_writer_skelanimation_test", usdc_writer_skelanimation_test },
  { "usdc_writer_blendshape_test", usdc_writer_blendshape_test },
  { "usdc_writer_skelroot_test", usdc_writer_skelroot_test },
  { "usdc_writer_shader_terminal_test", usdc_writer_shader_terminal_test },
  { "usdc_writer_material_outputs_test", usdc_writer_material_outputs_test },
  { "usdc_writer_uvtexture_test", usdc_writer_uvtexture_test },
  { "usdc_writer_primvarreader_test", usdc_writer_primvarreader_test },
  { "usdc_writer_transform2d_test", usdc_writer_transform2d_test },
  { "usdc_writer_previewsurface_full_test", usdc_writer_previewsurface_full_test },
  { "usdc_writer_nurbscurves_test", usdc_writer_nurbscurves_test },
  { "usdc_writer_pointinstancer_test", usdc_writer_pointinstancer_test },
  { "usdc_writer_pointinstancer_prototypes_test", usdc_writer_pointinstancer_prototypes_test },
  { "usdc_writer_instanceable_test", usdc_writer_instanceable_test },
  { "usdc_writer_sphere_light_test", usdc_writer_sphere_light_test },
  { "usdc_writer_distant_light_test", usdc_writer_distant_light_test },
  { "usdc_writer_dome_light_test", usdc_writer_dome_light_test },
  { "usdc_writer_light_shadow_shaping_test", usdc_writer_light_shadow_shaping_test },
  { "usdc_writer_apischemas_test", usdc_writer_apischemas_test },
  { "usdc_writer_materialx_config_test", usdc_writer_materialx_config_test },
  // Path utility and tree encoding tests
  { "path_lessthan_basic_test", path_lessthan_basic_test },
  { "path_lessthan_variant_test", path_lessthan_variant_test },
  { "path_has_prefix_basic_test", path_has_prefix_basic_test },
  { "path_has_prefix_variant_test", path_has_prefix_variant_test },
  { "path_get_parent_basic_test", path_get_parent_basic_test },
  { "path_get_parent_variant_test", path_get_parent_variant_test },
  { "path_tree_flat_siblings_test", path_tree_flat_siblings_test },
  { "path_tree_deep_hierarchy_test", path_tree_deep_hierarchy_test },
  { "path_tree_mixed_props_test", path_tree_mixed_props_test },
  { "path_tree_variant_basic_test", path_tree_variant_basic_test },
  // Variant roundtrip tests
  { "usdc_writer_variant_with_props_test", usdc_writer_variant_with_props_test },
  { "usdc_writer_variant_multi_selection_test", usdc_writer_variant_multi_selection_test },
  { "usdc_writer_variant_nested_test", usdc_writer_variant_nested_test },
  { "usdc_writer_variant_with_selection_test", usdc_writer_variant_with_selection_test },
  { "usdc_writer_variant_with_children_test", usdc_writer_variant_with_children_test },
  { "usdc_writer_variant_empty_test", usdc_writer_variant_empty_test },
  { "usdc_writer_variant_multiple_sets_test", usdc_writer_variant_multiple_sets_test },
  { "usdc_writer_variant_props_and_children_roundtrip_test", usdc_writer_variant_props_and_children_roundtrip_test },
  { "usdc_writer_variant_3level_nested_test", usdc_writer_variant_3level_nested_test },
  { "usdc_writer_variant_nested_with_props_test", usdc_writer_variant_nested_with_props_test },
  // Physics + MuJoCo
  { "physics_scene_reconstruct_test", physics_scene_reconstruct_test },
  { "physics_scene_mjc_scene_api_test", physics_scene_mjc_scene_api_test },
  { "physics_revolute_joint_test", physics_revolute_joint_test },
  { "physics_prismatic_joint_test", physics_prismatic_joint_test },
  { "physics_fixed_joint_test", physics_fixed_joint_test },
  { "physics_distance_joint_test", physics_distance_joint_test },
  { "physics_spherical_joint_test", physics_spherical_joint_test },
  { "physics_joint_mjc_api_test", physics_joint_mjc_api_test },
  { "mjc_actuator_test", mjc_actuator_test },
  { "mjc_tendon_test", mjc_tendon_test },
  { "mjc_keyframe_test", mjc_keyframe_test },
  { "physics_pprint_roundtrip_test", physics_pprint_roundtrip_test },
  { "physics_to_json_test", physics_to_json_test },
  // IK solver
  { "ik_forward_kinematics_test", ik_forward_kinematics_test },
  { "ik_ccd_solve_test", ik_ccd_solve_test },
  { "ik_fabrik_solve_test", ik_fabrik_solve_test },
  { "ik_joint_limits_test", ik_joint_limits_test },
  { "ik_unreachable_target_test", ik_unreachable_target_test },
#if defined(TINYUSDZ_WITH_PXR_COMPAT_API)
  { "pxr_compat_api_test", pxr_compat_api_test },
#endif
  { nullptr, nullptr }
};
