name: Android

on:
  # Allows manual build verification on any branch/tag (e.g. physics-2026)
  workflow_dispatch:
  push:
    branches: [ release ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ release ]

jobs:


  # Android(aarch64) build
  build-android:

    runs-on: ubuntu-latest
    name: Build for Android(arm64v8a)
    env:
      ANDROID_NDK_VERSION: 29.0.14206865
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show android sdk root
        run: |
            env | grep ANDROID
            echo $ANDROID_SDK_ROOT
      - name: Setup
        run: |
            sudo apt-get install -y ninja-build tree
      - name: Install Android NDK
        run: |
            "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" "ndk;$ANDROID_NDK_VERSION"
            echo "ANDROID_NDK_LATEST_HOME=$ANDROID_SDK_ROOT/ndk/$ANDROID_NDK_VERSION" >> "$GITHUB_ENV"
      - name: Show android sdk details
        run: |
            tree $ANDROID_SDK_ROOT
      - name: CmakeAndBuild
        run: |
            ./scripts/bootstrap-android-cmake-linux.sh
            cd build-android
            ninja -v
