# Simple workflow that builds wasm and publish to npm registry
name: Build and publish wasm

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'NPM Release Version'
        required: true
        type: string
        default: 1.0.0
      npm_tag:
        description: 'NPM Tag'
        required: true
        type: string
        default: preview

jobs:
  tinyusdz-wasm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: npm
          cache-dependency-path: web/npm/package-lock.json
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk

          ./emsdk install 4.0.9
          ./emsdk activate 4.0.9

          # Revert to 3.1.51 if there is a problem.
          ## from https://github.com/Twinklebear/webgpu-cpp-usdz/blob/main/.github/workflows/deploy-page.yml
          ## TODO: 3.1.52 has a change to WebGPU API that is incompatible
          ## with the C++ bindings I have in the repo?
          #./emsdk install 3.1.51
          #./emsdk activate 3.1.51
      - name: Configure WASM32
        run: |
          source ./emsdk/emsdk_env.sh
          emcmake cmake -S web -B web/cmake-build -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel

      - name: Build WASM32
        run: |
          source ./emsdk/emsdk_env.sh
          cmake --build web/cmake-build --parallel

      - name: Configure WASM64
        run: |
          source ./emsdk/emsdk_env.sh
          emcmake cmake -S web -B web/cmake-build64 -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DTINYUSDZ_WASM64=1

      - name: Build WASM64
        run: |
          source ./emsdk/emsdk_env.sh
          cmake --build web/cmake-build64 --parallel

      - name: Install npm dependencies
        working-directory: ${{ github.workspace }}/web/npm
        run: |
          npm ci

      - name: Stage npm package
        working-directory: ${{ github.workspace }}/web/npm
        run: |
          npm run build:stage -- --release-version=${{ github.event.inputs.release_version }}

      - name: Validate npm package
        working-directory: ${{ github.workspace }}/web/npm
        run: |
          npm run validate

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'tinyusdz-npm-${{ github.event.inputs.release_version }}'
          path: ${{ github.workspace }}/web/npm/dist

      - name: Publish package
        working-directory: ${{ github.workspace }}/web/npm/dist
        run: |
          npm publish --provenance --access public --tag ${{ github.event.inputs.npm_tag }}
